-- =========================
-- TRIGGERS
-- =========================

-- =========================
--Baja la cantidad de producto cuando se hace una venta y de agrega en la tabla DETALLE_VENTA
CREATE OR REPLACE TRIGGER TRG_DESCONTAR_STOCK
AFTER INSERT ON DETALLE_VENTA
FOR EACH ROW
BEGIN
    UPDATE PRODUCTOS
    SET STOCK = STOCK - :NEW.CANTIDAD
    WHERE ID_PRODUCTO = :NEW.ID_PRODUCTO;
END;

-- =========================
--Evita que se pueda vender mas producto del que hay en stock
CREATE OR REPLACE TRIGGER TRG_VALIDAR_STOCK
BEFORE INSERT ON DETALLE_VENTA
FOR EACH ROW
DECLARE
    v_stock PRODUCTOS.STOCK%TYPE;
BEGIN
    SELECT STOCK INTO v_stock
    FROM PRODUCTOS
    WHERE ID_PRODUCTO = :NEW.ID_PRODUCTO;

    IF v_stock < :NEW.CANTIDAD THEN
        RAISE_APPLICATION_ERROR(-20001, 'No hay suficiente stock');
    END IF;
END;

-- =========================
-- Crea la cantidad de venta hecha
CREATE OR REPLACE TRIGGER TRG_CALCULAR_TOTAL
AFTER INSERT ON DETALLE_VENTA
FOR EACH ROW
BEGIN
    UPDATE VENTAS
    SET TOTAL =
    (
        SELECT SUM(CANTIDAD * PRECIO_UNITARIO)
        FROM DETALLE_VENTA
        WHERE ID_VENTA = :NEW.ID_VENTA
    )
    WHERE ID_VENTA = :NEW.ID_VENTA;
END;

-- =========================
-- Crea auditoria para las tablas mas importantes 

-- AUDITORIA TABLA VENTAS
CREATE OR REPLACE TRIGGER TRG_AUD_PRODUCTOS
AFTER UPDATE OR INSERT OR DELETE ON PRODUCTOS
FOR EACH ROW
BEGIN
-- INSERT
IF INSERTING THEN
INSERT INTO AUDITORIA_SISTEMA
(TABLA_AFECTADA,OPERACION,ID_REGISTRO,USUARIO_DB)
VALUES
('PRODUCTOS','INSERT',:NEW.ID_PRODUCTO,USER);
END IF;
-- DELETE
IF DELETING THEN
INSERT INTO AUDITORIA_SISTEMA
(TABLA_AFECTADA,OPERACION,ID_REGISTRO,USUARIO_DB)
VALUES
('PRODUCTOS','DELETE',:OLD.ID_PRODUCTO,USER);
END IF;
-- UPDATE PRECIO
IF UPDATING AND :OLD.PRECIO <> :NEW.PRECIO THEN
INSERT INTO AUDITORIA_SISTEMA
(TABLA_AFECTADA,OPERACION,ID_REGISTRO,CAMPO_MODIFICADO,VALOR_ANTERIOR,VALOR_NUEVO,USUARIO_DB)
VALUES
('PRODUCTOS','UPDATE',:NEW.ID_PRODUCTO,'PRECIO',:OLD.PRECIO,:NEW.PRECIO,USER);
END IF;
-- UPDATE STOCK
IF UPDATING AND :OLD.STOCK <> :NEW.STOCK THEN
INSERT INTO AUDITORIA_SISTEMA
(TABLA_AFECTADA,OPERACION,ID_REGISTRO,CAMPO_MODIFICADO,VALOR_ANTERIOR,VALOR_NUEVO,USUARIO_DB)
VALUES
('PRODUCTOS','UPDATE',:NEW.ID_PRODUCTO,'STOCK',:OLD.STOCK,:NEW.STOCK,USER);
END IF;
-- UPDATE NOMBRE
IF UPDATING AND :OLD.NOMBRE <> :NEW.NOMBRE THEN
INSERT INTO AUDITORIA_SISTEMA
(TABLA_AFECTADA,OPERACION,ID_REGISTRO,CAMPO_MODIFICADO,VALOR_ANTERIOR,VALOR_NUEVO,USUARIO_DB)
VALUES
('PRODUCTOS','UPDATE',:NEW.ID_PRODUCTO,'NOMBRE',:OLD.NOMBRE,:NEW.NOMBRE,USER);
END IF;

END;


-- AUDITORIA TABLA VENTAS
CREATE OR REPLACE TRIGGER TRG_AUD_VENTAS
AFTER INSERT OR UPDATE OR DELETE ON VENTAS
FOR EACH ROW
BEGIN

IF INSERTING THEN
INSERT INTO AUDITORIA_SISTEMA
(TABLA_AFECTADA,OPERACION,ID_REGISTRO,USUARIO_DB)
VALUES
('VENTAS','INSERT',:NEW.ID_VENTA,USER);
END IF;

IF DELETING THEN
INSERT INTO AUDITORIA_SISTEMA
(TABLA_AFECTADA,OPERACION,ID_REGISTRO,USUARIO_DB)
VALUES
('VENTAS','DELETE',:OLD.ID_VENTA,USER);
END IF;

END;

-- AUDITORIA TABLA CLIENTES
CREATE OR REPLACE TRIGGER TRG_AUD_CLIENTES
AFTER INSERT OR UPDATE OR DELETE ON CLIENTES
FOR EACH ROW
BEGIN

IF INSERTING THEN
INSERT INTO AUDITORIA_SISTEMA
(TABLA_AFECTADA,OPERACION,ID_REGISTRO,USUARIO_DB)
VALUES
('CLIENTES','INSERT',:NEW.ID_CLIENTE,USER);
END IF;

IF DELETING THEN
INSERT INTO AUDITORIA_SISTEMA
(TABLA_AFECTADA,OPERACION,ID_REGISTRO,USUARIO_DB)
VALUES
('CLIENTES','DELETE',:OLD.ID_CLIENTE,USER);
END IF;

END;

SELECT * FROM AUDITORIA_SISTEMA;