----Primera excepcion - tabla Clientes
SET SERVEROUTPUT ON;
DECLARE 
    VNOM VARCHAR2(100);
    VID NUMBER := &v;
BEGIN
    SELECT NOMBRE
    INTO VNOM
    FROM CLIENTES
    WHERE ID_CLIENTE = VID;

    DBMS_OUTPUT.PUT_LINE('CLIENTE: ' || VNOM);

EXCEPTION
  WHEN NO_DATA_FOUND THEN
        DBMS_OUTPUT.PUT_LINE('ERROR: CLIENTE NO EXISTE');
END;
      

-----Segunda Excepcion - tabla Usuarios
SET SERVEROUTPUT ON;
DECLARE 
    VNOM VARCHAR2(100);
    VID NUMBER := &v;
BEGIN
    SELECT USERNAME
    INTO VNOM
    FROM USUARIOS
    WHERE ID_CLIENTE = VID;

    DBMS_OUTPUT.PUT_LINE('USUARIO: ' || VNOM);

EXCEPTION
  WHEN NO_DATA_FOUND THEN
        DBMS_OUTPUT.PUT_LINE('ERROR: USUARIO NO EXISTE');
END;

----Tercer excepcion - tabla proveedores 
SET SERVEROUTPUT ON;
DECLARE 
    VNOM VARCHAR2(100);
    VID NUMBER := &v;
BEGIN
    SELECT NOMBRE
    INTO VNOM
    FROM PROVEEDORES
    WHERE ID_PROVEEDOR = VID;

    DBMS_OUTPUT.PUT_LINE('PROVEEDOR: ' || VNOM);

EXCEPTION
  WHEN NO_DATA_FOUND THEN
        DBMS_OUTPUT.PUT_LINE('ERROR: PROVEEDOR NO EXISTE');
END;

----Cuarta excepcion - tabla categorias
SET SERVEROUTPUT ON;
DECLARE 
    VNOM VARCHAR2(100);
    VID NUMBER := &v;
BEGIN
    SELECT NOMBRE
    INTO VNOM
    FROM PROVEEDORES
    WHERE ID_PROVEEDOR = VID;

    DBMS_OUTPUT.PUT_LINE('PROVEEDOR: ' || VNOM);

EXCEPTION
  WHEN NO_DATA_FOUND THEN
        DBMS_OUTPUT.PUT_LINE('ERROR: Categoria NO EXISTE');
END;

----Quinta Excepcion - TRG_VALIDAR_STOCK
SET SERVEROUTPUT ON;
DECLARE
    v_stock NUMBER;
    VID NUMBER := &v;
BEGIN
    SELECT STOCK
    INTO v_stock
    FROM PRODUCTOS
    WHERE ID_PRODUCTO = VID;

    DBMS_OUTPUT.PUT_LINE('Producto: ' || v_stock);


EXCEPTION
    WHEN NO_DATA_FOUND THEN
        DBMS_OUTPUT.PUT_LINE('ERROR: PRODUCTO NO EXISTE');
END;
/


----Sexta Excepcion - Trigger TRG_VALIDAR_STOCK
SET SERVEROUTPUT ON;
DECLARE
    v_stock NUMBER;
    VID NUMBER := &v;
BEGIN
    SELECT STOCK
    INTO v_stock
    FROM PRODUCTOS
    WHERE ID_PRODUCTO = VID;

    DBMS_OUTPUT.PUT_LINE('Producto: ' || v_stock);


EXCEPTION
    WHEN NO_DATA_FOUND THEN
        DBMS_OUTPUT.PUT_LINE('ERROR: PRODUCTO NO EXISTE');
END;
/


----Septima excepcion - funtion TOTAL_COMPRADO_CLIENTE
SET SERVEROUTPUT ON;
DECLARE
    v_total NUMBER;
    VNOM VARCHAR2(100);
    VID NUMBER := &v;
BEGIN
    SELECT NOMBRE
    INTO VNOM
    FROM CLIENTES
    WHERE ID_CLIENTE = VID;

    DBMS_OUTPUT.PUT_LINE('TOTAL Comprado: ' || v_total);

EXCEPTION
    WHEN NO_DATA_FOUND THEN
        DBMS_OUTPUT.PUT_LINE('ERROR: lo comprado no existe');
END;
/

