----PS/SQL anonimo - cursor que busca todos los datos de la tabla marca con Adata
SET SERVEROUTPUT ON;
DECLARE
    V_ID_PRODUCTO PRODUCTOS.ID_PRODUCTO%TYPE;
    V_NOMBRE PRODUCTOS.NOMBRE%TYPE;
    V_PRECIO PRODUCTOS.PRECIO%TYPE;

    CURSOR C_PRODUCTOS_ADATA IS
        SELECT P.ID_PRODUCTO, P.NOMBRE, P.PRECIO
        FROM PRODUCTOS P
        INNER JOIN MARCAS M
            ON P.ID_MARCA = M.ID_MARCA
        WHERE M.NOMBRE_MARCA = 'Adata';

BEGIN
    OPEN C_PRODUCTOS_ADATA;

    LOOP
        FETCH C_PRODUCTOS_ADATA INTO V_ID_PRODUCTO, V_NOMBRE, V_PRECIO;
        EXIT WHEN C_PRODUCTOS_ADATA%NOTFOUND;

        DBMS_OUTPUT.PUT_LINE(
            'ID: ' || V_ID_PRODUCTO ||
            ' - NOMBRE: ' || V_NOMBRE ||
            ' - PRECIO: ' || V_PRECIO
        );
    END LOOP;

    CLOSE C_PRODUCTOS_ADATA;
END;
/

----PS/SQL anonimo - busca los productos menores a 5
DECLARE
    V_ID PRODUCTOS.ID_PRODUCTO%TYPE;
    V_NOMBRE PRODUCTOS.NOMBRE%TYPE;
    V_STOCK PRODUCTOS.STOCK%TYPE;

    CURSOR C_PRODUCTOS_STOCK IS
        SELECT ID_PRODUCTO, NOMBRE, STOCK
        FROM PRODUCTOS
        WHERE STOCK < 5;

BEGIN
    OPEN C_PRODUCTOS_STOCK;

    LOOP
        FETCH C_PRODUCTOS_STOCK INTO V_ID, V_NOMBRE, V_STOCK;
        EXIT WHEN C_PRODUCTOS_STOCK%NOTFOUND;

        DBMS_OUTPUT.PUT_LINE(
            'ID: ' || V_ID ||
            ' - NOMBRE: ' || V_NOMBRE ||
            ' - STOCK: ' || V_STOCK
        );
    END LOOP;

    CLOSE C_PRODUCTOS_STOCK;
END;
/


-----PS/SQL anonimo - busca las ventas por ID_METODO
DECLARE
    V_METODO     NUMBER := &metodo;
    V_ID_DETALLE NUMBER;
    V_ID_CLIENTE NUMBER;
    V_TOTAL      NUMBER;
    V_FECHA      DATE;

    CURSOR C_VENTAS_METODO IS
        SELECT
            DETALLE_VENTAS.ID_DETALLE,
            DETALLE_VENTAS.ID_CLIENTE,
            SUM(VENTAS.CANTIDAD * VENTAS.PRECIO_UNITARIO) AS TOTAL,
            DETALLE_VENTAS.FECHA_VENTA
        FROM DETALLE_VENTAS
        JOIN VENTAS ON VENTAS.ID_DETALLE = DETALLE_VENTAS.ID_DETALLE
        WHERE DETALLE_VENTAS.ID_METODO = V_METODO
        GROUP BY DETALLE_VENTAS.ID_DETALLE, DETALLE_VENTAS.ID_CLIENTE, DETALLE_VENTAS.FECHA_VENTA;

BEGIN
    OPEN C_VENTAS_METODO;
    LOOP
        FETCH C_VENTAS_METODO INTO V_ID_DETALLE, V_ID_CLIENTE, V_TOTAL, V_FECHA;
        EXIT WHEN C_VENTAS_METODO%NOTFOUND;
        DBMS_OUTPUT.PUT_LINE(
            'PEDIDO: '     || V_ID_DETALLE ||
            ' - CLIENTE: ' || V_ID_CLIENTE ||
            ' - TOTAL: '   || V_TOTAL      ||
            ' - FECHA: '   || V_FECHA
        );
    END LOOP;
    CLOSE C_VENTAS_METODO;

EXCEPTION
    WHEN NO_DATA_FOUND THEN
        DBMS_OUTPUT.PUT_LINE('No hay ventas para ese método de pago.');
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('Error: ' || SQLERRM);
END;