----Primer cursor - cursor que busca todos los datos de la tabla marca con Adata
SET SERVEROUTPUT ON;
DECLARE
    V_ID_PRODUCTO PRODUCTOS.ID_PRODUCTO%TYPE;
    V_NOMBRE PRODUCTOS.NOMBRE%TYPE;
    V_PRECIO PRODUCTOS.PRECIO%TYPE;

    CURSOR C_PRODUCTOS_ADATA IS
        SELECT P.ID_PRODUCTO, P.NOMBRE, P.PRECIO
        FROM PRODUCTOS P
        INNER JOIN MARCAS M
            ON P.ID_MARCA = M.ID_MARCA
        WHERE M.NOMBRE_MARCA = 'Adata';

BEGIN
    OPEN C_PRODUCTOS_ADATA;

    LOOP
        FETCH C_PRODUCTOS_ADATA INTO V_ID_PRODUCTO, V_NOMBRE, V_PRECIO;
        EXIT WHEN C_PRODUCTOS_ADATA%NOTFOUND;

        DBMS_OUTPUT.PUT_LINE(
            'ID: ' || V_ID_PRODUCTO ||
            ' - NOMBRE: ' || V_NOMBRE ||
            ' - PRECIO: ' || V_PRECIO
        );
    END LOOP;

    CLOSE C_PRODUCTOS_ADATA;
END;
/

----Srgundo cursor - busca los productos menores a 5
DECLARE
    V_ID PRODUCTOS.ID_PRODUCTO%TYPE;
    V_NOMBRE PRODUCTOS.NOMBRE%TYPE;
    V_STOCK PRODUCTOS.STOCK%TYPE;

    CURSOR C_PRODUCTOS_STOCK IS
        SELECT ID_PRODUCTO, NOMBRE, STOCK
        FROM PRODUCTOS
        WHERE STOCK < 5;

BEGIN
    OPEN C_PRODUCTOS_STOCK;

    LOOP
        FETCH C_PRODUCTOS_STOCK INTO V_ID, V_NOMBRE, V_STOCK;
        EXIT WHEN C_PRODUCTOS_STOCK%NOTFOUND;

        DBMS_OUTPUT.PUT_LINE(
            'ID: ' || V_ID ||
            ' - NOMBRE: ' || V_NOMBRE ||
            ' - STOCK: ' || V_STOCK
        );
    END LOOP;

    CLOSE C_PRODUCTOS_STOCK;
END;
/


-----Cursor 3 que busca las ventas por ID_METODO
DECLARE
    V_METODO NUMBER := &metodo;

    V_ID_VENTA VENTAS.ID_VENTA%TYPE;
    V_ID_CLIENTE VENTAS.ID_CLIENTE%TYPE;
    V_TOTAL VENTAS.TOTAL%TYPE;
    V_FECHA VENTAS.FECHA_VENTA%TYPE;

    CURSOR C_VENTAS_METODO IS
        SELECT ID_VENTA, ID_CLIENTE, TOTAL, FECHA_VENTA
        FROM VENTAS
        WHERE ID_METODO = V_METODO;

BEGIN
    OPEN C_VENTAS_METODO;

    LOOP
        FETCH C_VENTAS_METODO INTO V_ID_VENTA, V_ID_CLIENTE, V_TOTAL, V_FECHA;
        EXIT WHEN C_VENTAS_METODO%NOTFOUND;

        DBMS_OUTPUT.PUT_LINE(
            'VENTA: ' || V_ID_VENTA ||
            ' - CLIENTE: ' || V_ID_CLIENTE ||
            ' - TOTAL: ' || V_TOTAL ||
            ' - FECHA: ' || V_FECHA
        );
    END LOOP;

    CLOSE C_VENTAS_METODO;
END;
/