-- =========================
-- Tablespaces
-- =========================
CREATE TABLESPACE Proyecto_Base_de_DatosLN
DATAFILE 'C:\ORACLE\ORADATA\ORCL\Proyecto_Base_de_DatosLN.dbf'
SIZE 100M
AUTOEXTEND ON
NEXT 10M
MAXSIZE 500M;

-- =========================
-- Creacion de perfiles 
-- =========================
CREATE PROFILE perfil_admin LIMIT
    SESSIONS_PER_USER          2
    IDLE_TIME                  30
    CONNECT_TIME               600
    LOGICAL_READS_PER_SESSION  2000000
    FAILED_LOGIN_ATTEMPTS      3
    PASSWORD_LIFE_TIME         30
    PASSWORD_LOCK_TIME         1/24
    PASSWORD_GRACE_TIME        4;

CREATE PROFILE perfil_operador LIMIT
    SESSIONS_PER_USER         1
    IDLE_TIME                 15        
    CONNECT_TIME              480
    LOGICAL_READS_PER_SESSION 1500000
    FAILED_LOGIN_ATTEMPTS     5
    PASSWORD_LIFE_TIME        30
    PASSWORD_LOCK_TIME        1/24
    PASSWORD_GRACE_TIME       4;

CREATE PROFILE perfil_consulta LIMIT
    SESSIONS_PER_USER         1
    IDLE_TIME                 10       
    CONNECT_TIME              240
    LOGICAL_READS_PER_SESSION 60000
    FAILED_LOGIN_ATTEMPTS     5
    PASSWORD_LIFE_TIME        30
    PASSWORD_LOCK_TIME        1/24
    PASSWORD_GRACE_TIME       4;

-- =========================
--Roles
-- =========================
CREATE ROLE rol_admin;
GRANT CREATE SESSION TO rol_admin;
GRANT CREATE USER TO rol_admin;
GRANT ALTER USER TO rol_admin;
GRANT DROP USER TO rol_admin;
GRANT CREATE TABLE TO rol_admin;
GRANT CREATE VIEW TO rol_admin;
GRANT CREATE SEQUENCE TO rol_admin;
GRANT CREATE TRIGGER TO rol_admin;
GRANT CREATE PROCEDURE TO rol_admin;

CREATE ROLE rol_operador;
GRANT CREATE SESSION TO rol_operador;
GRANT CREATE TABLE TO rol_operador;
GRANT CREATE VIEW TO rol_operador;
GRANT CREATE SEQUENCE TO rol_operador;
GRANT CREATE TRIGGER TO rol_operador;
GRANT SELECT, INSERT, UPDATE, DELETE ON AdminProyecto.NOMBRE_TABLA TO rol_operador;

CREATE ROLE rol_consulta;
    GRANT CREATE SESSION TO rol_consulta;
    GRANT SELECT ON AdminProyecto.PRODUCTOS TO rol_consulta;
    
SELECT ROLE, PASSWORD_REQUIRED
FROM DBA_ROLES;

-- =========================
-- USUARIO PRINCIPAL
-- =========================
CREATE USER AdminProyecto IDENTIFIED BY AdminProyecto2026#
    DEFAULT TABLESPACE Proyecto_Base_de_DatosLN
    TEMPORARY TABLESPACE TEMP
    PROFILE perfil_admin
    ACCOUNT UNLOCK;

GRANT rol_admin TO AdminProyecto;
GRANT CONNECT TO AdminProyecto;
ALTER USER AdminProyecto QUOTA UNLIMITED ON Proyecto_Base_de_DatosLN;

-- =========================
-- USUARIO OPERADOR
-- =========================
CREATE USER Operador IDENTIFIED BY Operador2026#
    DEFAULT TABLESPACE Proyecto_Base_de_DatosLN
    TEMPORARY TABLESPACE TEMP
    PROFILE perfil_operador
    ACCOUNT UNLOCK;

GRANT rol_operador TO Operador;
GRANT CONNECT TO Operador;
ALTER USER Operador QUOTA UNLIMITED ON Proyecto_Base_de_DatosLN;

-- =========================
-- USUARIO CONSULTA
-- =========================
CREATE USER Consulta IDENTIFIED BY Consulta2026#
    DEFAULT TABLESPACE Proyecto_Base_de_DatosLN
    TEMPORARY TABLESPACE TEMP
    PROFILE perfil_consulta
    ACCOUNT UNLOCK;

GRANT rol_consulta TO Consulta;
GRANT CONNECT TO Consulta;

-- =========================
-- Verificacion 
-- =========================
SELECT USERNAME, PROFILE
FROM DBA_USERS
WHERE USERNAME IN ('ADMINPROYECTO','OPERADOR','CONSULTA');


ALTER USER AdminProyecto
DEFAULT TABLESPACE Proyecto_Base_de_DatosLN;

ALTER USER Operador
DEFAULT TABLESPACE Proyecto_Base_de_DatosLN;

ALTER USER Consulta
DEFAULT TABLESPACE Proyecto_Base_de_DatosLN;


-- =========================
-- DROP TABLAS
-- =========================
DROP TABLE DETALLE_VENTA CASCADE CONSTRAINTS;
DROP TABLE PRODUCTO_ATRIBUTOS CASCADE CONSTRAINTS;
DROP TABLE TELEFONOS CASCADE CONSTRAINTS;
DROP TABLE TELEFONOS_PROVEEDOR CASCADE CONSTRAINTS;
DROP TABLE CORREOS CASCADE CONSTRAINTS;
DROP TABLE DIRECCIONES CASCADE CONSTRAINTS;
DROP TABLE USUARIOS CASCADE CONSTRAINTS;
DROP TABLE VENTAS CASCADE CONSTRAINTS;
DROP TABLE PRODUCTOS CASCADE CONSTRAINTS;
DROP TABLE PROVEEDORES CASCADE CONSTRAINTS;
DROP TABLE CLIENTES CASCADE CONSTRAINTS;
DROP TABLE METODOS_PAGO CASCADE CONSTRAINTS;
DROP TABLE MARCAS CASCADE CONSTRAINTS;
DROP TABLE CATEGORIAS CASCADE CONSTRAINTS;
DROP TABLE AUDITORIA_SISTEMA CASCADE CONSTRAINTS;

-- =========================
-- TABLAS 
-- =========================
CREATE TABLE CATEGORIAS (
    ID_CATEGORIA NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NOMBRE_CATEGORIA VARCHAR2(100) NOT NULL,
    TIPO_GENERAL VARCHAR2(50) NOT NULL
);

CREATE TABLE MARCAS (
    ID_MARCA NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NOMBRE_MARCA VARCHAR2(100) NOT NULL UNIQUE
);

CREATE TABLE METODOS_PAGO (
    ID_METODO NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NOMBRE VARCHAR2(50) NOT NULL UNIQUE
);

CREATE TABLE CLIENTES (
    ID_CLIENTE NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NOMBRE VARCHAR2(100) NOT NULL,
    APELLIDO VARCHAR2(100) NOT NULL,
    FECHA_REGISTRO DATE DEFAULT SYSDATE
);

CREATE TABLE PRODUCTOS (
    ID_PRODUCTO NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ID_CATEGORIA NUMBER NOT NULL,
    ID_MARCA NUMBER NOT NULL,
    NOMBRE VARCHAR2(100) NOT NULL,
    DESCRIPCION VARCHAR2(200),
    PRECIO NUMBER(10,2) NOT NULL CHECK (PRECIO > 0),
    STOCK NUMBER DEFAULT 0 NOT NULL CHECK (STOCK >= 0),
    IMAGEN VARCHAR2(1000),
    CONSTRAINT UK_PRODUCTO UNIQUE (NOMBRE, ID_MARCA),
    CONSTRAINT FK_PRODUCTO_CATEGORIA
        FOREIGN KEY (ID_CATEGORIA)
        REFERENCES CATEGORIAS(ID_CATEGORIA),
    CONSTRAINT FK_PRODUCTO_MARCA
        FOREIGN KEY (ID_MARCA)
        REFERENCES MARCAS(ID_MARCA)
);


CREATE TABLE PRODUCTO_ATRIBUTOS (
    ID_ATRIBUTO NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ID_PRODUCTO NUMBER NOT NULL,
    NOMBRE_ATRIBUTO VARCHAR2(100) NOT NULL,
    VALOR VARCHAR2(200) NOT NULL,
    CONSTRAINT FK_ATRIBUTO_PRODUCTO
        FOREIGN KEY (ID_PRODUCTO)
        REFERENCES PRODUCTOS(ID_PRODUCTO)
        ON DELETE CASCADE
);


CREATE TABLE DETALLE_VENTAS (
    ID_DETALLE NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ID_CLIENTE NUMBER NOT NULL,
    ID_METODO NUMBER NOT NULL,
    FECHA_VENTA DATE DEFAULT SYSDATE,

    CONSTRAINT FK_VENTA_CLIENTE
        FOREIGN KEY (ID_CLIENTE)
        REFERENCES CLIENTES(ID_CLIENTE),

    CONSTRAINT FK_VENTA_METODO
        FOREIGN KEY (ID_METODO)
        REFERENCES METODOS_PAGO(ID_METODO)
);

CREATE TABLE VENTAS (
    ID_VENTA NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ID_DETALLE NUMBER NOT NULL,
    ID_PRODUCTO NUMBER NOT NULL,
    CANTIDAD NUMBER NOT NULL CHECK (CANTIDAD > 0),
    PRECIO_UNITARIO NUMBER(10,2) NOT NULL CHECK (PRECIO_UNITARIO > 0),
    CONSTRAINT FK_DETALLE_VENTA
        FOREIGN KEY (ID_DETALLE)
        REFERENCES DETALLE_VENTAS(ID_DETALLE)
        ON DELETE CASCADE,
    CONSTRAINT FK_DETALLE_PRODUCTO
        FOREIGN KEY (ID_PRODUCTO)
        REFERENCES PRODUCTOS(ID_PRODUCTO)
);


CREATE TABLE USUARIOS (
    ID_USUARIO NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    USERNAME VARCHAR2(50) UNIQUE NOT NULL,
    PASSWORD VARCHAR2(200) NOT NULL,
    ROL VARCHAR2(20) CHECK (ROL IN ('ADMIN','VENDEDOR','CLIENTE')) NOT NULL,
    ID_CLIENTE NUMBER,
    CONSTRAINT FK_USUARIO_CLIENTE
        FOREIGN KEY (ID_CLIENTE)
        REFERENCES CLIENTES(ID_CLIENTE)
);

CREATE TABLE PROVEEDORES (
    ID_PROVEEDOR NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NOMBRE VARCHAR2(150) NOT NULL,
    CORREO VARCHAR2(150) UNIQUE CHECK (CORREO LIKE '%@%')
);

CREATE TABLE TELEFONOS (
    ID_TELEFONO NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ID_CLIENTE NUMBER NOT NULL,
    TELEFONO VARCHAR2(8) NOT NULL UNIQUE,
    CONSTRAINT FK_TELEFONOS_CLIENTE
        FOREIGN KEY (ID_CLIENTE)
        REFERENCES CLIENTES(ID_CLIENTE)
        ON DELETE CASCADE
);

CREATE TABLE TELEFONOS_PROVEEDOR (
    ID_TELEFONO NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ID_PROVEEDOR NUMBER NOT NULL,
    TELEFONO VARCHAR2(20) NOT NULL UNIQUE,
    CONSTRAINT FK_TEL_PROVEEDOR
        FOREIGN KEY (ID_PROVEEDOR)
        REFERENCES PROVEEDORES(ID_PROVEEDOR)
        ON DELETE CASCADE
);


CREATE TABLE CORREOS (
    ID_CORREO NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ID_CLIENTE NUMBER NOT NULL,
    CORREO VARCHAR2(150) UNIQUE CHECK (CORREO LIKE '%@%'),
    CONSTRAINT FK_CORREOS_CLIENTE
        FOREIGN KEY (ID_CLIENTE)
        REFERENCES CLIENTES(ID_CLIENTE)
        ON DELETE CASCADE
);

CREATE TABLE DIRECCIONES (
    ID_DIRECCION NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ID_CLIENTE NUMBER NOT NULL,
    DIRECCION VARCHAR2(250) NOT NULL,
    CONSTRAINT FK_DIRECCIONES_CLIENTE
        FOREIGN KEY (ID_CLIENTE)
        REFERENCES CLIENTES(ID_CLIENTE)
        ON DELETE CASCADE     
);

CREATE TABLE CARRITO (
    ID_CARRITO    NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ID_USUARIO    NUMBER NOT NULL,
    ID_PRODUCTO   NUMBER NOT NULL,
    CANTIDAD      NUMBER DEFAULT 1 NOT NULL CHECK (CANTIDAD > 0),
    FECHA_AGREGADO DATE DEFAULT SYSDATE,
    CONSTRAINT FK_CARRITO_USUARIO
        FOREIGN KEY (ID_USUARIO)
        REFERENCES USUARIOS(ID_USUARIO)
        ON DELETE CASCADE,
    CONSTRAINT FK_CARRITO_PRODUCTO
        FOREIGN KEY (ID_PRODUCTO)
        REFERENCES PRODUCTOS(ID_PRODUCTO)
        ON DELETE CASCADE,
    -- Un usuario no puede tener el mismo producto duplicado
    CONSTRAINT UK_CARRITO_USUARIO_PRODUCTO
        UNIQUE (ID_USUARIO, ID_PRODUCTO)
);

CREATE TABLE AUDITORIA_SISTEMA (
    ID_AUDITORIA NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    TABLA_AFECTADA VARCHAR2(50),
    OPERACION VARCHAR2(10),
    ID_REGISTRO NUMBER,
    CAMPO_MODIFICADO VARCHAR2(50),
    VALOR_ANTERIOR VARCHAR2(200),
    VALOR_NUEVO VARCHAR2(200),
    FECHA_CAMBIO DATE DEFAULT SYSDATE,
    USUARIO_DB VARCHAR2(50)
);


SELECT * FROM AUDITORIA_SISTEMA;

-- =========================
-- TRIGGERS
-- =========================

-- =========================
--Baja la cantidad de producto cuando se hace una venta y de agrega en la tabla DETALLE_VENTA
CREATE OR REPLACE TRIGGER TRG_DESCONTAR_STOCK
AFTER INSERT ON DETALLE_VENTA
FOR EACH ROW
BEGIN
    UPDATE PRODUCTOS
    SET STOCK = STOCK - :NEW.CANTIDAD
    WHERE ID_PRODUCTO = :NEW.ID_PRODUCTO;
END;

-- =========================
--Evita que se pueda vender mas producto del que hay en stock
CREATE OR REPLACE TRIGGER TRG_VALIDAR_STOCK
BEFORE INSERT ON DETALLE_VENTA
FOR EACH ROW
DECLARE
    v_stock PRODUCTOS.STOCK%TYPE;
BEGIN
    SELECT STOCK INTO v_stock
    FROM PRODUCTOS
    WHERE ID_PRODUCTO = :NEW.ID_PRODUCTO;

    IF v_stock < :NEW.CANTIDAD THEN
        RAISE_APPLICATION_ERROR(-20001, 'No hay suficiente stock');
    END IF;
END;

-- =========================
-- Crea la cantidad de venta hecha
CREATE OR REPLACE TRIGGER TRG_CALCULAR_TOTAL
AFTER INSERT ON DETALLE_VENTA
FOR EACH ROW
BEGIN
    UPDATE VENTAS
    SET TOTAL =
    (
        SELECT SUM(CANTIDAD * PRECIO_UNITARIO)
        FROM DETALLE_VENTA
        WHERE ID_VENTA = :NEW.ID_VENTA
    )
    WHERE ID_VENTA = :NEW.ID_VENTA;
END;

-- =========================
-- Crea auditoria para las tablas mas importantes 

-- =========================================
-- AUDITORIA TABLA CATEGORIAS
-- =========================================
CREATE OR REPLACE TRIGGER TRG_AUD_CATEGORIAS
AFTER INSERT OR UPDATE OR DELETE ON CATEGORIAS
FOR EACH ROW
BEGIN

    IF INSERTING THEN
        INSERT INTO AUDITORIA_SISTEMA
            (TABLA_AFECTADA, OPERACION, ID_REGISTRO, USUARIO_DB)
        VALUES
            ('CATEGORIAS', 'INSERT', :NEW.ID_CATEGORIA, USER);

    ELSIF DELETING THEN
        INSERT INTO AUDITORIA_SISTEMA
            (TABLA_AFECTADA, OPERACION, ID_REGISTRO, USUARIO_DB)
        VALUES
            ('CATEGORIAS', 'DELETE', :OLD.ID_CATEGORIA, USER);

    ELSIF UPDATING THEN

        IF :OLD.NOMBRE_CATEGORIA <> :NEW.NOMBRE_CATEGORIA THEN
            INSERT INTO AUDITORIA_SISTEMA
                (TABLA_AFECTADA, OPERACION, ID_REGISTRO, CAMPO_MODIFICADO, VALOR_ANTERIOR, VALOR_NUEVO, USUARIO_DB)
            VALUES
                ('CATEGORIAS', 'UPDATE', :NEW.ID_CATEGORIA, 'NOMBRE_CATEGORIA', :OLD.NOMBRE_CATEGORIA, :NEW.NOMBRE_CATEGORIA, USER);
        END IF;

        IF :OLD.TIPO_GENERAL <> :NEW.TIPO_GENERAL THEN
            INSERT INTO AUDITORIA_SISTEMA
                (TABLA_AFECTADA, OPERACION, ID_REGISTRO, CAMPO_MODIFICADO, VALOR_ANTERIOR, VALOR_NUEVO, USUARIO_DB)
            VALUES
                ('CATEGORIAS', 'UPDATE', :NEW.ID_CATEGORIA, 'TIPO_GENERAL', :OLD.TIPO_GENERAL, :NEW.TIPO_GENERAL, USER);
        END IF;

    END IF;

END;
/


-- =========================================
-- AUDITORIA TABLA MARCAS
-- =========================================
CREATE OR REPLACE TRIGGER TRG_AUD_MARCAS
AFTER INSERT OR UPDATE OR DELETE ON MARCAS
FOR EACH ROW
BEGIN

    IF INSERTING THEN
        INSERT INTO AUDITORIA_SISTEMA
            (TABLA_AFECTADA, OPERACION, ID_REGISTRO, USUARIO_DB)
        VALUES
            ('MARCAS', 'INSERT', :NEW.ID_MARCA, USER);

    ELSIF DELETING THEN
        INSERT INTO AUDITORIA_SISTEMA
            (TABLA_AFECTADA, OPERACION, ID_REGISTRO, USUARIO_DB)
        VALUES
            ('MARCAS', 'DELETE', :OLD.ID_MARCA, USER);

    ELSIF UPDATING THEN

        IF :OLD.NOMBRE_MARCA <> :NEW.NOMBRE_MARCA THEN
            INSERT INTO AUDITORIA_SISTEMA
                (TABLA_AFECTADA, OPERACION, ID_REGISTRO, CAMPO_MODIFICADO, VALOR_ANTERIOR, VALOR_NUEVO, USUARIO_DB)
            VALUES
                ('MARCAS', 'UPDATE', :NEW.ID_MARCA, 'NOMBRE_MARCA', :OLD.NOMBRE_MARCA, :NEW.NOMBRE_MARCA, USER);
        END IF;

    END IF;

END;
/


-- =========================================
-- AUDITORIA TABLA METODOS_PAGO
-- =========================================
CREATE OR REPLACE TRIGGER TRG_AUD_METODOS_PAGO
AFTER INSERT OR UPDATE OR DELETE ON METODOS_PAGO
FOR EACH ROW
BEGIN

    IF INSERTING THEN
        INSERT INTO AUDITORIA_SISTEMA
            (TABLA_AFECTADA, OPERACION, ID_REGISTRO, USUARIO_DB)
        VALUES
            ('METODOS_PAGO', 'INSERT', :NEW.ID_METODO, USER);

    ELSIF DELETING THEN
        INSERT INTO AUDITORIA_SISTEMA
            (TABLA_AFECTADA, OPERACION, ID_REGISTRO, USUARIO_DB)
        VALUES
            ('METODOS_PAGO', 'DELETE', :OLD.ID_METODO, USER);

    ELSIF UPDATING THEN

        IF :OLD.NOMBRE <> :NEW.NOMBRE THEN
            INSERT INTO AUDITORIA_SISTEMA
                (TABLA_AFECTADA, OPERACION, ID_REGISTRO, CAMPO_MODIFICADO, VALOR_ANTERIOR, VALOR_NUEVO, USUARIO_DB)
            VALUES
                ('METODOS_PAGO', 'UPDATE', :NEW.ID_METODO, 'NOMBRE', :OLD.NOMBRE, :NEW.NOMBRE, USER);
        END IF;

    END IF;

END;
/


-- =========================================
-- AUDITORIA TABLA PROVEEDORES
-- =========================================
CREATE OR REPLACE TRIGGER TRG_AUD_PROVEEDORES
AFTER INSERT OR UPDATE OR DELETE ON PROVEEDORES
FOR EACH ROW
BEGIN

    IF INSERTING THEN
        INSERT INTO AUDITORIA_SISTEMA
            (TABLA_AFECTADA, OPERACION, ID_REGISTRO, USUARIO_DB)
        VALUES
            ('PROVEEDORES', 'INSERT', :NEW.ID_PROVEEDOR, USER);

    ELSIF DELETING THEN
        INSERT INTO AUDITORIA_SISTEMA
            (TABLA_AFECTADA, OPERACION, ID_REGISTRO, USUARIO_DB)
        VALUES
            ('PROVEEDORES', 'DELETE', :OLD.ID_PROVEEDOR, USER);

    ELSIF UPDATING THEN

        IF :OLD.NOMBRE <> :NEW.NOMBRE THEN
            INSERT INTO AUDITORIA_SISTEMA
                (TABLA_AFECTADA, OPERACION, ID_REGISTRO, CAMPO_MODIFICADO, VALOR_ANTERIOR, VALOR_NUEVO, USUARIO_DB)
            VALUES
                ('PROVEEDORES', 'UPDATE', :NEW.ID_PROVEEDOR, 'NOMBRE', :OLD.NOMBRE, :NEW.NOMBRE, USER);
        END IF;

        IF :OLD.CORREO <> :NEW.CORREO THEN
            INSERT INTO AUDITORIA_SISTEMA
                (TABLA_AFECTADA, OPERACION, ID_REGISTRO, CAMPO_MODIFICADO, VALOR_ANTERIOR, VALOR_NUEVO, USUARIO_DB)
            VALUES
                ('PROVEEDORES', 'UPDATE', :NEW.ID_PROVEEDOR, 'CORREO', :OLD.CORREO, :NEW.CORREO, USER);
        END IF;

    END IF;

END;
/


-- =========================================
-- AUDITORIA TABLA TELEFONOS
-- =========================================
CREATE OR REPLACE TRIGGER TRG_AUD_TELEFONOS
AFTER INSERT OR UPDATE OR DELETE ON TELEFONOS
FOR EACH ROW
BEGIN

    IF INSERTING THEN
        INSERT INTO AUDITORIA_SISTEMA
            (TABLA_AFECTADA, OPERACION, ID_REGISTRO, USUARIO_DB)
        VALUES
            ('TELEFONOS', 'INSERT', :NEW.ID_TELEFONO, USER);

    ELSIF DELETING THEN
        INSERT INTO AUDITORIA_SISTEMA
            (TABLA_AFECTADA, OPERACION, ID_REGISTRO, USUARIO_DB)
        VALUES
            ('TELEFONOS', 'DELETE', :OLD.ID_TELEFONO, USER);

    ELSIF UPDATING THEN

        IF :OLD.TELEFONO <> :NEW.TELEFONO THEN
            INSERT INTO AUDITORIA_SISTEMA
                (TABLA_AFECTADA, OPERACION, ID_REGISTRO, CAMPO_MODIFICADO, VALOR_ANTERIOR, VALOR_NUEVO, USUARIO_DB)
            VALUES
                ('TELEFONOS', 'UPDATE', :NEW.ID_TELEFONO, 'TELEFONO', :OLD.TELEFONO, :NEW.TELEFONO, USER);
        END IF;

        IF :OLD.ID_CLIENTE <> :NEW.ID_CLIENTE THEN
            INSERT INTO AUDITORIA_SISTEMA
                (TABLA_AFECTADA, OPERACION, ID_REGISTRO, CAMPO_MODIFICADO, VALOR_ANTERIOR, VALOR_NUEVO, USUARIO_DB)
            VALUES
                ('TELEFONOS', 'UPDATE', :NEW.ID_TELEFONO, 'ID_CLIENTE', TO_CHAR(:OLD.ID_CLIENTE), TO_CHAR(:NEW.ID_CLIENTE), USER);
        END IF;

    END IF;

END;
/


-- =========================================
-- AUDITORIA TABLA TELEFONOS_PROVEEDOR
-- =========================================
CREATE OR REPLACE TRIGGER TRG_AUD_TELEFONOS_PROVEEDOR
AFTER INSERT OR UPDATE OR DELETE ON TELEFONOS_PROVEEDOR
FOR EACH ROW
BEGIN

    IF INSERTING THEN
        INSERT INTO AUDITORIA_SISTEMA
            (TABLA_AFECTADA, OPERACION, ID_REGISTRO, USUARIO_DB)
        VALUES
            ('TELEFONOS_PROVEEDOR', 'INSERT', :NEW.ID_TELEFONO, USER);

    ELSIF DELETING THEN
        INSERT INTO AUDITORIA_SISTEMA
            (TABLA_AFECTADA, OPERACION, ID_REGISTRO, USUARIO_DB)
        VALUES
            ('TELEFONOS_PROVEEDOR', 'DELETE', :OLD.ID_TELEFONO, USER);

    ELSIF UPDATING THEN

        IF :OLD.TELEFONO <> :NEW.TELEFONO THEN
            INSERT INTO AUDITORIA_SISTEMA
                (TABLA_AFECTADA, OPERACION, ID_REGISTRO, CAMPO_MODIFICADO, VALOR_ANTERIOR, VALOR_NUEVO, USUARIO_DB)
            VALUES
                ('TELEFONOS_PROVEEDOR', 'UPDATE', :NEW.ID_TELEFONO, 'TELEFONO', :OLD.TELEFONO, :NEW.TELEFONO, USER);
        END IF;

        IF :OLD.ID_PROVEEDOR <> :NEW.ID_PROVEEDOR THEN
            INSERT INTO AUDITORIA_SISTEMA
                (TABLA_AFECTADA, OPERACION, ID_REGISTRO, CAMPO_MODIFICADO, VALOR_ANTERIOR, VALOR_NUEVO, USUARIO_DB)
            VALUES
                ('TELEFONOS_PROVEEDOR', 'UPDATE', :NEW.ID_TELEFONO, 'ID_PROVEEDOR', TO_CHAR(:OLD.ID_PROVEEDOR), TO_CHAR(:NEW.ID_PROVEEDOR), USER);
        END IF;

    END IF;

END;
/


-- =========================================
-- AUDITORIA TABLA CORREOS
-- =========================================
CREATE OR REPLACE TRIGGER TRG_AUD_CORREOS
AFTER INSERT OR UPDATE OR DELETE ON CORREOS
FOR EACH ROW
BEGIN

    IF INSERTING THEN
        INSERT INTO AUDITORIA_SISTEMA
            (TABLA_AFECTADA, OPERACION, ID_REGISTRO, USUARIO_DB)
        VALUES
            ('CORREOS', 'INSERT', :NEW.ID_CORREO, USER);

    ELSIF DELETING THEN
        INSERT INTO AUDITORIA_SISTEMA
            (TABLA_AFECTADA, OPERACION, ID_REGISTRO, USUARIO_DB)
        VALUES
            ('CORREOS', 'DELETE', :OLD.ID_CORREO, USER);

    ELSIF UPDATING THEN

        IF :OLD.CORREO <> :NEW.CORREO THEN
            INSERT INTO AUDITORIA_SISTEMA
                (TABLA_AFECTADA, OPERACION, ID_REGISTRO, CAMPO_MODIFICADO, VALOR_ANTERIOR, VALOR_NUEVO, USUARIO_DB)
            VALUES
                ('CORREOS', 'UPDATE', :NEW.ID_CORREO, 'CORREO', :OLD.CORREO, :NEW.CORREO, USER);
        END IF;

        IF :OLD.ID_CLIENTE <> :NEW.ID_CLIENTE THEN
            INSERT INTO AUDITORIA_SISTEMA
                (TABLA_AFECTADA, OPERACION, ID_REGISTRO, CAMPO_MODIFICADO, VALOR_ANTERIOR, VALOR_NUEVO, USUARIO_DB)
            VALUES
                ('CORREOS', 'UPDATE', :NEW.ID_CORREO, 'ID_CLIENTE', TO_CHAR(:OLD.ID_CLIENTE), TO_CHAR(:NEW.ID_CLIENTE), USER);
        END IF;

    END IF;

END;
/


-- =========================================
-- AUDITORIA TABLA DIRECCIONES
-- =========================================
CREATE OR REPLACE TRIGGER TRG_AUD_DIRECCIONES
AFTER INSERT OR UPDATE OR DELETE ON DIRECCIONES
FOR EACH ROW
BEGIN

    IF INSERTING THEN
        INSERT INTO AUDITORIA_SISTEMA
            (TABLA_AFECTADA, OPERACION, ID_REGISTRO, USUARIO_DB)
        VALUES
            ('DIRECCIONES', 'INSERT', :NEW.ID_DIRECCION, USER);

    ELSIF DELETING THEN
        INSERT INTO AUDITORIA_SISTEMA
            (TABLA_AFECTADA, OPERACION, ID_REGISTRO, USUARIO_DB)
        VALUES
            ('DIRECCIONES', 'DELETE', :OLD.ID_DIRECCION, USER);

    ELSIF UPDATING THEN

        IF :OLD.DIRECCION <> :NEW.DIRECCION THEN
            INSERT INTO AUDITORIA_SISTEMA
                (TABLA_AFECTADA, OPERACION, ID_REGISTRO, CAMPO_MODIFICADO, VALOR_ANTERIOR, VALOR_NUEVO, USUARIO_DB)
            VALUES
                ('DIRECCIONES', 'UPDATE', :NEW.ID_DIRECCION, 'DIRECCION', :OLD.DIRECCION, :NEW.DIRECCION, USER);
        END IF;

        IF :OLD.ID_CLIENTE <> :NEW.ID_CLIENTE THEN
            INSERT INTO AUDITORIA_SISTEMA
                (TABLA_AFECTADA, OPERACION, ID_REGISTRO, CAMPO_MODIFICADO, VALOR_ANTERIOR, VALOR_NUEVO, USUARIO_DB)
            VALUES
                ('DIRECCIONES', 'UPDATE', :NEW.ID_DIRECCION, 'ID_CLIENTE', TO_CHAR(:OLD.ID_CLIENTE), TO_CHAR(:NEW.ID_CLIENTE), USER);
        END IF;

    END IF;

END;
/


-- =========================================
-- AUDITORIA TABLA USUARIOS
-- =========================================
CREATE OR REPLACE TRIGGER TRG_AUD_USUARIOS
AFTER INSERT OR UPDATE OR DELETE ON USUARIOS
FOR EACH ROW
BEGIN

    IF INSERTING THEN
        INSERT INTO AUDITORIA_SISTEMA
            (TABLA_AFECTADA, OPERACION, ID_REGISTRO, USUARIO_DB)
        VALUES
            ('USUARIOS', 'INSERT', :NEW.ID_USUARIO, USER);

    ELSIF DELETING THEN
        INSERT INTO AUDITORIA_SISTEMA
            (TABLA_AFECTADA, OPERACION, ID_REGISTRO, USUARIO_DB)
        VALUES
            ('USUARIOS', 'DELETE', :OLD.ID_USUARIO, USER);

    ELSIF UPDATING THEN

        IF :OLD.USERNAME <> :NEW.USERNAME THEN
            INSERT INTO AUDITORIA_SISTEMA
                (TABLA_AFECTADA, OPERACION, ID_REGISTRO, CAMPO_MODIFICADO, VALOR_ANTERIOR, VALOR_NUEVO, USUARIO_DB)
            VALUES
                ('USUARIOS', 'UPDATE', :NEW.ID_USUARIO, 'USERNAME', :OLD.USERNAME, :NEW.USERNAME, USER);
        END IF;

        -- Se audita el cambio de password pero sin guardar el valor real por seguridad
        IF :OLD.PASSWORD <> :NEW.PASSWORD THEN
            INSERT INTO AUDITORIA_SISTEMA
                (TABLA_AFECTADA, OPERACION, ID_REGISTRO, CAMPO_MODIFICADO, VALOR_ANTERIOR, VALOR_NUEVO, USUARIO_DB)
            VALUES
                ('USUARIOS', 'UPDATE', :NEW.ID_USUARIO, 'PASSWORD', '********', '********', USER);
        END IF;

        IF :OLD.ROL <> :NEW.ROL THEN
            INSERT INTO AUDITORIA_SISTEMA
                (TABLA_AFECTADA, OPERACION, ID_REGISTRO, CAMPO_MODIFICADO, VALOR_ANTERIOR, VALOR_NUEVO, USUARIO_DB)
            VALUES
                ('USUARIOS', 'UPDATE', :NEW.ID_USUARIO, 'ROL', :OLD.ROL, :NEW.ROL, USER);
        END IF;

    END IF;

END;
/


-- =========================================
-- AUDITORIA TABLA PRODUCTO_ATRIBUTOS
-- =========================================
CREATE OR REPLACE TRIGGER TRG_AUD_PRODUCTO_ATRIBUTOS
AFTER INSERT OR UPDATE OR DELETE ON PRODUCTO_ATRIBUTOS
FOR EACH ROW
BEGIN

    IF INSERTING THEN
        INSERT INTO AUDITORIA_SISTEMA
            (TABLA_AFECTADA, OPERACION, ID_REGISTRO, USUARIO_DB)
        VALUES
            ('PRODUCTO_ATRIBUTOS', 'INSERT', :NEW.ID_ATRIBUTO, USER);

    ELSIF DELETING THEN
        INSERT INTO AUDITORIA_SISTEMA
            (TABLA_AFECTADA, OPERACION, ID_REGISTRO, USUARIO_DB)
        VALUES
            ('PRODUCTO_ATRIBUTOS', 'DELETE', :OLD.ID_ATRIBUTO, USER);

    ELSIF UPDATING THEN

        IF :OLD.NOMBRE_ATRIBUTO <> :NEW.NOMBRE_ATRIBUTO THEN
            INSERT INTO AUDITORIA_SISTEMA
                (TABLA_AFECTADA, OPERACION, ID_REGISTRO, CAMPO_MODIFICADO, VALOR_ANTERIOR, VALOR_NUEVO, USUARIO_DB)
            VALUES
                ('PRODUCTO_ATRIBUTOS', 'UPDATE', :NEW.ID_ATRIBUTO, 'NOMBRE_ATRIBUTO', :OLD.NOMBRE_ATRIBUTO, :NEW.NOMBRE_ATRIBUTO, USER);
        END IF;

        IF :OLD.VALOR <> :NEW.VALOR THEN
            INSERT INTO AUDITORIA_SISTEMA
                (TABLA_AFECTADA, OPERACION, ID_REGISTRO, CAMPO_MODIFICADO, VALOR_ANTERIOR, VALOR_NUEVO, USUARIO_DB)
            VALUES
                ('PRODUCTO_ATRIBUTOS', 'UPDATE', :NEW.ID_ATRIBUTO, 'VALOR', :OLD.VALOR, :NEW.VALOR, USER);
        END IF;

    END IF;

END;
/


-- =========================================
-- AUDITORIA TABLA CARRITO
-- =========================================
CREATE OR REPLACE TRIGGER TRG_AUD_CARRITO
AFTER INSERT OR UPDATE OR DELETE ON CARRITO
FOR EACH ROW
BEGIN

    IF INSERTING THEN
        INSERT INTO AUDITORIA_SISTEMA
            (TABLA_AFECTADA, OPERACION, ID_REGISTRO, USUARIO_DB)
        VALUES
            ('CARRITO', 'INSERT', :NEW.ID_CARRITO, USER);

    ELSIF DELETING THEN
        INSERT INTO AUDITORIA_SISTEMA
            (TABLA_AFECTADA, OPERACION, ID_REGISTRO, USUARIO_DB)
        VALUES
            ('CARRITO', 'DELETE', :OLD.ID_CARRITO, USER);

    ELSIF UPDATING THEN

        IF :OLD.CANTIDAD <> :NEW.CANTIDAD THEN
            INSERT INTO AUDITORIA_SISTEMA
                (TABLA_AFECTADA, OPERACION, ID_REGISTRO, CAMPO_MODIFICADO, VALOR_ANTERIOR, VALOR_NUEVO, USUARIO_DB)
            VALUES
                ('CARRITO', 'UPDATE', :NEW.ID_CARRITO, 'CANTIDAD', TO_CHAR(:OLD.CANTIDAD), TO_CHAR(:NEW.CANTIDAD), USER);
        END IF;

        IF :OLD.ID_PRODUCTO <> :NEW.ID_PRODUCTO THEN
            INSERT INTO AUDITORIA_SISTEMA
                (TABLA_AFECTADA, OPERACION, ID_REGISTRO, CAMPO_MODIFICADO, VALOR_ANTERIOR, VALOR_NUEVO, USUARIO_DB)
            VALUES
                ('CARRITO', 'UPDATE', :NEW.ID_CARRITO, 'ID_PRODUCTO', TO_CHAR(:OLD.ID_PRODUCTO), TO_CHAR(:NEW.ID_PRODUCTO), USER);
        END IF;

    END IF;

END;
/
-- =========================================
-- AUDITORIA TABLA PRODUCTOS
-- =========================================
CREATE OR REPLACE TRIGGER TRG_AUD_PRODUCTOS
AFTER INSERT OR UPDATE OR DELETE ON PRODUCTOS
FOR EACH ROW
BEGIN

    IF INSERTING THEN
        INSERT INTO AUDITORIA_SISTEMA
            (TABLA_AFECTADA, OPERACION, ID_REGISTRO, USUARIO_DB)
        VALUES
            ('PRODUCTOS', 'INSERT', :NEW.ID_PRODUCTO, USER);

    ELSIF DELETING THEN
        INSERT INTO AUDITORIA_SISTEMA
            (TABLA_AFECTADA, OPERACION, ID_REGISTRO, USUARIO_DB)
        VALUES
            ('PRODUCTOS', 'DELETE', :OLD.ID_PRODUCTO, USER);

    ELSIF UPDATING THEN

        IF :OLD.PRECIO <> :NEW.PRECIO THEN
            INSERT INTO AUDITORIA_SISTEMA
                (TABLA_AFECTADA, OPERACION, ID_REGISTRO, CAMPO_MODIFICADO, VALOR_ANTERIOR, VALOR_NUEVO, USUARIO_DB)
            VALUES
                ('PRODUCTOS', 'UPDATE', :NEW.ID_PRODUCTO, 'PRECIO', TO_CHAR(:OLD.PRECIO), TO_CHAR(:NEW.PRECIO), USER);
        END IF;

        IF :OLD.STOCK <> :NEW.STOCK THEN
            INSERT INTO AUDITORIA_SISTEMA
                (TABLA_AFECTADA, OPERACION, ID_REGISTRO, CAMPO_MODIFICADO, VALOR_ANTERIOR, VALOR_NUEVO, USUARIO_DB)
            VALUES
                ('PRODUCTOS', 'UPDATE', :NEW.ID_PRODUCTO, 'STOCK', TO_CHAR(:OLD.STOCK), TO_CHAR(:NEW.STOCK), USER);
        END IF;

        IF :OLD.NOMBRE <> :NEW.NOMBRE THEN
            INSERT INTO AUDITORIA_SISTEMA
                (TABLA_AFECTADA, OPERACION, ID_REGISTRO, CAMPO_MODIFICADO, VALOR_ANTERIOR, VALOR_NUEVO, USUARIO_DB)
            VALUES
                ('PRODUCTOS', 'UPDATE', :NEW.ID_PRODUCTO, 'NOMBRE', :OLD.NOMBRE, :NEW.NOMBRE, USER);
        END IF;

    END IF;

END;
/

-- =========================================
-- AUDITORIA TABLA DETALLE_VENTAS
-- =========================================
CREATE OR REPLACE TRIGGER TRG_AUD_DETALLE_VENTAS
AFTER INSERT OR UPDATE OR DELETE ON DETALLE_VENTAS
FOR EACH ROW
BEGIN

    IF INSERTING THEN
        INSERT INTO AUDITORIA_SISTEMA
            (TABLA_AFECTADA, OPERACION, ID_REGISTRO, USUARIO_DB)
        VALUES
            ('DETALLE_VENTAS', 'INSERT', :NEW.ID_DETALLE, USER);

    ELSIF DELETING THEN
        INSERT INTO AUDITORIA_SISTEMA
            (TABLA_AFECTADA, OPERACION, ID_REGISTRO, USUARIO_DB)
        VALUES
            ('DETALLE_VENTAS', 'DELETE', :OLD.ID_DETALLE, USER);

    ELSIF UPDATING THEN

        IF :OLD.ID_CLIENTE <> :NEW.ID_CLIENTE THEN
            INSERT INTO AUDITORIA_SISTEMA
                (TABLA_AFECTADA, OPERACION, ID_REGISTRO, CAMPO_MODIFICADO, VALOR_ANTERIOR, VALOR_NUEVO, USUARIO_DB)
            VALUES
                ('DETALLE_VENTAS', 'UPDATE', :NEW.ID_DETALLE, 'ID_CLIENTE', TO_CHAR(:OLD.ID_CLIENTE), TO_CHAR(:NEW.ID_CLIENTE), USER);
        END IF;

        IF :OLD.ID_METODO <> :NEW.ID_METODO THEN
            INSERT INTO AUDITORIA_SISTEMA
                (TABLA_AFECTADA, OPERACION, ID_REGISTRO, CAMPO_MODIFICADO, VALOR_ANTERIOR, VALOR_NUEVO, USUARIO_DB)
            VALUES
                ('DETALLE_VENTAS', 'UPDATE', :NEW.ID_DETALLE, 'ID_METODO', TO_CHAR(:OLD.ID_METODO), TO_CHAR(:NEW.ID_METODO), USER);
        END IF;

        IF :OLD.FECHA_VENTA <> :NEW.FECHA_VENTA THEN
            INSERT INTO AUDITORIA_SISTEMA
                (TABLA_AFECTADA, OPERACION, ID_REGISTRO, CAMPO_MODIFICADO, VALOR_ANTERIOR, VALOR_NUEVO, USUARIO_DB)
            VALUES
                ('DETALLE_VENTAS', 'UPDATE', :NEW.ID_DETALLE, 'FECHA_VENTA', TO_CHAR(:OLD.FECHA_VENTA, 'DD/MM/YYYY'), TO_CHAR(:NEW.FECHA_VENTA, 'DD/MM/YYYY'), USER);
        END IF;

    END IF;

END;
/

-- =========================================
-- AUDITORIA TABLA VENTAS
-- =========================================
CREATE OR REPLACE TRIGGER TRG_AUD_VENTAS
AFTER INSERT OR UPDATE OR DELETE ON VENTAS
FOR EACH ROW
BEGIN

    IF INSERTING THEN
        INSERT INTO AUDITORIA_SISTEMA
            (TABLA_AFECTADA, OPERACION, ID_REGISTRO, USUARIO_DB)
        VALUES
            ('VENTAS', 'INSERT', :NEW.ID_VENTA, USER);

    ELSIF DELETING THEN
        INSERT INTO AUDITORIA_SISTEMA
            (TABLA_AFECTADA, OPERACION, ID_REGISTRO, USUARIO_DB)
        VALUES
            ('VENTAS', 'DELETE', :OLD.ID_VENTA, USER);

    ELSIF UPDATING THEN

        IF :OLD.CANTIDAD <> :NEW.CANTIDAD THEN
            INSERT INTO AUDITORIA_SISTEMA
                (TABLA_AFECTADA, OPERACION, ID_REGISTRO, CAMPO_MODIFICADO, VALOR_ANTERIOR, VALOR_NUEVO, USUARIO_DB)
            VALUES
                ('VENTAS', 'UPDATE', :NEW.ID_VENTA, 'CANTIDAD', TO_CHAR(:OLD.CANTIDAD), TO_CHAR(:NEW.CANTIDAD), USER);
        END IF;

        IF :OLD.PRECIO_UNITARIO <> :NEW.PRECIO_UNITARIO THEN
            INSERT INTO AUDITORIA_SISTEMA
                (TABLA_AFECTADA, OPERACION, ID_REGISTRO, CAMPO_MODIFICADO, VALOR_ANTERIOR, VALOR_NUEVO, USUARIO_DB)
            VALUES
                ('VENTAS', 'UPDATE', :NEW.ID_VENTA, 'PRECIO_UNITARIO', TO_CHAR(:OLD.PRECIO_UNITARIO), TO_CHAR(:NEW.PRECIO_UNITARIO), USER);
        END IF;

    END IF;

END;
/


-- =========================================
-- AUDITORIA TABLA CLIENTES
-- =========================================
CREATE OR REPLACE TRIGGER TRG_AUD_CLIENTES
AFTER INSERT OR UPDATE OR DELETE ON CLIENTES
FOR EACH ROW
BEGIN

    IF INSERTING THEN
        INSERT INTO AUDITORIA_SISTEMA
            (TABLA_AFECTADA, OPERACION, ID_REGISTRO, USUARIO_DB)
        VALUES
            ('CLIENTES', 'INSERT', :NEW.ID_CLIENTE, USER);

    ELSIF DELETING THEN
        INSERT INTO AUDITORIA_SISTEMA
            (TABLA_AFECTADA, OPERACION, ID_REGISTRO, USUARIO_DB)
        VALUES
            ('CLIENTES', 'DELETE', :OLD.ID_CLIENTE, USER);

    ELSIF UPDATING THEN

        IF :OLD.NOMBRE <> :NEW.NOMBRE THEN
            INSERT INTO AUDITORIA_SISTEMA
                (TABLA_AFECTADA, OPERACION, ID_REGISTRO, CAMPO_MODIFICADO, VALOR_ANTERIOR, VALOR_NUEVO, USUARIO_DB)
            VALUES
                ('CLIENTES', 'UPDATE', :NEW.ID_CLIENTE, 'NOMBRE', :OLD.NOMBRE, :NEW.NOMBRE, USER);
        END IF;

        IF :OLD.APELLIDO <> :NEW.APELLIDO THEN
            INSERT INTO AUDITORIA_SISTEMA
                (TABLA_AFECTADA, OPERACION, ID_REGISTRO, CAMPO_MODIFICADO, VALOR_ANTERIOR, VALOR_NUEVO, USUARIO_DB)
            VALUES
                ('CLIENTES', 'UPDATE', :NEW.ID_CLIENTE, 'APELLIDO', :OLD.APELLIDO, :NEW.APELLIDO, USER);
        END IF;

    END IF;

END;
/


SELECT * FROM AUDITORIA_SISTEMA;

-- =========================
-- FUNCIONES
-- =========================

-- =========================
--Crea un total de ventas 
CREATE OR REPLACE FUNCTION TOTAL_VENTA
(
    P_ID_VENTA NUMBER
)
RETURN NUMBER
IS
    V_TOTAL NUMBER;
BEGIN

SELECT SUM(CANTIDAD * PRECIO_UNITARIO)
INTO V_TOTAL
FROM DETALLE_VENTA
WHERE ID_VENTA = P_ID_VENTA;

RETURN V_TOTAL;

END;

SELECT TOTAL_VENTA(1) FROM DUAL;
-- =========================
--Para saber la cantidad de inventario que hay 
CREATE OR REPLACE FUNCTION VALOR_INVENTARIO
RETURN NUMBER
IS
    V_TOTAL NUMBER;
BEGIN

SELECT SUM(PRECIO * STOCK)
INTO V_TOTAL
FROM PRODUCTOS;

RETURN V_TOTAL;

END;

SELECT VALOR_INVENTARIO FROM DUAL;
-- =========================
--Para saber cuantos productos tiene una categoria 
CREATE OR REPLACE FUNCTION PRODUCTOS_POR_CATEGORIA
(
    P_ID_CATEGORIA NUMBER
)
RETURN NUMBER
IS
    V_TOTAL NUMBER;
BEGIN

SELECT COUNT(*)
INTO V_TOTAL
FROM PRODUCTOS
WHERE ID_CATEGORIA = P_ID_CATEGORIA;

RETURN V_TOTAL;

END;

SELECT 
NOMBRE_CATEGORIA,
PRODUCTOS_POR_CATEGORIA(ID_CATEGORIA)
FROM CATEGORIAS;

-- =========================
--Para saber cuanto a gastado un cliente en la tienda 
CREATE OR REPLACE FUNCTION TOTAL_COMPRADO_CLIENTE
(
    P_ID_CLIENTE NUMBER
)
RETURN NUMBER
IS
    V_TOTAL NUMBER;
BEGIN

SELECT SUM(TOTAL)
INTO V_TOTAL
FROM VENTAS
WHERE ID_CLIENTE = P_ID_CLIENTE;

RETURN NVL(V_TOTAL,0);

END;

SELECT 
NOMBRE,
APELLIDO,
TOTAL_COMPRADO_CLIENTE(ID_CLIENTE)
FROM CLIENTES;

-- =========================
-- CURSORES
-- =========================



-- =========================
-- PROCEDIMIENTOS
-- =========================



-- =========================
-- PAQUETES
-- =========================


-- =========================
-- EXCEPCIONES
-- =========================



-- =========================
-- EXPRECIONES REGULARES
-- =========================

SET SERVEROUTPUT ON;

-- =======================================================
-- 1.1  Validar que el correo tenga formato nombre@dominio.ext
--      ?til al registrar o actualizar CORREOS de clientes
-- =======================================================
SELECT c.ID_CLIENTE, c.CORREO
FROM   AdminProyecto.CORREOS c
WHERE  REGEXP_LIKE(c.CORREO,
           '^[A-Za-z0-9._%+\-]+@[A-Za-z0-9.\-]+\.[A-Za-z]{2,}$');

-- =======================================================
-- 1.2  Correos INV?LIDOS (para auditoria / limpieza)
-- =======================================================
SELECT c.ID_CLIENTE, c.CORREO
FROM   AdminProyecto.CORREOS c
WHERE  NOT REGEXP_LIKE(c.CORREO,
           '^[A-Za-z0-9._%+\-]+@[A-Za-z0-9.\-]+\.[A-Za-z]{2,}$');

-- =======================================================
-- 1.3  Validar tel?fonos: exactamente 8 d?gitos (Costa Rica)
--      ?til en TELEFONOS de clientes
-- =======================================================
SELECT t.ID_CLIENTE, t.TELEFONO
FROM   AdminProyecto.TELEFONOS t
WHERE  REGEXP_LIKE(t.TELEFONO, '^[0-9]{8}$');

-- =======================================================
-- 1.4  Tel?fonos que NO cumplen el formato (para revisar)
-- =======================================================
SELECT t.ID_CLIENTE, t.TELEFONO
FROM   AdminProyecto.TELEFONOS t
WHERE  NOT REGEXP_LIKE(t.TELEFONO, '^[0-9]{8}$');

-- =======================================================
-- 1.5  Buscar productos cuyo nombre contenga un n?mero
--      (ej: RTX 4060, 980 Pro, 16GB ?)
--      ?til para filtrar componentes con specs en el nombre
-- =======================================================
SELECT ID_PRODUCTO, NOMBRE, PRECIO
FROM   AdminProyecto.PRODUCTOS
WHERE  REGEXP_LIKE(NOMBRE, '[0-9]')
ORDER  BY NOMBRE;

-- =======================================================
-- 1.6  Productos cuya descripci?n mencione "DDR4" o "DDR5"
--      (case-insensitive) ? Memoria RAM
-- =======================================================
SELECT ID_PRODUCTO, NOMBRE, DESCRIPCION
FROM   AdminProyecto.PRODUCTOS
WHERE  REGEXP_LIKE(DESCRIPCION, 'DDR[45]', 'i');

-- =======================================================
-- 1.7  Extraer la capacidad (n?mero + GB/TB) del nombre
--      del producto ? ?til para ordenar almacenamiento
-- =======================================================
SELECT NOMBRE,
       REGEXP_SUBSTR(NOMBRE, '[0-9]+\s*(GB|TB)', 1, 1, 'i') AS CAPACIDAD
FROM   AdminProyecto.PRODUCTOS
WHERE  REGEXP_LIKE(NOMBRE, '[0-9]+\s*(GB|TB)', 'i')
ORDER  BY NOMBRE;

-- =======================================================
-- 1.8  Limpiar espacios dobles en DESCRIPCION de productos
--      (REGEXP_REPLACE) ? normalizaci?n de texto
-- =======================================================
SELECT ID_PRODUCTO,
       NOMBRE,
       REGEXP_REPLACE(DESCRIPCION, ' {2,}', ' ') AS DESCRIPCION_LIMPIA
FROM   AdminProyecto.PRODUCTOS;

-- =======================================================
-- 1.9  Validar USERNAME: solo letras, n?meros y gui?n bajo,
--      m?nimo 4 caracteres
-- =======================================================
SELECT ID_USUARIO, USERNAME, ROL
FROM   AdminProyecto.USUARIOS
WHERE  REGEXP_LIKE(USERNAME, '^[A-Za-z0-9_]{4,}$');

-- =======================================================
-- 1.10 Proveedores cuyo correo sea de dominio .com o .cr
-- =======================================================
SELECT ID_PROVEEDOR, NOMBRE, CORREO
FROM   AdminProyecto.PROVEEDORES
WHERE  REGEXP_LIKE(CORREO, '\.(com|cr)$', 'i');

-- =======================================================
-- 1.11 Posici?n donde aparece el primer n?mero en el nombre
--      del producto (REGEXP_INSTR)
-- =======================================================
SELECT NOMBRE,
       REGEXP_INSTR(NOMBRE, '[0-9]') AS POS_PRIMER_NUMERO
FROM   AdminProyecto.PRODUCTOS
WHERE  REGEXP_INSTR(NOMBRE, '[0-9]') > 0
ORDER  BY NOMBRE;


-- =========================
-- SQL DINAMICO
-- =========================

CREATE OR REPLACE PROCEDURE BuscarProductos(
    p_categoria  IN NUMBER   DEFAULT NULL,
    p_marca      IN NUMBER   DEFAULT NULL,
    p_precio_max IN NUMBER   DEFAULT NULL,
    p_texto      IN VARCHAR2 DEFAULT NULL
) AS
    v_sql    VARCHAR2(2000);
    v_cursor SYS_REFCURSOR;
    v_id     NUMBER;
    v_nombre VARCHAR2(100);
    v_precio NUMBER;
    v_marca  VARCHAR2(100);
BEGIN
    v_sql := 'SELECT p.ID_PRODUCTO, p.NOMBRE, p.PRECIO, m.NOMBRE_MARCA
              FROM AdminProyecto.PRODUCTOS p
              JOIN AdminProyecto.MARCAS m ON m.ID_MARCA = p.ID_MARCA
              WHERE 1=1';

    IF p_categoria IS NOT NULL THEN
        v_sql := v_sql || ' AND p.ID_CATEGORIA = ' || p_categoria;
    END IF;

    IF p_marca IS NOT NULL THEN
        v_sql := v_sql || ' AND p.ID_MARCA = ' || p_marca;
    END IF;

    IF p_precio_max IS NOT NULL THEN
        v_sql := v_sql || ' AND p.PRECIO <= ' || p_precio_max;
    END IF;

    IF p_texto IS NOT NULL THEN
        v_sql := v_sql || ' AND (UPPER(p.NOMBRE) LIKE UPPER(''%' || p_texto || '%'')'
                        || ' OR UPPER(p.DESCRIPCION) LIKE UPPER(''%' || p_texto || '%''))';
    END IF;

    v_sql := v_sql || ' ORDER BY p.NOMBRE';

    OPEN v_cursor FOR v_sql;
    LOOP
        FETCH v_cursor INTO v_id, v_nombre, v_precio, v_marca;
        EXIT WHEN v_cursor%NOTFOUND;
        DBMS_OUTPUT.PUT_LINE(v_id || ' | ' || v_nombre || ' | $' || v_precio || ' | ' || v_marca);
    END LOOP;
    CLOSE v_cursor;
END BuscarProductos;
/

EXEC BuscarProductos(p_categoria => 9, p_precio_max => 500);
-- Ejemplo de uso:
EXEC AdminProyecto.BuscarProductos(p_texto => 'RTX');

-- =======================================================
-- 2.2  Contar productos por cualquier columna din?mica
--      ?til para reportes de administraci?n
-- =======================================================
CREATE OR REPLACE PROCEDURE AdminProyecto.ContarPorColumna(
    p_columna IN VARCHAR2   -- 'ID_CATEGORIA' | 'ID_MARCA' | 'STOCK'
) AS
    v_sql    VARCHAR2(500);
    v_cursor SYS_REFCURSOR;
    v_grupo  VARCHAR2(100);
    v_total  NUMBER;
BEGIN
    -- Solo se permite un conjunto seguro de columnas
    IF p_columna NOT IN ('ID_CATEGORIA','ID_MARCA','STOCK') THEN
        RAISE_APPLICATION_ERROR(-20001, 'Columna no permitida: ' || p_columna);
    END IF;

    v_sql := 'SELECT TO_CHAR(' || p_columna || '), COUNT(*)
              FROM AdminProyecto.PRODUCTOS
              GROUP BY ' || p_columna || '
              ORDER BY COUNT(*) DESC';

    OPEN v_cursor FOR v_sql;
    LOOP
        FETCH v_cursor INTO v_grupo, v_total;
        EXIT WHEN v_cursor%NOTFOUND;
        DBMS_OUTPUT.PUT_LINE(p_columna || ': ' || v_grupo || ' => ' || v_total || ' productos');
    END LOOP;
    CLOSE v_cursor;
END ContarPorColumna;
/

-- Ejemplo:
EXEC AdminProyecto.ContarPorColumna('ID_CATEGORIA');
EXEC AdminProyecto.ContarPorColumna('ID_MARCA');

-- =======================================================
-- 2.3  Actualizar precio de productos de una categor?a
--      con un porcentaje din?mico (descuento o aumento)
--      ?til para campa?as de ofertas desde el admin
-- =======================================================
CREATE OR REPLACE PROCEDURE AdminProyecto.AjustarPrecioCategoria(
    p_id_categoria IN NUMBER,
    p_porcentaje   IN NUMBER   -- negativo = descuento, positivo = aumento
) AS
    v_sql VARCHAR2(300);
BEGIN
    v_sql := 'UPDATE AdminProyecto.PRODUCTOS
              SET PRECIO = ROUND(PRECIO * (1 + (' || p_porcentaje || ' / 100)), 2)
              WHERE ID_CATEGORIA = ' || p_id_categoria;

    EXECUTE IMMEDIATE v_sql;

    DBMS_OUTPUT.PUT_LINE('Filas actualizadas: ' || SQL%ROWCOUNT);
    COMMIT;
END AjustarPrecioCategoria;
/

-- Ejemplo: bajar 10% todas las Gr?ficas (ID_CATEGORIA = 9)
EXEC AdminProyecto.AjustarPrecioCategoria(9, -10);

-- =======================================================
-- 2.4  Buscar atributos de producto por nombre din?mico
--      Ej: todas las GPUs con atributo "VRAM"
-- =======================================================
CREATE OR REPLACE PROCEDURE AdminProyecto.BuscarPorAtributo(
    p_nombre_atributo IN VARCHAR2,
    p_valor_minimo    IN VARCHAR2 DEFAULT NULL
) AS
    v_sql    VARCHAR2(1000);
    v_cursor SYS_REFCURSOR;
    v_prod   VARCHAR2(100);
    v_attr   VARCHAR2(100);
    v_valor  VARCHAR2(200);
BEGIN
    v_sql := 'SELECT p.NOMBRE, pa.NOMBRE_ATRIBUTO, pa.VALOR
              FROM AdminProyecto.PRODUCTO_ATRIBUTOS pa
              JOIN AdminProyecto.PRODUCTOS p ON p.ID_PRODUCTO = pa.ID_PRODUCTO
              WHERE UPPER(pa.NOMBRE_ATRIBUTO) = UPPER(''' || p_nombre_atributo || ''')';

    IF p_valor_minimo IS NOT NULL THEN
        v_sql := v_sql || ' AND pa.VALOR >= ''' || p_valor_minimo || '''';
    END IF;

    v_sql := v_sql || ' ORDER BY p.NOMBRE';

    OPEN v_cursor FOR v_sql;
    LOOP
        FETCH v_cursor INTO v_prod, v_attr, v_valor;
        EXIT WHEN v_cursor%NOTFOUND;
        DBMS_OUTPUT.PUT_LINE(v_prod || ' | ' || v_attr || ': ' || v_valor);
    END LOOP;
    CLOSE v_cursor;
END BuscarPorAtributo;
/

-- Ejemplo:
EXEC AdminProyecto.BuscarPorAtributo('VRAM');
EXEC AdminProyecto.BuscarPorAtributo('Frecuencia', '3200MHz');


-- =========================
-- PERMISOS
-- =========================
GRANT SELECT ON AdminProyecto.PRODUCTOS TO Consulta;

GRANT SELECT ON AdminProyecto.MARCAS TO Consulta;

GRANT SELECT ON AdminProyecto.CATEGORIAS TO Consulta;

GRANT SELECT ON AdminProyecto.DETALLE_VENTA TO Consulta;

GRANT SELECT ON AdminProyecto.PRODUCTO_ATRIBUTOS TO Consulta;

GRANT SELECT ON AdminProyecto.USUARIOS TO Consulta;

GRANT SELECT ON AdminProyecto.USUARIOS TO Operador;

GRANT SELECT ON AdminProyecto.CLIENTES TO Operador;

GRANT SELECT, INSERT, UPDATE, DELETE ON AdminProyecto.CARRITO TO Operador;

GRANT SELECT ON AdminProyecto.PRODUCTOS TO Operador;

GRANT SELECT ON AdminProyecto.MARCAS TO Operador;

GRANT SELECT, INSERT ON AdminProyecto.DETALLE_VENTAS TO Operador;

GRANT SELECT, INSERT ON AdminProyecto.VENTAS TO Operador;

GRANT SELECT ON AdminProyecto.METODOS_PAGO TO Operador;

GRANT SELECT, INSERT ON AdminProyecto.CLIENTES TO Operador;

GRANT SELECT, INSERT ON AdminProyecto.USUARIOS TO Operador;

GRANT SELECT, INSERT ON AdminProyecto.CORREOS TO Operador;

GRANT INSERT ON AdminProyecto.DIRECCIONES TO Operador;

GRANT SELECT ON AdminProyecto.CATEGORIAS TO Operador;

GRANT SELECT ON AdminProyecto.PRODUCTO_ATRIBUTOS TO Operador;

-- =========================
-- CATEGORIAS
-- =========================
SET DEFINE OFF;
INSERT INTO CATEGORIAS (NOMBRE_CATEGORIA, TIPO_GENERAL) VALUES ('Teclados', 'Perifericos');

INSERT INTO CATEGORIAS (NOMBRE_CATEGORIA, TIPO_GENERAL) VALUES ('Mouses', 'Perifericos');

INSERT INTO CATEGORIAS (NOMBRE_CATEGORIA, TIPO_GENERAL) VALUES ('Microfonos', 'Perifericos');

INSERT INTO CATEGORIAS (NOMBRE_CATEGORIA, TIPO_GENERAL) VALUES ('Headsets', 'Perifericos');

INSERT INTO CATEGORIAS (NOMBRE_CATEGORIA, TIPO_GENERAL) VALUES ('Controles', 'Perifericos');

INSERT INTO CATEGORIAS (NOMBRE_CATEGORIA, TIPO_GENERAL) VALUES ('Mouse Pads', 'Perifericos');

INSERT INTO CATEGORIAS (NOMBRE_CATEGORIA, TIPO_GENERAL) VALUES ('Memoria RAM', 'Componentes');

INSERT INTO CATEGORIAS (NOMBRE_CATEGORIA, TIPO_GENERAL) VALUES ('Almacenamiento', 'Componentes');

INSERT INTO CATEGORIAS (NOMBRE_CATEGORIA, TIPO_GENERAL) VALUES ('Graficas', 'Componentes');

INSERT INTO CATEGORIAS (NOMBRE_CATEGORIA, TIPO_GENERAL) VALUES ('Refrigeraciones', 'Componentes');

INSERT INTO CATEGORIAS (NOMBRE_CATEGORIA, TIPO_GENERAL) VALUES ('Ventilacion', 'Componentes');

INSERT INTO CATEGORIAS (NOMBRE_CATEGORIA, TIPO_GENERAL) VALUES ('Televisores', 'Para el Hogar');

INSERT INTO CATEGORIAS (NOMBRE_CATEGORIA, TIPO_GENERAL) VALUES ('Routers', 'Para el Hogar');

COMMIT;
SELECT * FROM CATEGORIAS;


-- =========================
-- MARCAS
-- =========================
INSERT INTO MARCAS (NOMBRE_MARCA) VALUES ('Razer');

INSERT INTO MARCAS (NOMBRE_MARCA) VALUES ('Samsung');

INSERT INTO MARCAS (NOMBRE_MARCA) VALUES ('Logitech');

INSERT INTO MARCAS (NOMBRE_MARCA) VALUES ('Kingston');

INSERT INTO MARCAS (NOMBRE_MARCA) VALUES ('HyperX');

INSERT INTO MARCAS (NOMBRE_MARCA) VALUES ('HP');

INSERT INTO MARCAS (NOMBRE_MARCA) VALUES ('Huawei');

INSERT INTO MARCAS (NOMBRE_MARCA) VALUES ('Wacom');

INSERT INTO MARCAS (NOMBRE_MARCA) VALUES ('XP Pen');

INSERT INTO MARCAS (NOMBRE_MARCA) VALUES ('AOC');

INSERT INTO MARCAS (NOMBRE_MARCA) VALUES ('Acer');

INSERT INTO MARCAS (NOMBRE_MARCA) VALUES ('Intel');

INSERT INTO MARCAS (NOMBRE_MARCA) VALUES ('AMD');

INSERT INTO MARCAS (NOMBRE_MARCA) VALUES ('Nvidia');

INSERT INTO MARCAS (NOMBRE_MARCA) VALUES ('Aerocool');

INSERT INTO MARCAS (NOMBRE_MARCA) VALUES ('ThermalTake');

INSERT INTO MARCAS (NOMBRE_MARCA) VALUES ('Antec');

INSERT INTO MARCAS (NOMBRE_MARCA) VALUES ('Corsair');

INSERT INTO MARCAS (NOMBRE_MARCA) VALUES ('Noctua');

INSERT INTO MARCAS (NOMBRE_MARCA) VALUES ('Cooler Master');

INSERT INTO MARCAS (NOMBRE_MARCA) VALUES ('NZXT');

INSERT INTO MARCAS (NOMBRE_MARCA) VALUES ('Lian LI');

INSERT INTO MARCAS (NOMBRE_MARCA) VALUES ('Red Dragon');

INSERT INTO MARCAS (NOMBRE_MARCA) VALUES ('Adata');

INSERT INTO MARCAS (NOMBRE_MARCA) VALUES ('G.SKILL');

INSERT INTO MARCAS (NOMBRE_MARCA) VALUES ('Xiaomi');

INSERT INTO MARCAS (NOMBRE_MARCA) VALUES ('MSI');

INSERT INTO MARCAS (NOMBRE_MARCA) VALUES ('Asus');

INSERT INTO MARCAS (NOMBRE_MARCA) VALUES ('Gigabyte');

INSERT INTO MARCAS (NOMBRE_MARCA) VALUES ('LG');

INSERT INTO MARCAS (NOMBRE_MARCA) VALUES ('Aorus');

-- =========================
-- PRODUCTOS
-- =========================

-- PERIFERICOS

INSERT INTO PRODUCTOS (ID_CATEGORIA, ID_MARCA, NOMBRE, DESCRIPCION, PRECIO, STOCK, IMAGEN) VALUES (1, 1, 'Razer BlackWidow V4', 'Teclado mecanico RGB', 150, 15, 'https://www.techzilla.cr/wp-content/uploads/2024/02/1-22.jpg.webp');

INSERT INTO PRODUCTOS (ID_CATEGORIA, ID_MARCA, NOMBRE, DESCRIPCION, PRECIO, STOCK, IMAGEN) VALUES (2, 3, 'Logitech G502', 'Mouse gamer alta precision', 80, 25, 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSDJQfsyLJjNpjHmgYCKX9CbwaeBW_3WnaY8A&s');

INSERT INTO PRODUCTOS (ID_CATEGORIA, ID_MARCA, NOMBRE, DESCRIPCION, PRECIO, STOCK, IMAGEN) VALUES (3, 5, 'HyperX SoloCast', 'Microfono USB condensador', 65, 18, 'https://www.cqnetcr.com/114105-thickbox_default/microfono-hyperx-solocast-usb-led-cardioide.jpg');

INSERT INTO PRODUCTOS (ID_CATEGORIA, ID_MARCA, NOMBRE, DESCRIPCION, PRECIO, STOCK, IMAGEN) VALUES (4, 1, 'Razer Kraken X', 'Headset gamer 7.1', 90, 20, 'https://m.media-amazon.com/images/I/51EafLX7lRL._AC_UF894,1000_QL80_.jpg');

INSERT INTO PRODUCTOS (ID_CATEGORIA, ID_MARCA, NOMBRE, DESCRIPCION, PRECIO, STOCK, IMAGEN) VALUES (5, 3, 'Logitech F310', 'Control USB para PC', 40, 30, 'https://holacompras.com/wp-content/uploads/2024/09/940-000110-2.png');

INSERT INTO PRODUCTOS (ID_CATEGORIA, ID_MARCA, NOMBRE, DESCRIPCION, PRECIO, STOCK, IMAGEN) VALUES (6, 23, 'Red Dragon Flick', 'Mouse Pad XL', 20, 40, 'https://www.techzilla.cr/wp-content/uploads/2024/02/redragon-flick-3xl-p040.jpg');

INSERT INTO PRODUCTOS (ID_CATEGORIA, ID_MARCA, NOMBRE, DESCRIPCION, PRECIO, STOCK, IMAGEN) VALUES (1, 3, 'Logitech G Pro X', 'Teclado mecanico profesional', 140, 12, 'https://www.techzilla.cr/wp-content/uploads/2025/01/Sin-titulo-1-162.jpg.webp');

INSERT INTO PRODUCTOS (ID_CATEGORIA, ID_MARCA, NOMBRE, DESCRIPCION, PRECIO, STOCK, IMAGEN) VALUES (1, 28, 'Asus TUF K3', 'Teclado mecanico RGB resistente', 110, 16, 'https://m.media-amazon.com/images/I/51lcg2odrdL._AC_SL1000_.jpg');

INSERT INTO PRODUCTOS (ID_CATEGORIA, ID_MARCA, NOMBRE, DESCRIPCION, PRECIO, STOCK, IMAGEN) VALUES (1, 29, 'Gigabyte K1', 'Teclado mecanico gamer', 95, 20, 'https://www.cqnetcr.com/114736-large_default/teclado-mecanico-gigabyte-aorus-k1-usb-usb-rgb.jpg');

INSERT INTO PRODUCTOS (ID_CATEGORIA, ID_MARCA, NOMBRE, DESCRIPCION, PRECIO, STOCK, IMAGEN) VALUES (2, 1, 'Razer DeathAdder V3', 'Mouse gamer ergonomico', 85, 22, 'https://www.techzilla.cr/wp-content/uploads/2023/07/MO2118-4.jpg.webp');

INSERT INTO PRODUCTOS (ID_CATEGORIA, ID_MARCA, NOMBRE, DESCRIPCION, PRECIO, STOCK, IMAGEN) VALUES (2, 27, 'MSI Clutch GM41', 'Mouse ligero 16000 DPI', 70, 18, 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRqH33uKN1EXfGkKhDrvbI6DdcEaJ5XOJ0bXg&s');

INSERT INTO PRODUCTOS (ID_CATEGORIA, ID_MARCA, NOMBRE, DESCRIPCION, PRECIO, STOCK, IMAGEN) VALUES (2, 30, 'LG Silent Mouse', 'Mouse inalambrico silencioso', 25, 40, 'https://www.intelec.co.cr/wp-content/uploads/2024/11/910-007116-1000x1000.webp');

INSERT INTO PRODUCTOS (ID_CATEGORIA, ID_MARCA, NOMBRE, DESCRIPCION, PRECIO, STOCK, IMAGEN) VALUES (3, 5, 'HyperX QuadCast', 'Microfono RGB profesional', 130, 14, 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSVcU4kzETFxPYjbi7EcJRdtyd81m6re8puMg&s');

INSERT INTO PRODUCTOS (ID_CATEGORIA, ID_MARCA, NOMBRE, DESCRIPCION, PRECIO, STOCK, IMAGEN) VALUES (3, 6, 'HP Streaming Mic', 'Microfono USB compacto', 55, 19, 'https://hp.widen.net/content/lizgrksgs4/webp/lizgrksgs4.png?dpi=72&color=ffffff00&w=270');

INSERT INTO PRODUCTOS (ID_CATEGORIA, ID_MARCA, NOMBRE, DESCRIPCION, PRECIO, STOCK, IMAGEN) VALUES (4, 23, 'Red Dragon Zeus X', 'Headset gamer 7.1 RGB', 75, 21, 'https://extremetechcr.com/wp-content/uploads/2024/11/37890.jpg');

INSERT INTO PRODUCTOS (ID_CATEGORIA, ID_MARCA, NOMBRE, DESCRIPCION, PRECIO, STOCK, IMAGEN) VALUES (4, 1, 'Razer Barracuda X', 'Headset inalambrico', 120, 13, 'https://m.media-amazon.com/images/I/71qKH+vJ+IL._AC_SL1500_.jpg');
-- COMPONENTES
INSERT INTO PRODUCTOS (ID_CATEGORIA, ID_MARCA, NOMBRE, DESCRIPCION, PRECIO, STOCK, IMAGEN) VALUES (7, 4, 'Kingston Fury 16GB', 'RAM DDR4 16GB 3200MHz', 75, 35, 'https://www.intelec.co.cr/wp-content/uploads/2024/11/910-005469.webp');

INSERT INTO PRODUCTOS (ID_CATEGORIA, ID_MARCA, NOMBRE, DESCRIPCION, PRECIO, STOCK, IMAGEN) VALUES (7, 18, 'Corsair Vengeance 16GB', 'RAM DDR4 16GB 3200MHz', 75, 30, 'https://coretms.tecnomegastore.ec/assets/images/main/26/DIMCORH325MB638.webp');

INSERT INTO PRODUCTOS (ID_CATEGORIA, ID_MARCA, NOMBRE, DESCRIPCION, PRECIO, STOCK, IMAGEN) VALUES (7, 4, 'Kingston Fury Beast 16GB', 'RAM DDR5 16GB 5200MHz', 95, 25, 'https://media.kingston.com/kingston/product/FURY_Beast_Black_DDR4_1_pkg-zm-lg.jpg');

INSERT INTO PRODUCTOS (ID_CATEGORIA, ID_MARCA, NOMBRE, DESCRIPCION, PRECIO, STOCK, IMAGEN) VALUES (7, 25, 'G.SKILL Trident Z 32GB', 'RAM DDR4 32GB 3600MHz', 160, 15, 'https://cyberteamcr.com/wp-content/uploads/2025/10/20588_18063.jpg');

INSERT INTO PRODUCTOS (ID_CATEGORIA, ID_MARCA, NOMBRE, DESCRIPCION, PRECIO, STOCK, IMAGEN) VALUES (7, 5, 'HyperX Fury 8GB', 'RAM DDR4 8GB 3200MHz', 40, 45, 'https://gabastorecr.com/wp-content/uploads/2023/04/CP-HYPERX-HX430C15FB38-3.jpg');

INSERT INTO PRODUCTOS (ID_CATEGORIA, ID_MARCA, NOMBRE, DESCRIPCION, PRECIO, STOCK, IMAGEN) VALUES (8, 4, 'Kingston NV2 500GB', 'SSD NVMe 500GB', 60, 30, 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRzArqEmGk7l-FX2zNvSuik-iiZWMxme6GA4w&s');

INSERT INTO PRODUCTOS (ID_CATEGORIA, ID_MARCA, NOMBRE, DESCRIPCION, PRECIO, STOCK, IMAGEN) VALUES (8, 2, 'Samsung 980 Pro 2TB', 'SSD NVMe Gen4 2TB', 210, 9, 'https://m.media-amazon.com/images/I/81mJYmdViYL._SY250_.jpg');

INSERT INTO PRODUCTOS (ID_CATEGORIA, ID_MARCA, NOMBRE, DESCRIPCION, PRECIO, STOCK, IMAGEN) VALUES (8, 24, 'Adata Legend 1TB', 'SSD NVMe 1TB', 110, 22, 'https://www.intelec.co.cr/wp-content/uploads/2025/01/SLEG-860-1000GCS.png');

INSERT INTO PRODUCTOS (ID_CATEGORIA, ID_MARCA, NOMBRE, DESCRIPCION, PRECIO, STOCK, IMAGEN) VALUES (8, 24, 'Adata SU650 480GB', 'SSD SATA 480GB', 50, 28, 'https://webapi3.adata.com/storage/product/23_p_su650_04_0628.jpg');

INSERT INTO PRODUCTOS (ID_CATEGORIA, ID_MARCA, NOMBRE, DESCRIPCION, PRECIO, STOCK, IMAGEN) VALUES (9, 13, 'AMD RX 7600', 'Tarjeta grafica 8GB GDDR6', 350, 11, 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS_1Fyq8_ShJhNWj4NQbgNEnfrFn6iEps0U1w&s');

INSERT INTO PRODUCTOS (ID_CATEGORIA, ID_MARCA, NOMBRE, DESCRIPCION, PRECIO, STOCK, IMAGEN) VALUES (9, 14, 'Nvidia RTX 4060', 'Tarjeta grafica 8GB GDDR6', 400, 12, 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRpC6en7rI64nIKGcO5IZroW88IMvxruwHqrg&s');

INSERT INTO PRODUCTOS (ID_CATEGORIA, ID_MARCA, NOMBRE, DESCRIPCION, PRECIO, STOCK, IMAGEN) VALUES (9, 27, 'MSI RTX 4070', 'Tarjeta grafica 12GB', 650, 7, 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSsgtRmSlEkEXOzxNRFkUdw4VbXPlT18b0rJA&s');

INSERT INTO PRODUCTOS (ID_CATEGORIA, ID_MARCA, NOMBRE, DESCRIPCION, PRECIO, STOCK, IMAGEN) VALUES (9, 29, 'Gigabyte RTX 4090', 'Tarjeta grafica 24GB GDDR6X', 1600, 3, 'https://images-na.ssl-images-amazon.com/images/I/71TZmq7RYtL._AC_UL495_SR435,495_.jpg');

INSERT INTO PRODUCTOS (ID_CATEGORIA, ID_MARCA, NOMBRE, DESCRIPCION, PRECIO, STOCK, IMAGEN) VALUES (10, 16, 'ThermalTake Water 3.0', 'Refrigeracion liquida 240mm', 130, 10, 'https://cdn11.bigcommerce.com/s-p52by1ef7/images/stencil/1280x1280/products/89232/89470/CA-007PL12__06771__83353.1550182145.JPG?c=2');

INSERT INTO PRODUCTOS (ID_CATEGORIA, ID_MARCA, NOMBRE, DESCRIPCION, PRECIO, STOCK, IMAGEN) VALUES (10, 20, 'Cooler Master ML240L', 'Refrigeracion liquida RGB', 125, 12, 'https://m.media-amazon.com/images/I/61g3UkYPnmL._SL1500_.jpg');

INSERT INTO PRODUCTOS (ID_CATEGORIA, ID_MARCA, NOMBRE, DESCRIPCION, PRECIO, STOCK, IMAGEN) VALUES (10, 18, 'Corsair H100i', 'Watercooling 240mm', 150, 8, 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT0NqZzCtq-hshsB9yu_U3g2nFkz6vboY4Hvg&s');

INSERT INTO PRODUCTOS (ID_CATEGORIA, ID_MARCA, NOMBRE, DESCRIPCION, PRECIO, STOCK, IMAGEN) VALUES (11, 21, 'NZXT F120 RGB', 'Ventilador RGB 120mm', 30, 35, 'https://m.media-amazon.com/images/I/51dYwbuFI1L._SL1000_.jpg');

INSERT INTO PRODUCTOS (ID_CATEGORIA, ID_MARCA, NOMBRE, DESCRIPCION, PRECIO, STOCK, IMAGEN) VALUES (11, 19, 'Noctua NF-A12x25', 'Ventilador 120mm silencioso', 35, 50, 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQzSH8VG2xxvbtjy8-i_6Mxj774CY3uZPlkNA&s');

INSERT INTO PRODUCTOS (ID_CATEGORIA, ID_MARCA, NOMBRE, DESCRIPCION, PRECIO, STOCK, IMAGEN) VALUES (11, 17, 'Antec Prizm 120', 'Ventilador alto flujo', 28, 42, 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTqSOaXrpgcNUW1I8b_Ldt5_Pzpn1IYpbgAfQ&s');
-- HOGAR
INSERT INTO PRODUCTOS (ID_CATEGORIA, ID_MARCA, NOMBRE, DESCRIPCION, PRECIO, STOCK, IMAGEN) VALUES (12, 31, 'Aorus OLED 48"', 'TV OLED 4K 120Hz', 900, 5, 'https://m.media-amazon.com/images/I/71xAK1yIIwL._AC_UF894,1000_QL80_.jpg');

INSERT INTO PRODUCTOS (ID_CATEGORIA, ID_MARCA, NOMBRE, DESCRIPCION, PRECIO, STOCK, IMAGEN) VALUES (12, 2, 'Samsung Crystal 50"', 'Smart TV 4K UHD', 500, 10, 'https://me-tiendamexpress.s3.us-east-1.amazonaws.com/images/thumbs/0064255_pantalla-samsung-50-un50du7000pxpa-smart-tv-4k_600.png');

INSERT INTO PRODUCTOS (ID_CATEGORIA, ID_MARCA, NOMBRE, DESCRIPCION, PRECIO, STOCK, IMAGEN) VALUES (13, 26, 'Xiaomi Mi Router AX1800', 'Router WiFi 6 Dual Band', 85, 18, 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ4Jgdbdze_4TS6ihdqRT_EI-YZLYbJ09LsaA&s');

INSERT INTO PRODUCTOS (ID_CATEGORIA, ID_MARCA, NOMBRE, DESCRIPCION, PRECIO, STOCK, IMAGEN) VALUES (13, 7, 'Huawei WiFi Mesh 7', 'Sistema Mesh WiFi', 180, 6, 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQveSkVJGYbhXRj584YiwgGc4IrAvpihYwFQA&s');

COMMIT;

SELECT * FROM PRODUCTOS;

-- =========================
-- PRODUCTO_ATRIBUTOS
-- =========================
-- =======================================================
-- PERIFÉRICOS — Teclados
-- =======================================================


-- 1: Razer BlackWidow V4
INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (1, 'Switch', 'Razer Green Mecánico');

INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (1, 'Retroiluminación', 'RGB Chroma');

INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (1, 'Conexión', 'USB');

INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (1, 'Layout', 'Teclado Completo');

INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (1, 'Anti-ghosting', 'Sí');

-- 7: Logitech G Pro X
INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (7, 'Switch', 'GX Blue Intercambiable');

INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (7, 'Retroiluminación', 'RGB Lightsync');

INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (7, 'Conexión', 'USB');

INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (7, 'Layout', 'TKL (Sin numpad)');

INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (7, 'Anti-ghosting', 'Sí');

-- 8: Asus TUF K3
INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (8, 'Switch', 'Red Lineal');

INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (8, 'Retroiluminación', 'RGB Aura Sync');

INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (8, 'Conexión', 'USB');

INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (8, 'Resistencia', 'Certificado IP56');

INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (8, 'Layout', 'Teclado Completo');

-- 9: Gigabyte K1
INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (9, 'Switch', 'Cherry MX Red');

INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (9, 'Retroiluminación', 'RGB por tecla');

INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (9, 'Conexión', 'USB');

INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (9, 'Layout', 'Teclado Completo');

INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (9, 'Anti-ghosting', 'N-Key Rollover');

-- =======================================================
-- PERIFÉRICOS — Mouses
-- =======================================================

-- 2: Logitech G502
INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (2, 'DPI Máximo', '25600 DPI');

INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (2, 'Botones', '11');

INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (2, 'Sensor', 'HERO 25K');

INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (2, 'Conexión', 'USB');

INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (2, 'Pesos ajustables', 'Sí');

-- 10: Razer DeathAdder V3
INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (10, 'DPI Máximo', '30000 DPI');

INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (10, 'Botones', '6');

INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (10, 'Sensor', 'Focus Pro 30K');

INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (10, 'Conexión', 'USB');

INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (10, 'Peso', '59g');

-- 11: MSI Clutch GM41
INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (11, 'DPI Máximo', '16000 DPI');

INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (11, 'Botones', '6');

INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (11, 'Sensor', 'PixArt PMW3389');

INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (11, 'Conexión', 'USB');

INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (11, 'Peso', '65g');

-- 12: LG Silent Mouse
INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (12, 'DPI Máximo', '1600 DPI');

INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (12, 'Botones', '3');

INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (12, 'Conexión', 'Inalámbrico 2.4GHz');

INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (12, 'Batería', 'AA x1');

INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (12, 'Nivel de ruido', 'Silencioso (-90% ruido)');

-- =======================================================
-- PERIFÉRICOS — Micrófonos
-- =======================================================

-- 3: HyperX SoloCast
INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (3, 'Tipo de cápsula', 'Condensador');

INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (3, 'Patrón polar', 'Cardioide');

INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (3, 'Conexión', 'USB-C');

INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (3, 'Frecuencia', '20Hz - 20kHz');

INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (3, 'Resolución', '16 bit / 48kHz');

-- 13: HyperX QuadCast
INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (13, 'Tipo de cápsula', 'Condensador x4');

INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (13, 'Patrón polar', 'Estéreo / Cardioide / Bidireccional / Omnidireccional');

INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (13, 'Conexión', 'USB');

INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (13, 'Retroiluminación', 'RGB');

INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (13, 'Resolución', '24 bit / 96kHz');

-- 14: HP Streaming Mic
INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (14, 'Tipo de cápsula', 'Condensador');

INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (14, 'Patrón polar', 'Cardioide');

INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (14, 'Conexión', 'USB');

INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (14, 'Frecuencia', '100Hz - 18kHz');

INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (14, 'Resolución', '16 bit / 44.1kHz');

-- =======================================================
-- PERIFÉRICOS — Headsets
-- =======================================================

-- 4: Razer Kraken X
INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (4, 'Audio', '7.1 Surround');

INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (4, 'Drivers', '40mm');

INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (4, 'Frecuencia', '12Hz - 28kHz');

INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (4, 'Conexión', 'Jack 3.5mm');

INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (4, 'Peso', '250g');

-- 15: Red Dragon Zeus X
INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (15, 'Audio', '7.1 Virtual Surround');

INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (15, 'Drivers', '53mm');

INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (15, 'Retroiluminación', 'RGB');

INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (15, 'Conexión', 'USB');

INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (15, 'Micrófono desmontable', 'Sí');

-- 16: Razer Barracuda X
INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (16, 'Audio', 'Estéreo');

INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (16, 'Drivers', '40mm');

INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (16, 'Conexión', 'Inalámbrico 2.4GHz / USB-C');

INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (16, 'Batería', 'Hasta 50 horas');

INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (16, 'Peso', '250g');

-- =======================================================
-- PERIFÉRICOS — Controles y Mouse Pads
-- =======================================================

-- 5: Logitech F310
INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (5, 'Conexión', 'USB');

INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (5, 'Botones', '12');

INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (5, 'Vibración', 'No');

INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (5, 'Modo D/X', 'Sí (switch)');

INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (5, 'Compatible con', 'Windows / Android');

-- 6: Red Dragon Flick
INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (6, 'Tamaño', 'XL (900 x 300mm)');

INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (6, 'Grosor', '3mm');

INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (6, 'Base', 'Antideslizante');

INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (6, 'Material superficie', 'Tela microfibra');

INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (6, 'Bordes cosidos', 'Sí');

-- =======================================================
-- COMPONENTES — Memoria RAM
-- =======================================================

-- 17: Kingston Fury 16GB (DDR4)
INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (17, 'Capacidad', '16GB');
INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (17, 'Tipo', 'DDR4');

INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (17, 'Frecuencia', '3200MHz');

INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (17, 'Latencia', 'CL16');

INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (17, 'Voltaje', '1.35V');

-- 18: Corsair Vengeance 16GB
INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (18, 'Capacidad', '16GB');

INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (18, 'Tipo', 'DDR4');

INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (18, 'Frecuencia', '3200MHz');

INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (18, 'Latencia', 'CL16');

INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (18, 'Voltaje', '1.35V');

-- 19: Kingston Fury Beast 16GB (DDR5)
INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (19, 'Capacidad', '16GB');

INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (19, 'Tipo', 'DDR5');

INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (19, 'Frecuencia', '5200MHz');

INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (19, 'Latencia', 'CL40');

INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (19, 'Voltaje', '1.1V');

-- 20: G.SKILL Trident Z 32GB
INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (20, 'Capacidad', '32GB (2x16GB)');

INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (20, 'Tipo', 'DDR4');

INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (20, 'Frecuencia', '3600MHz');

INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (20, 'Latencia', 'CL18');

INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (20, 'Retroiluminación', 'RGB');

-- 21: HyperX Fury 8GB
INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (21, 'Capacidad', '8GB');

INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (21, 'Tipo', 'DDR4');

INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (21, 'Frecuencia', '3200MHz');

INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (21, 'Latencia', 'CL16');

INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (21, 'Voltaje', '1.35V');

-- =======================================================
-- COMPONENTES — Almacenamiento
-- =======================================================

-- 22: Kingston NV2 500GB
INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (22, 'Capacidad', '500GB');

INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (22, 'Tipo', 'NVMe PCIe 4.0');

INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (22, 'Lectura secuencial', '3500MB/s');

INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (22, 'Escritura secuencial', '2100MB/s');

INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (22, 'Factor de forma', 'M.2 2280');

-- 23: Samsung 980 Pro 2TB
INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (23, 'Capacidad', '2TB');

INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (23, 'Tipo', 'NVMe PCIe 4.0 Gen4');

INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (23, 'Lectura secuencial', '7000MB/s');

INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (23, 'Escritura secuencial', '5100MB/s');

INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (23, 'Factor de forma', 'M.2 2280');

-- 24: Adata Legend 1TB
INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (24, 'Capacidad', '1TB');

INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (24, 'Tipo', 'NVMe PCIe 4.0');

INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (24, 'Lectura secuencial', '5000MB/s');

INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (24, 'Escritura secuencial', '4500MB/s');

INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (24, 'Factor de forma', 'M.2 2280');

-- 25: Adata SU650 480GB
INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (25, 'Capacidad', '480GB');

INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (25, 'Tipo', 'SATA III 2.5"');

INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (25, 'Lectura secuencial', '520MB/s');

INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (25, 'Escritura secuencial', '450MB/s');

INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (25, 'Factor de forma', '2.5 pulgadas');


-- =======================================================
-- COMPONENTES — Gráficas
-- =======================================================

-- 26: AMD RX 7600
INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (26, 'VRAM', '8GB GDDR6');

INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (26, 'Bus de memoria', '128-bit');

INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (26, 'Núcleos de cómputo', '2048');

INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (26, 'TDP', '165W');

INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (26, 'Conectores de video', 'HDMI 2.1 / DP 2.1');

INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (26, 'Proceso de fabricación', '6nm');

INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (26, 'Ray Tracing', 'Sí');

-- 27: Nvidia RTX 4060
INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (27, 'VRAM', '8GB GDDR6');

INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (27, 'Bus de memoria', '128-bit');

INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (27, 'CUDA Cores', '3072');

INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (27, 'TDP', '115W');

INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (27, 'Conectores de video', 'HDMI 2.1 / DP 1.4');

INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (27, 'Proceso de fabricación', '4nm');

INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (27, 'Ray Tracing', 'Sí (3ra gen)');

-- 28: MSI RTX 4070
INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (28, 'VRAM', '12GB GDDR6X');

INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (28, 'Bus de memoria', '192-bit');

INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (28, 'CUDA Cores', '5888');

INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (28, 'TDP', '200W');

INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (28, 'Conectores de video', 'HDMI 2.1 / DP 1.4 x3');

INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (28, 'Proceso de fabricación', '4nm');

INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (28, 'Ray Tracing', 'Sí (3ra gen)');

-- 29: Gigabyte RTX 4090
INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (29, 'VRAM', '24GB GDDR6X');

INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (29, 'Bus de memoria', '384-bit');

INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (29, 'CUDA Cores', '16384');

INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (29, 'TDP', '450W');

INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (29, 'Conectores de video', 'HDMI 2.1 / DP 1.4 x3');

INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (29, 'Proceso de fabricación', '4nm');

INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (29, 'Ray Tracing', 'Sí (3ra gen)');

-- =======================================================
-- COMPONENTES — Refrigeración
-- =======================================================

-- 30: ThermalTake Water 3.0
INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (30, 'Tipo', 'Refrigeración líquida AIO');

INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (30, 'Tamaño radiador', '240mm');

INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (30, 'Ventiladores incluidos', '2 x 120mm');

INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (30, 'Socket compatible', 'LGA1700 / AM5 / AM4');

INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (30, 'Retroiluminación', 'No');

-- 31: Cooler Master ML240L
INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (31, 'Tipo', 'Refrigeración líquida AIO');

INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (31, 'Tamaño radiador', '240mm');

INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (31, 'Ventiladores incluidos', '2 x 120mm');

INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (31, 'Socket compatible', 'LGA1700 / AM4');

INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (31, 'Retroiluminación', 'RGB');

-- 32: Corsair H100i
INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (32, 'Tipo', 'Refrigeración líquida AIO');

INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (32, 'Tamaño radiador', '240mm');

INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (32, 'Ventiladores incluidos', '2 x 120mm PWM');

INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (32, 'Socket compatible', 'LGA1700 / LGA1200 / AM5 / AM4');

INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (32, 'Software', 'iCUE compatible');

-- =======================================================
-- COMPONENTES — Ventilación
-- =======================================================

-- 33: NZXT F120 RGB
INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (33, 'Diámetro', '120mm');

INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (33, 'Velocidad', '500 - 1800 rpm');

INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (33, 'Flujo de aire', '52.44 CFM');

INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (33, 'Nivel de ruido', '28 dBA');

INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (33, 'Retroiluminación', 'RGB');

-- 34: Noctua NF-A12x25
INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (34, 'Diámetro', '120mm');

INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (34, 'Velocidad', '450 - 2000 rpm');

INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (34, 'Flujo de aire', '60.09 CFM');

INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (34, 'Nivel de ruido', '22.6 dBA');

INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (34, 'Retroiluminación', 'No');

-- 35: Antec Prizm 120
INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (35, 'Diámetro', '120mm');

INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (35, 'Velocidad', '800 - 1600 rpm');

INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (35, 'Flujo de aire', '56 CFM');

INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (35, 'Nivel de ruido', '26 dBA');

INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (35, 'Retroiluminación', 'RGB Dual-ring');

-- =======================================================
-- HOGAR — Televisores
-- =======================================================

-- 36: Aorus OLED 48"
INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (36, 'Panel', 'OLED');

INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (36, 'Resolución', '4K UHD (3840x2160)');

INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (36, 'Frecuencia de refresco', '120Hz');

INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (36, 'HDR', 'HDR10 / Dolby Vision');

INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (36, 'Smart TV', 'Sí');

INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (36, 'HDMI', '4 x HDMI 2.1');

-- 37: Samsung Crystal 50"
INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (37, 'Panel', 'Crystal UHD');

INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (37, 'Resolución', '4K UHD (3840x2160)');

INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (37, 'Frecuencia de refresco', '60Hz');
INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (37, 'HDR', 'HDR10+');

INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (37, 'Smart TV', 'Sí (Tizen OS)');

INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (37, 'HDMI', '3 x HDMI 2.0');

-- =======================================================
-- HOGAR — Routers
-- =======================================================

INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (38, 'Estándar WiFi', 'WiFi 6 (802.11ax)');

INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (38, 'Velocidad', 'AX1800 (1800 Mbps)');

INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (38, 'Bandas', 'Dual Band 2.4GHz + 5GHz');

INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (38, 'Antenas', '4 antenas externas');

INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (38, 'Puertos LAN', '3 x Gigabit');

INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (39, 'Estándar WiFi', 'WiFi 7 (802.11be)');

INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (39, 'Velocidad', 'BE7200 (7200 Mbps)');

INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (39, 'Bandas', 'Tri Band 2.4 / 5 / 6GHz');

INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (39, 'Mesh', 'Sí — HiLink Mesh');

INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (39, 'Puertos LAN', '4 x 2.5G + 1 x 10G');


COMMIT;

-- =========================
-- METODOS_PAGO
-- =========================
INSERT INTO METODOS_PAGO (NOMBRE) VALUES ('Efectivo');

INSERT INTO METODOS_PAGO (NOMBRE) VALUES ('Tarjeta');

INSERT INTO METODOS_PAGO (NOMBRE) VALUES ('Transferencia');
COMMIT;

-- =========================
-- CLIENTES
-- =========================
INSERT INTO CLIENTES (NOMBRE, APELLIDO) VALUES ('Luis',     'Mora');

INSERT INTO CLIENTES (NOMBRE, APELLIDO) VALUES ('Valeria',  'Castro');

INSERT INTO CLIENTES (NOMBRE, APELLIDO) VALUES ('Diego',    'Vargas');

INSERT INTO CLIENTES (NOMBRE, APELLIDO) VALUES ('Sofia',    'Jimenez');

INSERT INTO CLIENTES (NOMBRE, APELLIDO) VALUES ('Andres',   'Salazar');
COMMIT;

SELECT * FROM CLIENTES;

-- =========================
-- USUARIOS
-- ========================
INSERT INTO USUARIOS (USERNAME, PASSWORD, ROL) VALUES ('admin', 'admin123', 'ADMIN');

INSERT INTO USUARIOS (USERNAME, PASSWORD, ROL) VALUES ('vendedor1', 'vend123', 'VENDEDOR');

INSERT INTO USUARIOS (USERNAME, PASSWORD, ROL, ID_CLIENTE) VALUES ('Luis', '1234', 'CLIENTE', 1);

INSERT INTO USUARIOS (USERNAME, PASSWORD, ROL, ID_CLIENTE) VALUES ('Valeria', '1234', 'CLIENTE', 2);

INSERT INTO USUARIOS (USERNAME, PASSWORD, ROL, ID_CLIENTE)  VALUES ('diegov', '1234', 'CLIENTE', 3);

INSERT INTO USUARIOS (USERNAME, PASSWORD, ROL, ID_CLIENTE)  VALUES ('sofiaj', '1234', 'CLIENTE', 4);

INSERT INTO USUARIOS (USERNAME, PASSWORD, ROL, ID_CLIENTE)  VALUES ('andress', '1234', 'CLIENTE', 5);

SELECT * FROM USUARIOS;
COMMIT;

-- =========================
-- PROVEEDORES
-- =========================
INSERT INTO PROVEEDORES (NOMBRE, CORREO) VALUES ('Distribuidora Tech', 'ventas@distech.com');

INSERT INTO PROVEEDORES (NOMBRE, CORREO) VALUES ('Importadora Digital', 'contacto@impodigital.com');

INSERT INTO PROVEEDORES (NOMBRE, CORREO) VALUES ('CompuMayorista', 'info@compumayorista.com');
COMMIT;

-- =========================
-- TELEFONOS CLIENTES
-- =========================
INSERT INTO TELEFONOS (ID_CLIENTE, TELEFONO) VALUES (1, '84445555');

INSERT INTO TELEFONOS (ID_CLIENTE, TELEFONO) VALUES (2, '85556666');

INSERT INTO TELEFONOS (ID_CLIENTE, TELEFONO) VALUES (3, '86667777');

INSERT INTO TELEFONOS (ID_CLIENTE, TELEFONO) VALUES (4, '87778888');

INSERT INTO TELEFONOS (ID_CLIENTE, TELEFONO) VALUES (5, '88889999');
COMMIT;

-- =========================
-- CORREOS CLIENTES
-- =========================
INSERT INTO CORREOS (ID_CLIENTE, CORREO) VALUES (1, 'luis.mora@gmail.com');

INSERT INTO CORREOS (ID_CLIENTE, CORREO) VALUES (2, 'valeria.castro@hotmail.com');

INSERT INTO CORREOS (ID_CLIENTE, CORREO) VALUES (3, 'diego.vargas@outlook.com');

INSERT INTO CORREOS (ID_CLIENTE, CORREO) VALUES (4, 'sofia.jimenez@gmail.com');

INSERT INTO CORREOS (ID_CLIENTE, CORREO) VALUES (5, 'andres.salazar@yahoo.com');
COMMIT;

-- =========================
-- DIRECCIONES
-- =========================
INSERT INTO DIRECCIONES (ID_CLIENTE, DIRECCION) VALUES (1, 'Av Siempre Viva 123');

INSERT INTO DIRECCIONES (ID_CLIENTE, DIRECCION) VALUES (2, 'Calle Central 456');

INSERT INTO DIRECCIONES (ID_CLIENTE, DIRECCION) VALUES (3, 'Zona Norte 789');

INSERT INTO DIRECCIONES (ID_CLIENTE, DIRECCION) VALUES (4, 'Boulevard Principal 321');

INSERT INTO DIRECCIONES (ID_CLIENTE, DIRECCION) VALUES (5, 'Barrio Los Yoses, San Jose');

COMMIT;



-- =========================
-- TELEFONOS PROVEEDOR
-- =========================
INSERT INTO TELEFONOS_PROVEEDOR (ID_PROVEEDOR, TELEFONO) VALUES (1, '80001111');

INSERT INTO TELEFONOS_PROVEEDOR (ID_PROVEEDOR, TELEFONO) VALUES (2, '80002222');

INSERT INTO TELEFONOS_PROVEEDOR (ID_PROVEEDOR, TELEFONO) VALUES (3, '80003333');
COMMIT;


-- =========================
-- DETALLE_VENTA
-- =========================

INSERT INTO DETALLE_VENTAS (ID_CLIENTE, ID_METODO) VALUES (1, 2);

INSERT INTO DETALLE_VENTAS (ID_CLIENTE, ID_METODO) VALUES (2, 1);

INSERT INTO DETALLE_VENTAS (ID_CLIENTE, ID_METODO) VALUES (3, 3);

INSERT INTO DETALLE_VENTAS (ID_CLIENTE, ID_METODO) VALUES (4, 2);

INSERT INTO DETALLE_VENTAS (ID_CLIENTE, ID_METODO) VALUES (5, 1);

SELECT * FROM DETALLE_VENTAS;

 
COMMIT;

-- =========================
-- VENTAS
-- =========================

INSERT INTO VENTAS (ID_DETALLE, ID_PRODUCTO, CANTIDAD, PRECIO_UNITARIO) VALUES (1, 1,  1, 150);

INSERT INTO VENTAS (ID_DETALLE, ID_PRODUCTO, CANTIDAD, PRECIO_UNITARIO) VALUES (1, 2,  1,  80);
 
INSERT INTO VENTAS (ID_DETALLE, ID_PRODUCTO, CANTIDAD, PRECIO_UNITARIO) VALUES (2, 4,  1,  90);
 
INSERT INTO VENTAS (ID_DETALLE, ID_PRODUCTO, CANTIDAD, PRECIO_UNITARIO) VALUES (3, 20, 1, 160);

INSERT INTO VENTAS (ID_DETALLE, ID_PRODUCTO, CANTIDAD, PRECIO_UNITARIO) VALUES (4, 17, 2,  75);

INSERT INTO VENTAS (ID_DETALLE, ID_PRODUCTO, CANTIDAD, PRECIO_UNITARIO) VALUES (4, 22, 1,  60);
 
INSERT INTO VENTAS (ID_DETALLE, ID_PRODUCTO, CANTIDAD, PRECIO_UNITARIO) VALUES (5, 27, 1, 400);

INSERT INTO VENTAS (ID_DETALLE, ID_PRODUCTO, CANTIDAD, PRECIO_UNITARIO) VALUES (5, 26, 2, 400);

SELECT * FROM VENTAS;
SET DEFINE ON;


COMMIT;










