DROP TABLE DETALLE_VENTAS CASCADE CONSTRAINTS;
DROP TABLE PRODUCTO_ATRIBUTOS CASCADE CONSTRAINTS;
DROP TABLE TELEFONOS CASCADE CONSTRAINTS;
DROP TABLE TELEFONOS_PROVEEDOR CASCADE CONSTRAINTS;
DROP TABLE CORREOS CASCADE CONSTRAINTS;
DROP TABLE DIRECCIONES CASCADE CONSTRAINTS;
DROP TABLE USUARIOS CASCADE CONSTRAINTS;
DROP TABLE VENTAS CASCADE CONSTRAINTS;
DROP TABLE PRODUCTOS CASCADE CONSTRAINTS;
DROP TABLE PROVEEDORES CASCADE CONSTRAINTS;
DROP TABLE CLIENTES CASCADE CONSTRAINTS;
DROP TABLE METODOS_PAGO CASCADE CONSTRAINTS;
DROP TABLE MARCAS CASCADE CONSTRAINTS;
DROP TABLE CATEGORIAS CASCADE CONSTRAINTS;
DROP TABLE CARRITO CASCADE CONSTRAINTS;
DROP TABLE AUDITORIA_SISTEMA CASCADE CONSTRAINTS;
DROP TRIGGER TRG_DESCONTAR_STOCK;

DROP PROCEDURE SP_REGISTRAR_VENTA;