
-- =========================
-- 1. TOTAL_VENTA
-- Retorna el total de un pedido (ID_DETALLE)
-- sumando CANTIDAD * PRECIO_UNITARIO de cada línea
-- =========================
CREATE OR REPLACE FUNCTION TOTAL_VENTA
(
    P_ID_DETALLE NUMBER
)
RETURN NUMBER
IS
    V_TOTAL   NUMBER := 0;
    V_CANT    NUMBER;
    V_PRECIO  NUMBER;

    CURSOR C_LINEAS IS
        SELECT CANTIDAD, PRECIO_UNITARIO
        FROM VENTAS
        WHERE ID_DETALLE = P_ID_DETALLE;

BEGIN
    IF P_ID_DETALLE IS NULL THEN
        RAISE_APPLICATION_ERROR(-20001, 'El ID de pedido no puede ser nulo.');
    END IF;

    OPEN C_LINEAS;
    LOOP
        FETCH C_LINEAS INTO V_CANT, V_PRECIO;
        EXIT WHEN C_LINEAS%NOTFOUND;
        V_TOTAL := V_TOTAL + (V_CANT * V_PRECIO);
    END LOOP;
    CLOSE C_LINEAS;

    RETURN NVL(V_TOTAL, 0);

EXCEPTION
    WHEN NO_DATA_FOUND THEN
        RETURN 0;
    WHEN OTHERS THEN
        RAISE_APPLICATION_ERROR(-20002, 'Error en TOTAL_VENTA: ' || SQLERRM);
END;
/

SELECT TOTAL_VENTA(2) AS TOTAL FROM DUAL;


-- =========================
-- 2. VALOR_INVENTARIO
-- Retorna el valor total del inventario
-- sumando PRECIO * STOCK de todos los productos
-- =========================
CREATE OR REPLACE FUNCTION VALOR_INVENTARIO
RETURN NUMBER
IS
    V_TOTAL  NUMBER := 0;
    V_PRECIO NUMBER;
    V_STOCK  NUMBER;
    V_NOMBRE VARCHAR2(100);

    CURSOR C_PRODUCTOS IS
        SELECT NOMBRE, PRECIO, STOCK
        FROM PRODUCTOS
        WHERE STOCK > 0;

BEGIN
    OPEN C_PRODUCTOS;
    LOOP
        FETCH C_PRODUCTOS INTO V_NOMBRE, V_PRECIO, V_STOCK;
        EXIT WHEN C_PRODUCTOS%NOTFOUND;
        V_TOTAL := V_TOTAL + (V_PRECIO * V_STOCK);
    END LOOP;
    CLOSE C_PRODUCTOS;

    RETURN NVL(V_TOTAL, 0);

EXCEPTION
    WHEN NO_DATA_FOUND THEN
        RETURN 0;
    WHEN OTHERS THEN
        RAISE_APPLICATION_ERROR(-20003, 'Error en VALOR_INVENTARIO: ' || SQLERRM);
END;
/

SELECT VALOR_INVENTARIO() AS VALOR_TOTAL_INVENTARIO FROM DUAL;


-- =========================
-- 3. PRODUCTOS_POR_CATEGORIA
-- Retorna cuántos productos tiene una categoría
-- =========================
CREATE OR REPLACE FUNCTION PRODUCTOS_POR_CATEGORIA
(
    P_ID_CATEGORIA NUMBER
)
RETURN NUMBER
IS
    V_TOTAL      NUMBER := 0;
    V_NOMBRE_CAT VARCHAR2(100);

    CURSOR C_PRODUCTOS IS
        SELECT COUNT(*) AS TOTAL
        FROM PRODUCTOS
        WHERE ID_CATEGORIA = P_ID_CATEGORIA;

BEGIN
    IF P_ID_CATEGORIA IS NULL THEN
        RAISE_APPLICATION_ERROR(-20004, 'El ID de categoría no puede ser nulo.');
    END IF;

    BEGIN
        SELECT NOMBRE_CATEGORIA INTO V_NOMBRE_CAT
        FROM CATEGORIAS
        WHERE ID_CATEGORIA = P_ID_CATEGORIA;
    EXCEPTION
        WHEN NO_DATA_FOUND THEN
            RAISE_APPLICATION_ERROR(-20005, 'La categoría ' || P_ID_CATEGORIA || ' no existe.');
    END;

    OPEN C_PRODUCTOS;
    FETCH C_PRODUCTOS INTO V_TOTAL;
    CLOSE C_PRODUCTOS;

    RETURN NVL(V_TOTAL, 0);

EXCEPTION
    WHEN OTHERS THEN
        RAISE_APPLICATION_ERROR(-20006, 'Error en PRODUCTOS_POR_CATEGORIA: ' || SQLERRM);
END;
/

SELECT
    NOMBRE_CATEGORIA,
    PRODUCTOS_POR_CATEGORIA(ID_CATEGORIA) AS CANTIDAD_PRODUCTOS
FROM CATEGORIAS;


-- =========================
-- 4. TOTAL_COMPRADO_CLIENTE
-- Retorna el total gastado por un cliente
-- =========================
CREATE OR REPLACE FUNCTION TOTAL_COMPRADO_CLIENTE
(
    P_ID_CLIENTE NUMBER
)
RETURN NUMBER
IS
    V_TOTAL NUMBER := 0;

    -- Un solo cursor que une ambas tablas y suma directo
    CURSOR C_TOTAL IS
        SELECT SUM(VENTAS.CANTIDAD * VENTAS.PRECIO_UNITARIO)
        FROM DETALLE_VENTAS
        JOIN VENTAS ON VENTAS.ID_DETALLE = DETALLE_VENTAS.ID_DETALLE
        WHERE DETALLE_VENTAS.ID_CLIENTE = P_ID_CLIENTE;

BEGIN
    IF P_ID_CLIENTE IS NULL THEN
        RAISE_APPLICATION_ERROR(-20007, 'El ID de cliente no puede ser nulo.');
    END IF;

    OPEN C_TOTAL;
    FETCH C_TOTAL INTO V_TOTAL;
    CLOSE C_TOTAL;

    RETURN NVL(V_TOTAL, 0);

EXCEPTION
    WHEN NO_DATA_FOUND THEN
        RETURN 0;
    WHEN OTHERS THEN
        RAISE_APPLICATION_ERROR(-20008, 'Error en TOTAL_COMPRADO_CLIENTE: ' || SQLERRM);
END;
/

SELECT
    NOMBRE,
    APELLIDO,
    TOTAL_COMPRADO_CLIENTE(ID_CLIENTE) AS TOTAL_GASTADO
FROM CLIENTES;
