-- =========================
-- FUNCIONES
-- =========================

-- =========================
--Crea un total de ventas 
CREATE OR REPLACE FUNCTION TOTAL_VENTA
(
    P_ID_VENTA NUMBER
)
RETURN NUMBER
IS
    V_TOTAL NUMBER;
BEGIN

SELECT SUM(CANTIDAD * PRECIO_UNITARIO)
INTO V_TOTAL
FROM DETALLE_VENTA
WHERE ID_VENTA = P_ID_VENTA;

RETURN V_TOTAL;

END;

SELECT TOTAL_VENTA(1) FROM DUAL;
-- =========================
--Para saber la cantidad de inventario que hay 
CREATE OR REPLACE FUNCTION VALOR_INVENTARIO
RETURN NUMBER
IS
    V_TOTAL NUMBER;
BEGIN

SELECT SUM(PRECIO * STOCK)
INTO V_TOTAL
FROM PRODUCTOS;

RETURN V_TOTAL;

END;

SELECT VALOR_INVENTARIO FROM DUAL;
-- =========================
--Para saber cuantos productos tiene una categoria 
CREATE OR REPLACE FUNCTION PRODUCTOS_POR_CATEGORIA
(
    P_ID_CATEGORIA NUMBER
)
RETURN NUMBER
IS
    V_TOTAL NUMBER;
BEGIN

SELECT COUNT(*)
INTO V_TOTAL
FROM PRODUCTOS
WHERE ID_CATEGORIA = P_ID_CATEGORIA;

RETURN V_TOTAL;

END;

SELECT 
NOMBRE_CATEGORIA,
PRODUCTOS_POR_CATEGORIA(ID_CATEGORIA)
FROM CATEGORIAS;

-- =========================
--Para saber cuanto a gastado un cliente en la tienda 
CREATE OR REPLACE FUNCTION TOTAL_COMPRADO_CLIENTE
(
    P_ID_CLIENTE NUMBER
)
RETURN NUMBER
IS
    V_TOTAL NUMBER;
BEGIN

SELECT SUM(TOTAL)
INTO V_TOTAL
FROM VENTAS
WHERE ID_CLIENTE = P_ID_CLIENTE;

RETURN NVL(V_TOTAL,0);

END;

SELECT 
NOMBRE,
APELLIDO,
TOTAL_COMPRADO_CLIENTE(ID_CLIENTE)
FROM CLIENTES;