-- =========================
-- CATEGORIAS
-- =========================
SET DEFINE OFF;
INSERT INTO CATEGORIAS (NOMBRE_CATEGORIA, TIPO_GENERAL) VALUES ('Teclados', 'Perifericos');

INSERT INTO CATEGORIAS (NOMBRE_CATEGORIA, TIPO_GENERAL) VALUES ('Mouses', 'Perifericos');

INSERT INTO CATEGORIAS (NOMBRE_CATEGORIA, TIPO_GENERAL) VALUES ('Microfonos', 'Perifericos');

INSERT INTO CATEGORIAS (NOMBRE_CATEGORIA, TIPO_GENERAL) VALUES ('Headsets', 'Perifericos');

INSERT INTO CATEGORIAS (NOMBRE_CATEGORIA, TIPO_GENERAL) VALUES ('Controles', 'Perifericos');

INSERT INTO CATEGORIAS (NOMBRE_CATEGORIA, TIPO_GENERAL) VALUES ('Mouse Pads', 'Perifericos');

INSERT INTO CATEGORIAS (NOMBRE_CATEGORIA, TIPO_GENERAL) VALUES ('Memoria RAM', 'Componentes');

INSERT INTO CATEGORIAS (NOMBRE_CATEGORIA, TIPO_GENERAL) VALUES ('Almacenamiento', 'Componentes');

INSERT INTO CATEGORIAS (NOMBRE_CATEGORIA, TIPO_GENERAL) VALUES ('Graficas', 'Componentes');

INSERT INTO CATEGORIAS (NOMBRE_CATEGORIA, TIPO_GENERAL) VALUES ('Refrigeraciones', 'Componentes');

INSERT INTO CATEGORIAS (NOMBRE_CATEGORIA, TIPO_GENERAL) VALUES ('Ventilacion', 'Componentes');

INSERT INTO CATEGORIAS (NOMBRE_CATEGORIA, TIPO_GENERAL) VALUES ('Televisores', 'Para el Hogar');

INSERT INTO CATEGORIAS (NOMBRE_CATEGORIA, TIPO_GENERAL) VALUES ('Routers', 'Para el Hogar');

COMMIT;
SELECT * FROM CATEGORIAS;


-- =========================
-- MARCAS
-- =========================
INSERT INTO MARCAS (NOMBRE_MARCA) VALUES ('Razer');

INSERT INTO MARCAS (NOMBRE_MARCA) VALUES ('Samsung');

INSERT INTO MARCAS (NOMBRE_MARCA) VALUES ('Logitech');

INSERT INTO MARCAS (NOMBRE_MARCA) VALUES ('Kingston');

INSERT INTO MARCAS (NOMBRE_MARCA) VALUES ('HyperX');

INSERT INTO MARCAS (NOMBRE_MARCA) VALUES ('HP');

INSERT INTO MARCAS (NOMBRE_MARCA) VALUES ('Huawei');

INSERT INTO MARCAS (NOMBRE_MARCA) VALUES ('Wacom');

INSERT INTO MARCAS (NOMBRE_MARCA) VALUES ('XP Pen');

INSERT INTO MARCAS (NOMBRE_MARCA) VALUES ('AOC');

INSERT INTO MARCAS (NOMBRE_MARCA) VALUES ('Acer');

INSERT INTO MARCAS (NOMBRE_MARCA) VALUES ('Intel');

INSERT INTO MARCAS (NOMBRE_MARCA) VALUES ('AMD');

INSERT INTO MARCAS (NOMBRE_MARCA) VALUES ('Nvidia');

INSERT INTO MARCAS (NOMBRE_MARCA) VALUES ('Aerocool');

INSERT INTO MARCAS (NOMBRE_MARCA) VALUES ('ThermalTake');

INSERT INTO MARCAS (NOMBRE_MARCA) VALUES ('Antec');

INSERT INTO MARCAS (NOMBRE_MARCA) VALUES ('Corsair');

INSERT INTO MARCAS (NOMBRE_MARCA) VALUES ('Noctua');

INSERT INTO MARCAS (NOMBRE_MARCA) VALUES ('Cooler Master');

INSERT INTO MARCAS (NOMBRE_MARCA) VALUES ('NZXT');

INSERT INTO MARCAS (NOMBRE_MARCA) VALUES ('Lian LI');

INSERT INTO MARCAS (NOMBRE_MARCA) VALUES ('Red Dragon');

INSERT INTO MARCAS (NOMBRE_MARCA) VALUES ('Adata');

INSERT INTO MARCAS (NOMBRE_MARCA) VALUES ('G.SKILL');

INSERT INTO MARCAS (NOMBRE_MARCA) VALUES ('Xiaomi');

INSERT INTO MARCAS (NOMBRE_MARCA) VALUES ('MSI');

INSERT INTO MARCAS (NOMBRE_MARCA) VALUES ('Asus');

INSERT INTO MARCAS (NOMBRE_MARCA) VALUES ('Gigabyte');

INSERT INTO MARCAS (NOMBRE_MARCA) VALUES ('LG');

INSERT INTO MARCAS (NOMBRE_MARCA) VALUES ('Aorus');

-- =========================
-- PRODUCTOS
-- =========================

-- PERIFERICOS

INSERT INTO PRODUCTOS (ID_CATEGORIA, ID_MARCA, NOMBRE, DESCRIPCION, PRECIO, STOCK, IMAGEN) VALUES (1, 1, 'Razer BlackWidow V4', 'Teclado mecanico RGB', 150, 15, 'https://www.techzilla.cr/wp-content/uploads/2024/02/1-22.jpg.webp');

INSERT INTO PRODUCTOS (ID_CATEGORIA, ID_MARCA, NOMBRE, DESCRIPCION, PRECIO, STOCK, IMAGEN) VALUES (2, 3, 'Logitech G502', 'Mouse gamer alta precision', 80, 25, 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSDJQfsyLJjNpjHmgYCKX9CbwaeBW_3WnaY8A&s');

INSERT INTO PRODUCTOS (ID_CATEGORIA, ID_MARCA, NOMBRE, DESCRIPCION, PRECIO, STOCK, IMAGEN) VALUES (3, 5, 'HyperX SoloCast', 'Microfono USB condensador', 65, 18, 'https://www.cqnetcr.com/114105-thickbox_default/microfono-hyperx-solocast-usb-led-cardioide.jpg');

INSERT INTO PRODUCTOS (ID_CATEGORIA, ID_MARCA, NOMBRE, DESCRIPCION, PRECIO, STOCK, IMAGEN) VALUES (4, 1, 'Razer Kraken X', 'Headset gamer 7.1', 90, 20, 'https://m.media-amazon.com/images/I/51EafLX7lRL._AC_UF894,1000_QL80_.jpg');

INSERT INTO PRODUCTOS (ID_CATEGORIA, ID_MARCA, NOMBRE, DESCRIPCION, PRECIO, STOCK, IMAGEN) VALUES (5, 3, 'Logitech F310', 'Control USB para PC', 40, 30, 'https://holacompras.com/wp-content/uploads/2024/09/940-000110-2.png');

INSERT INTO PRODUCTOS (ID_CATEGORIA, ID_MARCA, NOMBRE, DESCRIPCION, PRECIO, STOCK, IMAGEN) VALUES (6, 23, 'Red Dragon Flick', 'Mouse Pad XL', 20, 40, 'https://www.techzilla.cr/wp-content/uploads/2024/02/redragon-flick-3xl-p040.jpg');

INSERT INTO PRODUCTOS (ID_CATEGORIA, ID_MARCA, NOMBRE, DESCRIPCION, PRECIO, STOCK, IMAGEN) VALUES (1, 3, 'Logitech G Pro X', 'Teclado mecanico profesional', 140, 12, 'https://www.techzilla.cr/wp-content/uploads/2025/01/Sin-titulo-1-162.jpg.webp');

INSERT INTO PRODUCTOS (ID_CATEGORIA, ID_MARCA, NOMBRE, DESCRIPCION, PRECIO, STOCK, IMAGEN) VALUES (1, 28, 'Asus TUF K3', 'Teclado mecanico RGB resistente', 110, 16, 'https://m.media-amazon.com/images/I/51lcg2odrdL._AC_SL1000_.jpg');

INSERT INTO PRODUCTOS (ID_CATEGORIA, ID_MARCA, NOMBRE, DESCRIPCION, PRECIO, STOCK, IMAGEN) VALUES (1, 29, 'Gigabyte K1', 'Teclado mecanico gamer', 95, 20, 'https://www.cqnetcr.com/114736-large_default/teclado-mecanico-gigabyte-aorus-k1-usb-usb-rgb.jpg');

INSERT INTO PRODUCTOS (ID_CATEGORIA, ID_MARCA, NOMBRE, DESCRIPCION, PRECIO, STOCK, IMAGEN) VALUES (2, 1, 'Razer DeathAdder V3', 'Mouse gamer ergonomico', 85, 22, 'https://www.techzilla.cr/wp-content/uploads/2023/07/MO2118-4.jpg.webp');

INSERT INTO PRODUCTOS (ID_CATEGORIA, ID_MARCA, NOMBRE, DESCRIPCION, PRECIO, STOCK, IMAGEN) VALUES (2, 27, 'MSI Clutch GM41', 'Mouse ligero 16000 DPI', 70, 18, 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRqH33uKN1EXfGkKhDrvbI6DdcEaJ5XOJ0bXg&s');

INSERT INTO PRODUCTOS (ID_CATEGORIA, ID_MARCA, NOMBRE, DESCRIPCION, PRECIO, STOCK, IMAGEN) VALUES (2, 30, 'LG Silent Mouse', 'Mouse inalambrico silencioso', 25, 40, 'https://www.intelec.co.cr/wp-content/uploads/2024/11/910-007116-1000x1000.webp');

INSERT INTO PRODUCTOS (ID_CATEGORIA, ID_MARCA, NOMBRE, DESCRIPCION, PRECIO, STOCK, IMAGEN) VALUES (3, 5, 'HyperX QuadCast', 'Microfono RGB profesional', 130, 14, 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSVcU4kzETFxPYjbi7EcJRdtyd81m6re8puMg&s');

INSERT INTO PRODUCTOS (ID_CATEGORIA, ID_MARCA, NOMBRE, DESCRIPCION, PRECIO, STOCK, IMAGEN) VALUES (3, 6, 'HP Streaming Mic', 'Microfono USB compacto', 55, 19, 'https://hp.widen.net/content/lizgrksgs4/webp/lizgrksgs4.png?dpi=72&color=ffffff00&w=270');

INSERT INTO PRODUCTOS (ID_CATEGORIA, ID_MARCA, NOMBRE, DESCRIPCION, PRECIO, STOCK, IMAGEN) VALUES (4, 23, 'Red Dragon Zeus X', 'Headset gamer 7.1 RGB', 75, 21, 'https://extremetechcr.com/wp-content/uploads/2024/11/37890.jpg');

INSERT INTO PRODUCTOS (ID_CATEGORIA, ID_MARCA, NOMBRE, DESCRIPCION, PRECIO, STOCK, IMAGEN) VALUES (4, 1, 'Razer Barracuda X', 'Headset inalambrico', 120, 13, 'https://m.media-amazon.com/images/I/71qKH+vJ+IL._AC_SL1500_.jpg');
-- COMPONENTES
INSERT INTO PRODUCTOS (ID_CATEGORIA, ID_MARCA, NOMBRE, DESCRIPCION, PRECIO, STOCK, IMAGEN) VALUES (7, 4, 'Kingston Fury 16GB', 'RAM DDR4 16GB 3200MHz', 75, 35, 'https://www.intelec.co.cr/wp-content/uploads/2024/11/910-005469.webp');

INSERT INTO PRODUCTOS (ID_CATEGORIA, ID_MARCA, NOMBRE, DESCRIPCION, PRECIO, STOCK, IMAGEN) VALUES (7, 18, 'Corsair Vengeance 16GB', 'RAM DDR4 16GB 3200MHz', 75, 30, 'https://coretms.tecnomegastore.ec/assets/images/main/26/DIMCORH325MB638.webp');

INSERT INTO PRODUCTOS (ID_CATEGORIA, ID_MARCA, NOMBRE, DESCRIPCION, PRECIO, STOCK, IMAGEN) VALUES (7, 4, 'Kingston Fury Beast 16GB', 'RAM DDR5 16GB 5200MHz', 95, 25, 'https://media.kingston.com/kingston/product/FURY_Beast_Black_DDR4_1_pkg-zm-lg.jpg');

INSERT INTO PRODUCTOS (ID_CATEGORIA, ID_MARCA, NOMBRE, DESCRIPCION, PRECIO, STOCK, IMAGEN) VALUES (7, 25, 'G.SKILL Trident Z 32GB', 'RAM DDR4 32GB 3600MHz', 160, 15, 'https://cyberteamcr.com/wp-content/uploads/2025/10/20588_18063.jpg');

INSERT INTO PRODUCTOS (ID_CATEGORIA, ID_MARCA, NOMBRE, DESCRIPCION, PRECIO, STOCK, IMAGEN) VALUES (7, 5, 'HyperX Fury 8GB', 'RAM DDR4 8GB 3200MHz', 40, 45, 'https://gabastorecr.com/wp-content/uploads/2023/04/CP-HYPERX-HX430C15FB38-3.jpg');

INSERT INTO PRODUCTOS (ID_CATEGORIA, ID_MARCA, NOMBRE, DESCRIPCION, PRECIO, STOCK, IMAGEN) VALUES (8, 4, 'Kingston NV2 500GB', 'SSD NVMe 500GB', 60, 30, 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRzArqEmGk7l-FX2zNvSuik-iiZWMxme6GA4w&s');

INSERT INTO PRODUCTOS (ID_CATEGORIA, ID_MARCA, NOMBRE, DESCRIPCION, PRECIO, STOCK, IMAGEN) VALUES (8, 2, 'Samsung 980 Pro 2TB', 'SSD NVMe Gen4 2TB', 210, 9, 'https://m.media-amazon.com/images/I/81mJYmdViYL._SY250_.jpg');

INSERT INTO PRODUCTOS (ID_CATEGORIA, ID_MARCA, NOMBRE, DESCRIPCION, PRECIO, STOCK, IMAGEN) VALUES (8, 24, 'Adata Legend 1TB', 'SSD NVMe 1TB', 110, 22, 'https://www.intelec.co.cr/wp-content/uploads/2025/01/SLEG-860-1000GCS.png');

INSERT INTO PRODUCTOS (ID_CATEGORIA, ID_MARCA, NOMBRE, DESCRIPCION, PRECIO, STOCK, IMAGEN) VALUES (8, 24, 'Adata SU650 480GB', 'SSD SATA 480GB', 50, 28, 'https://webapi3.adata.com/storage/product/23_p_su650_04_0628.jpg');

INSERT INTO PRODUCTOS (ID_CATEGORIA, ID_MARCA, NOMBRE, DESCRIPCION, PRECIO, STOCK, IMAGEN) VALUES (9, 13, 'AMD RX 7600', 'Tarjeta grafica 8GB GDDR6', 350, 11, 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS_1Fyq8_ShJhNWj4NQbgNEnfrFn6iEps0U1w&s');

INSERT INTO PRODUCTOS (ID_CATEGORIA, ID_MARCA, NOMBRE, DESCRIPCION, PRECIO, STOCK, IMAGEN) VALUES (9, 14, 'Nvidia RTX 4060', 'Tarjeta grafica 8GB GDDR6', 400, 12, 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRpC6en7rI64nIKGcO5IZroW88IMvxruwHqrg&s');

INSERT INTO PRODUCTOS (ID_CATEGORIA, ID_MARCA, NOMBRE, DESCRIPCION, PRECIO, STOCK, IMAGEN) VALUES (9, 27, 'MSI RTX 4070', 'Tarjeta grafica 12GB', 650, 7, 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSsgtRmSlEkEXOzxNRFkUdw4VbXPlT18b0rJA&s');

INSERT INTO PRODUCTOS (ID_CATEGORIA, ID_MARCA, NOMBRE, DESCRIPCION, PRECIO, STOCK, IMAGEN) VALUES (9, 29, 'Gigabyte RTX 4090', 'Tarjeta grafica 24GB GDDR6X', 1600, 3, 'https://images-na.ssl-images-amazon.com/images/I/71TZmq7RYtL._AC_UL495_SR435,495_.jpg');

INSERT INTO PRODUCTOS (ID_CATEGORIA, ID_MARCA, NOMBRE, DESCRIPCION, PRECIO, STOCK, IMAGEN) VALUES (10, 16, 'ThermalTake Water 3.0', 'Refrigeracion liquida 240mm', 130, 10, 'https://cdn11.bigcommerce.com/s-p52by1ef7/images/stencil/1280x1280/products/89232/89470/CA-007PL12__06771__83353.1550182145.JPG?c=2');

INSERT INTO PRODUCTOS (ID_CATEGORIA, ID_MARCA, NOMBRE, DESCRIPCION, PRECIO, STOCK, IMAGEN) VALUES (10, 20, 'Cooler Master ML240L', 'Refrigeracion liquida RGB', 125, 12, 'https://m.media-amazon.com/images/I/61g3UkYPnmL._SL1500_.jpg');

INSERT INTO PRODUCTOS (ID_CATEGORIA, ID_MARCA, NOMBRE, DESCRIPCION, PRECIO, STOCK, IMAGEN) VALUES (10, 18, 'Corsair H100i', 'Watercooling 240mm', 150, 8, 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT0NqZzCtq-hshsB9yu_U3g2nFkz6vboY4Hvg&s');

INSERT INTO PRODUCTOS (ID_CATEGORIA, ID_MARCA, NOMBRE, DESCRIPCION, PRECIO, STOCK, IMAGEN) VALUES (11, 21, 'NZXT F120 RGB', 'Ventilador RGB 120mm', 30, 35, 'https://m.media-amazon.com/images/I/51dYwbuFI1L._SL1000_.jpg');

INSERT INTO PRODUCTOS (ID_CATEGORIA, ID_MARCA, NOMBRE, DESCRIPCION, PRECIO, STOCK, IMAGEN) VALUES (11, 19, 'Noctua NF-A12x25', 'Ventilador 120mm silencioso', 35, 50, 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQzSH8VG2xxvbtjy8-i_6Mxj774CY3uZPlkNA&s');

INSERT INTO PRODUCTOS (ID_CATEGORIA, ID_MARCA, NOMBRE, DESCRIPCION, PRECIO, STOCK, IMAGEN) VALUES (11, 17, 'Antec Prizm 120', 'Ventilador alto flujo', 28, 42, 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTqSOaXrpgcNUW1I8b_Ldt5_Pzpn1IYpbgAfQ&s');
-- HOGAR
INSERT INTO PRODUCTOS (ID_CATEGORIA, ID_MARCA, NOMBRE, DESCRIPCION, PRECIO, STOCK, IMAGEN) VALUES (12, 31, 'Aorus OLED 48"', 'TV OLED 4K 120Hz', 900, 5, 'https://m.media-amazon.com/images/I/71xAK1yIIwL._AC_UF894,1000_QL80_.jpg');

INSERT INTO PRODUCTOS (ID_CATEGORIA, ID_MARCA, NOMBRE, DESCRIPCION, PRECIO, STOCK, IMAGEN) VALUES (12, 2, 'Samsung Crystal 50"', 'Smart TV 4K UHD', 500, 10, 'https://me-tiendamexpress.s3.us-east-1.amazonaws.com/images/thumbs/0064255_pantalla-samsung-50-un50du7000pxpa-smart-tv-4k_600.png');

INSERT INTO PRODUCTOS (ID_CATEGORIA, ID_MARCA, NOMBRE, DESCRIPCION, PRECIO, STOCK, IMAGEN) VALUES (13, 26, 'Xiaomi Mi Router AX1800', 'Router WiFi 6 Dual Band', 85, 18, 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ4Jgdbdze_4TS6ihdqRT_EI-YZLYbJ09LsaA&s');

INSERT INTO PRODUCTOS (ID_CATEGORIA, ID_MARCA, NOMBRE, DESCRIPCION, PRECIO, STOCK, IMAGEN) VALUES (13, 7, 'Huawei WiFi Mesh 7', 'Sistema Mesh WiFi', 180, 6, 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQveSkVJGYbhXRj584YiwgGc4IrAvpihYwFQA&s');

COMMIT;

SELECT * FROM PRODUCTOS;

-- =========================
-- PRODUCTO_ATRIBUTOS
-- =========================
-- =======================================================
-- PERIFÉRICOS — Teclados
-- =======================================================


-- 1: Razer BlackWidow V4
INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (1, 'Switch', 'Razer Green Mecánico');

INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (1, 'Retroiluminación', 'RGB Chroma');

INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (1, 'Conexión', 'USB');

INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (1, 'Layout', 'Teclado Completo');

INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (1, 'Anti-ghosting', 'Sí');

-- 7: Logitech G Pro X
INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (7, 'Switch', 'GX Blue Intercambiable');

INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (7, 'Retroiluminación', 'RGB Lightsync');

INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (7, 'Conexión', 'USB');

INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (7, 'Layout', 'TKL (Sin numpad)');

INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (7, 'Anti-ghosting', 'Sí');

-- 8: Asus TUF K3
INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (8, 'Switch', 'Red Lineal');

INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (8, 'Retroiluminación', 'RGB Aura Sync');

INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (8, 'Conexión', 'USB');

INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (8, 'Resistencia', 'Certificado IP56');

INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (8, 'Layout', 'Teclado Completo');

-- 9: Gigabyte K1
INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (9, 'Switch', 'Cherry MX Red');

INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (9, 'Retroiluminación', 'RGB por tecla');

INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (9, 'Conexión', 'USB');

INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (9, 'Layout', 'Teclado Completo');

INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (9, 'Anti-ghosting', 'N-Key Rollover');

-- =======================================================
-- PERIFÉRICOS — Mouses
-- =======================================================

-- 2: Logitech G502
INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (2, 'DPI Máximo', '25600 DPI');

INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (2, 'Botones', '11');

INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (2, 'Sensor', 'HERO 25K');

INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (2, 'Conexión', 'USB');

INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (2, 'Pesos ajustables', 'Sí');

-- 10: Razer DeathAdder V3
INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (10, 'DPI Máximo', '30000 DPI');

INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (10, 'Botones', '6');

INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (10, 'Sensor', 'Focus Pro 30K');

INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (10, 'Conexión', 'USB');

INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (10, 'Peso', '59g');

-- 11: MSI Clutch GM41
INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (11, 'DPI Máximo', '16000 DPI');

INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (11, 'Botones', '6');

INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (11, 'Sensor', 'PixArt PMW3389');

INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (11, 'Conexión', 'USB');

INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (11, 'Peso', '65g');

-- 12: LG Silent Mouse
INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (12, 'DPI Máximo', '1600 DPI');

INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (12, 'Botones', '3');

INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (12, 'Conexión', 'Inalámbrico 2.4GHz');

INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (12, 'Batería', 'AA x1');

INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (12, 'Nivel de ruido', 'Silencioso (-90% ruido)');

-- =======================================================
-- PERIFÉRICOS — Micrófonos
-- =======================================================

-- 3: HyperX SoloCast
INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (3, 'Tipo de cápsula', 'Condensador');

INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (3, 'Patrón polar', 'Cardioide');

INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (3, 'Conexión', 'USB-C');

INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (3, 'Frecuencia', '20Hz - 20kHz');

INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (3, 'Resolución', '16 bit / 48kHz');

-- 13: HyperX QuadCast
INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (13, 'Tipo de cápsula', 'Condensador x4');

INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (13, 'Patrón polar', 'Estéreo / Cardioide / Bidireccional / Omnidireccional');

INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (13, 'Conexión', 'USB');

INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (13, 'Retroiluminación', 'RGB');

INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (13, 'Resolución', '24 bit / 96kHz');

-- 14: HP Streaming Mic
INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (14, 'Tipo de cápsula', 'Condensador');

INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (14, 'Patrón polar', 'Cardioide');

INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (14, 'Conexión', 'USB');

INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (14, 'Frecuencia', '100Hz - 18kHz');

INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (14, 'Resolución', '16 bit / 44.1kHz');

-- =======================================================
-- PERIFÉRICOS — Headsets
-- =======================================================

-- 4: Razer Kraken X
INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (4, 'Audio', '7.1 Surround');

INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (4, 'Drivers', '40mm');

INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (4, 'Frecuencia', '12Hz - 28kHz');

INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (4, 'Conexión', 'Jack 3.5mm');

INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (4, 'Peso', '250g');

-- 15: Red Dragon Zeus X
INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (15, 'Audio', '7.1 Virtual Surround');

INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (15, 'Drivers', '53mm');

INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (15, 'Retroiluminación', 'RGB');

INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (15, 'Conexión', 'USB');

INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (15, 'Micrófono desmontable', 'Sí');

-- 16: Razer Barracuda X
INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (16, 'Audio', 'Estéreo');

INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (16, 'Drivers', '40mm');

INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (16, 'Conexión', 'Inalámbrico 2.4GHz / USB-C');

INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (16, 'Batería', 'Hasta 50 horas');

INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (16, 'Peso', '250g');

-- =======================================================
-- PERIFÉRICOS — Controles y Mouse Pads
-- =======================================================

-- 5: Logitech F310
INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (5, 'Conexión', 'USB');

INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (5, 'Botones', '12');

INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (5, 'Vibración', 'No');

INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (5, 'Modo D/X', 'Sí (switch)');

INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (5, 'Compatible con', 'Windows / Android');

-- 6: Red Dragon Flick
INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (6, 'Tamaño', 'XL (900 x 300mm)');

INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (6, 'Grosor', '3mm');

INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (6, 'Base', 'Antideslizante');

INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (6, 'Material superficie', 'Tela microfibra');

INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (6, 'Bordes cosidos', 'Sí');

-- =======================================================
-- COMPONENTES — Memoria RAM
-- =======================================================

-- 17: Kingston Fury 16GB (DDR4)
INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (17, 'Capacidad', '16GB');
INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (17, 'Tipo', 'DDR4');

INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (17, 'Frecuencia', '3200MHz');

INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (17, 'Latencia', 'CL16');

INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (17, 'Voltaje', '1.35V');

-- 18: Corsair Vengeance 16GB
INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (18, 'Capacidad', '16GB');

INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (18, 'Tipo', 'DDR4');

INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (18, 'Frecuencia', '3200MHz');

INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (18, 'Latencia', 'CL16');

INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (18, 'Voltaje', '1.35V');

-- 19: Kingston Fury Beast 16GB (DDR5)
INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (19, 'Capacidad', '16GB');

INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (19, 'Tipo', 'DDR5');

INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (19, 'Frecuencia', '5200MHz');

INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (19, 'Latencia', 'CL40');

INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (19, 'Voltaje', '1.1V');

-- 20: G.SKILL Trident Z 32GB
INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (20, 'Capacidad', '32GB (2x16GB)');

INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (20, 'Tipo', 'DDR4');

INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (20, 'Frecuencia', '3600MHz');

INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (20, 'Latencia', 'CL18');

INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (20, 'Retroiluminación', 'RGB');

-- 21: HyperX Fury 8GB
INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (21, 'Capacidad', '8GB');

INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (21, 'Tipo', 'DDR4');

INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (21, 'Frecuencia', '3200MHz');

INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (21, 'Latencia', 'CL16');

INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (21, 'Voltaje', '1.35V');

-- =======================================================
-- COMPONENTES — Almacenamiento
-- =======================================================

-- 22: Kingston NV2 500GB
INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (22, 'Capacidad', '500GB');

INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (22, 'Tipo', 'NVMe PCIe 4.0');

INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (22, 'Lectura secuencial', '3500MB/s');

INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (22, 'Escritura secuencial', '2100MB/s');

INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (22, 'Factor de forma', 'M.2 2280');

-- 23: Samsung 980 Pro 2TB
INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (23, 'Capacidad', '2TB');

INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (23, 'Tipo', 'NVMe PCIe 4.0 Gen4');

INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (23, 'Lectura secuencial', '7000MB/s');

INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (23, 'Escritura secuencial', '5100MB/s');

INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (23, 'Factor de forma', 'M.2 2280');

-- 24: Adata Legend 1TB
INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (24, 'Capacidad', '1TB');

INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (24, 'Tipo', 'NVMe PCIe 4.0');

INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (24, 'Lectura secuencial', '5000MB/s');

INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (24, 'Escritura secuencial', '4500MB/s');

INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (24, 'Factor de forma', 'M.2 2280');

-- 25: Adata SU650 480GB
INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (25, 'Capacidad', '480GB');

INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (25, 'Tipo', 'SATA III 2.5"');

INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (25, 'Lectura secuencial', '520MB/s');

INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (25, 'Escritura secuencial', '450MB/s');

INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (25, 'Factor de forma', '2.5 pulgadas');


-- =======================================================
-- COMPONENTES — Gráficas
-- =======================================================

-- 26: AMD RX 7600
INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (26, 'VRAM', '8GB GDDR6');

INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (26, 'Bus de memoria', '128-bit');

INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (26, 'Núcleos de cómputo', '2048');

INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (26, 'TDP', '165W');

INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (26, 'Conectores de video', 'HDMI 2.1 / DP 2.1');

INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (26, 'Proceso de fabricación', '6nm');

INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (26, 'Ray Tracing', 'Sí');

-- 27: Nvidia RTX 4060
INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (27, 'VRAM', '8GB GDDR6');

INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (27, 'Bus de memoria', '128-bit');

INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (27, 'CUDA Cores', '3072');

INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (27, 'TDP', '115W');

INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (27, 'Conectores de video', 'HDMI 2.1 / DP 1.4');

INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (27, 'Proceso de fabricación', '4nm');

INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (27, 'Ray Tracing', 'Sí (3ra gen)');

-- 28: MSI RTX 4070
INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (28, 'VRAM', '12GB GDDR6X');

INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (28, 'Bus de memoria', '192-bit');

INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (28, 'CUDA Cores', '5888');

INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (28, 'TDP', '200W');

INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (28, 'Conectores de video', 'HDMI 2.1 / DP 1.4 x3');

INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (28, 'Proceso de fabricación', '4nm');

INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (28, 'Ray Tracing', 'Sí (3ra gen)');

-- 29: Gigabyte RTX 4090
INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (29, 'VRAM', '24GB GDDR6X');

INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (29, 'Bus de memoria', '384-bit');

INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (29, 'CUDA Cores', '16384');

INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (29, 'TDP', '450W');

INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (29, 'Conectores de video', 'HDMI 2.1 / DP 1.4 x3');

INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (29, 'Proceso de fabricación', '4nm');

INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (29, 'Ray Tracing', 'Sí (3ra gen)');

-- =======================================================
-- COMPONENTES — Refrigeración
-- =======================================================

-- 30: ThermalTake Water 3.0
INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (30, 'Tipo', 'Refrigeración líquida AIO');

INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (30, 'Tamaño radiador', '240mm');

INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (30, 'Ventiladores incluidos', '2 x 120mm');

INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (30, 'Socket compatible', 'LGA1700 / AM5 / AM4');

INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (30, 'Retroiluminación', 'No');

-- 31: Cooler Master ML240L
INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (31, 'Tipo', 'Refrigeración líquida AIO');

INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (31, 'Tamaño radiador', '240mm');

INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (31, 'Ventiladores incluidos', '2 x 120mm');

INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (31, 'Socket compatible', 'LGA1700 / AM4');

INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (31, 'Retroiluminación', 'RGB');

-- 32: Corsair H100i
INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (32, 'Tipo', 'Refrigeración líquida AIO');

INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (32, 'Tamaño radiador', '240mm');

INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (32, 'Ventiladores incluidos', '2 x 120mm PWM');

INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (32, 'Socket compatible', 'LGA1700 / LGA1200 / AM5 / AM4');

INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (32, 'Software', 'iCUE compatible');

-- =======================================================
-- COMPONENTES — Ventilación
-- =======================================================

-- 33: NZXT F120 RGB
INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (33, 'Diámetro', '120mm');

INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (33, 'Velocidad', '500 - 1800 rpm');

INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (33, 'Flujo de aire', '52.44 CFM');

INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (33, 'Nivel de ruido', '28 dBA');

INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (33, 'Retroiluminación', 'RGB');

-- 34: Noctua NF-A12x25
INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (34, 'Diámetro', '120mm');

INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (34, 'Velocidad', '450 - 2000 rpm');

INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (34, 'Flujo de aire', '60.09 CFM');

INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (34, 'Nivel de ruido', '22.6 dBA');

INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (34, 'Retroiluminación', 'No');

-- 35: Antec Prizm 120
INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (35, 'Diámetro', '120mm');

INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (35, 'Velocidad', '800 - 1600 rpm');

INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (35, 'Flujo de aire', '56 CFM');

INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (35, 'Nivel de ruido', '26 dBA');

INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (35, 'Retroiluminación', 'RGB Dual-ring');

-- =======================================================
-- HOGAR — Televisores
-- =======================================================

-- 36: Aorus OLED 48"
INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (36, 'Panel', 'OLED');

INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (36, 'Resolución', '4K UHD (3840x2160)');

INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (36, 'Frecuencia de refresco', '120Hz');

INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (36, 'HDR', 'HDR10 / Dolby Vision');

INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (36, 'Smart TV', 'Sí');

INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (36, 'HDMI', '4 x HDMI 2.1');

-- 37: Samsung Crystal 50"
INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (37, 'Panel', 'Crystal UHD');

INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (37, 'Resolución', '4K UHD (3840x2160)');

INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (37, 'Frecuencia de refresco', '60Hz');
INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (37, 'HDR', 'HDR10+');

INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (37, 'Smart TV', 'Sí (Tizen OS)');

INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (37, 'HDMI', '3 x HDMI 2.0');

-- =======================================================
-- HOGAR — Routers
-- =======================================================

INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (38, 'Estándar WiFi', 'WiFi 6 (802.11ax)');

INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (38, 'Velocidad', 'AX1800 (1800 Mbps)');

INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (38, 'Bandas', 'Dual Band 2.4GHz + 5GHz');

INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (38, 'Antenas', '4 antenas externas');

INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (38, 'Puertos LAN', '3 x Gigabit');

INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (39, 'Estándar WiFi', 'WiFi 7 (802.11be)');

INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (39, 'Velocidad', 'BE7200 (7200 Mbps)');

INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (39, 'Bandas', 'Tri Band 2.4 / 5 / 6GHz');

INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (39, 'Mesh', 'Sí — HiLink Mesh');

INSERT INTO PRODUCTO_ATRIBUTOS (ID_PRODUCTO, NOMBRE_ATRIBUTO, VALOR) VALUES (39, 'Puertos LAN', '4 x 2.5G + 1 x 10G');


COMMIT;

-- =========================
-- METODOS_PAGO
-- =========================
INSERT INTO METODOS_PAGO (NOMBRE) VALUES ('Efectivo');

INSERT INTO METODOS_PAGO (NOMBRE) VALUES ('Tarjeta');

INSERT INTO METODOS_PAGO (NOMBRE) VALUES ('Transferencia');
COMMIT;

-- =========================
-- CLIENTES
-- =========================
INSERT INTO CLIENTES (NOMBRE, APELLIDO) VALUES ('Luis',     'Mora');

INSERT INTO CLIENTES (NOMBRE, APELLIDO) VALUES ('Valeria',  'Castro');

INSERT INTO CLIENTES (NOMBRE, APELLIDO) VALUES ('Diego',    'Vargas');

INSERT INTO CLIENTES (NOMBRE, APELLIDO) VALUES ('Sofia',    'Jimenez');

INSERT INTO CLIENTES (NOMBRE, APELLIDO) VALUES ('Andres',   'Salazar');
COMMIT;

-- =========================
-- USUARIOS
-- ========================
INSERT INTO USUARIOS (USERNAME, PASSWORD, ROL) VALUES ('admin', 'admin123', 'ADMIN');

INSERT INTO USUARIOS (USERNAME, PASSWORD, ROL) VALUES ('vendedor1', 'vend123', 'VENDEDOR');

INSERT INTO USUARIOS (USERNAME, PASSWORD, ROL, ID_CLIENTE) VALUES ('Luis', '1234', 'CLIENTE', 1);

INSERT INTO USUARIOS (USERNAME, PASSWORD, ROL, ID_CLIENTE) VALUES ('Valeria', '1234', 'CLIENTE', 2);

INSERT INTO USUARIOS (USERNAME, PASSWORD, ROL, ID_CLIENTE)  VALUES ('diegov', '1234', 'CLIENTE', 3);

INSERT INTO USUARIOS (USERNAME, PASSWORD, ROL, ID_CLIENTE)  VALUES ('sofiaj', '1234', 'CLIENTE', 4);

INSERT INTO USUARIOS (USERNAME, PASSWORD, ROL, ID_CLIENTE)  VALUES ('andress', '1234', 'CLIENTE', 5);

COMMIT;

-- =========================
-- PROVEEDORES
-- =========================
INSERT INTO PROVEEDORES (NOMBRE, CORREO) VALUES ('Distribuidora Tech', 'ventas@distech.com');

INSERT INTO PROVEEDORES (NOMBRE, CORREO) VALUES ('Importadora Digital', 'contacto@impodigital.com');

INSERT INTO PROVEEDORES (NOMBRE, CORREO) VALUES ('CompuMayorista', 'info@compumayorista.com');
COMMIT;

-- =========================
-- TELEFONOS CLIENTES
-- =========================
INSERT INTO TELEFONOS (ID_CLIENTE, TELEFONO) VALUES (1, '84445555');

INSERT INTO TELEFONOS (ID_CLIENTE, TELEFONO) VALUES (2, '85556666');

INSERT INTO TELEFONOS (ID_CLIENTE, TELEFONO) VALUES (3, '86667777');

INSERT INTO TELEFONOS (ID_CLIENTE, TELEFONO) VALUES (4, '87778888');

INSERT INTO TELEFONOS (ID_CLIENTE, TELEFONO) VALUES (5, '88889999');
COMMIT;

-- =========================
-- CORREOS CLIENTES
-- =========================
INSERT INTO CORREOS (ID_CLIENTE, CORREO) VALUES (1, 'luis.mora@gmail.com');

INSERT INTO CORREOS (ID_CLIENTE, CORREO) VALUES (2, 'valeria.castro@hotmail.com');

INSERT INTO CORREOS (ID_CLIENTE, CORREO) VALUES (3, 'diego.vargas@outlook.com');

INSERT INTO CORREOS (ID_CLIENTE, CORREO) VALUES (4, 'sofia.jimenez@gmail.com');

INSERT INTO CORREOS (ID_CLIENTE, CORREO) VALUES (5, 'andres.salazar@yahoo.com');
COMMIT;

-- =========================
-- DIRECCIONES
-- =========================
INSERT INTO DIRECCIONES (ID_CLIENTE, DIRECCION) VALUES (1, 'Av Siempre Viva 123');

INSERT INTO DIRECCIONES (ID_CLIENTE, DIRECCION) VALUES (2, 'Calle Central 456');

INSERT INTO DIRECCIONES (ID_CLIENTE, DIRECCION) VALUES (3, 'Zona Norte 789');

INSERT INTO DIRECCIONES (ID_CLIENTE, DIRECCION) VALUES (4, 'Boulevard Principal 321');

INSERT INTO DIRECCIONES (ID_CLIENTE, DIRECCION) VALUES (5, 'Barrio Los Yoses, San Jose');

COMMIT;



-- =========================
-- TELEFONOS PROVEEDOR
-- =========================
INSERT INTO TELEFONOS_PROVEEDOR (ID_PROVEEDOR, TELEFONO) VALUES (1, '80001111');

INSERT INTO TELEFONOS_PROVEEDOR (ID_PROVEEDOR, TELEFONO) VALUES (2, '80002222');

INSERT INTO TELEFONOS_PROVEEDOR (ID_PROVEEDOR, TELEFONO) VALUES (3, '80003333');
COMMIT;


-- =========================
-- DETALLE_VENTA
-- =========================

INSERT INTO DETALLE_VENTAS (ID_CLIENTE, ID_METODO) VALUES (1, 2);

INSERT INTO DETALLE_VENTAS (ID_CLIENTE, ID_METODO) VALUES (2, 1);

INSERT INTO DETALLE_VENTAS (ID_CLIENTE, ID_METODO) VALUES (3, 3);

INSERT INTO DETALLE_VENTAS (ID_CLIENTE, ID_METODO) VALUES (4, 2);

INSERT INTO DETALLE_VENTAS (ID_CLIENTE, ID_METODO) VALUES (5, 1);

 
COMMIT;

-- =========================
-- VENTAS
-- =========================

INSERT INTO VENTAS (ID_DETALLE, ID_PRODUCTO, CANTIDAD, PRECIO_UNITARIO) VALUES (1, 1,  1, 150);

INSERT INTO VENTAS (ID_DETALLE, ID_PRODUCTO, CANTIDAD, PRECIO_UNITARIO) VALUES (1, 2,  1,  80);
 
INSERT INTO VENTAS (ID_DETALLE, ID_PRODUCTO, CANTIDAD, PRECIO_UNITARIO) VALUES (2, 4,  1,  90);
 
INSERT INTO VENTAS (ID_DETALLE, ID_PRODUCTO, CANTIDAD, PRECIO_UNITARIO) VALUES (3, 20, 1, 160);

INSERT INTO VENTAS (ID_DETALLE, ID_PRODUCTO, CANTIDAD, PRECIO_UNITARIO) VALUES (4, 17, 2,  75);

INSERT INTO VENTAS (ID_DETALLE, ID_PRODUCTO, CANTIDAD, PRECIO_UNITARIO) VALUES (4, 22, 1,  60);
 
INSERT INTO VENTAS (ID_DETALLE, ID_PRODUCTO, CANTIDAD, PRECIO_UNITARIO) VALUES (5, 27, 1, 400);
SET DEFINE ON;


COMMIT;

