-- =========================
-- TRIGGERS
-- =========================

-- =========================
--Baja la cantidad de producto cuando se hace una venta y de agrega en la tabla DETALLE_VENTA
CREATE OR REPLACE TRIGGER TRG_DESCONTAR_STOCK
AFTER INSERT ON DETALLE_VENTA
FOR EACH ROW
BEGIN
    UPDATE PRODUCTOS
    SET STOCK = STOCK - :NEW.CANTIDAD
    WHERE ID_PRODUCTO = :NEW.ID_PRODUCTO;
END;

-- =========================
--Evita que se pueda vender mas producto del que hay en stock
CREATE OR REPLACE TRIGGER TRG_VALIDAR_STOCK
BEFORE INSERT ON DETALLE_VENTA
FOR EACH ROW
DECLARE
    v_stock PRODUCTOS.STOCK%TYPE;
BEGIN
    SELECT STOCK INTO v_stock
    FROM PRODUCTOS
    WHERE ID_PRODUCTO = :NEW.ID_PRODUCTO;

    IF v_stock < :NEW.CANTIDAD THEN
        RAISE_APPLICATION_ERROR(-20001, 'No hay suficiente stock');
    END IF;
END;

-- =========================
-- Crea la cantidad de venta hecha
CREATE OR REPLACE TRIGGER TRG_CALCULAR_TOTAL
AFTER INSERT ON DETALLE_VENTA
FOR EACH ROW
BEGIN
    UPDATE VENTAS
    SET TOTAL =
    (
        SELECT SUM(CANTIDAD * PRECIO_UNITARIO)
        FROM DETALLE_VENTA
        WHERE ID_VENTA = :NEW.ID_VENTA
    )
    WHERE ID_VENTA = :NEW.ID_VENTA;
END;

-- =========================
-- Crea auditoria para las tablas mas importantes 

-- =========================================
-- AUDITORIA TABLA CATEGORIAS
-- =========================================
CREATE OR REPLACE TRIGGER TRG_AUD_CATEGORIAS
AFTER INSERT OR UPDATE OR DELETE ON CATEGORIAS
FOR EACH ROW
BEGIN

    IF INSERTING THEN
        INSERT INTO AUDITORIA_SISTEMA
            (TABLA_AFECTADA, OPERACION, ID_REGISTRO, USUARIO_DB)
        VALUES
            ('CATEGORIAS', 'INSERT', :NEW.ID_CATEGORIA, USER);

    ELSIF DELETING THEN
        INSERT INTO AUDITORIA_SISTEMA
            (TABLA_AFECTADA, OPERACION, ID_REGISTRO, USUARIO_DB)
        VALUES
            ('CATEGORIAS', 'DELETE', :OLD.ID_CATEGORIA, USER);

    ELSIF UPDATING THEN

        IF :OLD.NOMBRE_CATEGORIA <> :NEW.NOMBRE_CATEGORIA THEN
            INSERT INTO AUDITORIA_SISTEMA
                (TABLA_AFECTADA, OPERACION, ID_REGISTRO, CAMPO_MODIFICADO, VALOR_ANTERIOR, VALOR_NUEVO, USUARIO_DB)
            VALUES
                ('CATEGORIAS', 'UPDATE', :NEW.ID_CATEGORIA, 'NOMBRE_CATEGORIA', :OLD.NOMBRE_CATEGORIA, :NEW.NOMBRE_CATEGORIA, USER);
        END IF;

        IF :OLD.TIPO_GENERAL <> :NEW.TIPO_GENERAL THEN
            INSERT INTO AUDITORIA_SISTEMA
                (TABLA_AFECTADA, OPERACION, ID_REGISTRO, CAMPO_MODIFICADO, VALOR_ANTERIOR, VALOR_NUEVO, USUARIO_DB)
            VALUES
                ('CATEGORIAS', 'UPDATE', :NEW.ID_CATEGORIA, 'TIPO_GENERAL', :OLD.TIPO_GENERAL, :NEW.TIPO_GENERAL, USER);
        END IF;

    END IF;

END;
/


-- =========================================
-- AUDITORIA TABLA MARCAS
-- =========================================
CREATE OR REPLACE TRIGGER TRG_AUD_MARCAS
AFTER INSERT OR UPDATE OR DELETE ON MARCAS
FOR EACH ROW
BEGIN

    IF INSERTING THEN
        INSERT INTO AUDITORIA_SISTEMA
            (TABLA_AFECTADA, OPERACION, ID_REGISTRO, USUARIO_DB)
        VALUES
            ('MARCAS', 'INSERT', :NEW.ID_MARCA, USER);

    ELSIF DELETING THEN
        INSERT INTO AUDITORIA_SISTEMA
            (TABLA_AFECTADA, OPERACION, ID_REGISTRO, USUARIO_DB)
        VALUES
            ('MARCAS', 'DELETE', :OLD.ID_MARCA, USER);

    ELSIF UPDATING THEN

        IF :OLD.NOMBRE_MARCA <> :NEW.NOMBRE_MARCA THEN
            INSERT INTO AUDITORIA_SISTEMA
                (TABLA_AFECTADA, OPERACION, ID_REGISTRO, CAMPO_MODIFICADO, VALOR_ANTERIOR, VALOR_NUEVO, USUARIO_DB)
            VALUES
                ('MARCAS', 'UPDATE', :NEW.ID_MARCA, 'NOMBRE_MARCA', :OLD.NOMBRE_MARCA, :NEW.NOMBRE_MARCA, USER);
        END IF;

    END IF;

END;
/


-- =========================================
-- AUDITORIA TABLA METODOS_PAGO
-- =========================================
CREATE OR REPLACE TRIGGER TRG_AUD_METODOS_PAGO
AFTER INSERT OR UPDATE OR DELETE ON METODOS_PAGO
FOR EACH ROW
BEGIN

    IF INSERTING THEN
        INSERT INTO AUDITORIA_SISTEMA
            (TABLA_AFECTADA, OPERACION, ID_REGISTRO, USUARIO_DB)
        VALUES
            ('METODOS_PAGO', 'INSERT', :NEW.ID_METODO, USER);

    ELSIF DELETING THEN
        INSERT INTO AUDITORIA_SISTEMA
            (TABLA_AFECTADA, OPERACION, ID_REGISTRO, USUARIO_DB)
        VALUES
            ('METODOS_PAGO', 'DELETE', :OLD.ID_METODO, USER);

    ELSIF UPDATING THEN

        IF :OLD.NOMBRE <> :NEW.NOMBRE THEN
            INSERT INTO AUDITORIA_SISTEMA
                (TABLA_AFECTADA, OPERACION, ID_REGISTRO, CAMPO_MODIFICADO, VALOR_ANTERIOR, VALOR_NUEVO, USUARIO_DB)
            VALUES
                ('METODOS_PAGO', 'UPDATE', :NEW.ID_METODO, 'NOMBRE', :OLD.NOMBRE, :NEW.NOMBRE, USER);
        END IF;

    END IF;

END;
/


-- =========================================
-- AUDITORIA TABLA PROVEEDORES
-- =========================================
CREATE OR REPLACE TRIGGER TRG_AUD_PROVEEDORES
AFTER INSERT OR UPDATE OR DELETE ON PROVEEDORES
FOR EACH ROW
BEGIN

    IF INSERTING THEN
        INSERT INTO AUDITORIA_SISTEMA
            (TABLA_AFECTADA, OPERACION, ID_REGISTRO, USUARIO_DB)
        VALUES
            ('PROVEEDORES', 'INSERT', :NEW.ID_PROVEEDOR, USER);

    ELSIF DELETING THEN
        INSERT INTO AUDITORIA_SISTEMA
            (TABLA_AFECTADA, OPERACION, ID_REGISTRO, USUARIO_DB)
        VALUES
            ('PROVEEDORES', 'DELETE', :OLD.ID_PROVEEDOR, USER);

    ELSIF UPDATING THEN

        IF :OLD.NOMBRE <> :NEW.NOMBRE THEN
            INSERT INTO AUDITORIA_SISTEMA
                (TABLA_AFECTADA, OPERACION, ID_REGISTRO, CAMPO_MODIFICADO, VALOR_ANTERIOR, VALOR_NUEVO, USUARIO_DB)
            VALUES
                ('PROVEEDORES', 'UPDATE', :NEW.ID_PROVEEDOR, 'NOMBRE', :OLD.NOMBRE, :NEW.NOMBRE, USER);
        END IF;

        IF :OLD.CORREO <> :NEW.CORREO THEN
            INSERT INTO AUDITORIA_SISTEMA
                (TABLA_AFECTADA, OPERACION, ID_REGISTRO, CAMPO_MODIFICADO, VALOR_ANTERIOR, VALOR_NUEVO, USUARIO_DB)
            VALUES
                ('PROVEEDORES', 'UPDATE', :NEW.ID_PROVEEDOR, 'CORREO', :OLD.CORREO, :NEW.CORREO, USER);
        END IF;

    END IF;

END;
/


-- =========================================
-- AUDITORIA TABLA TELEFONOS
-- =========================================
CREATE OR REPLACE TRIGGER TRG_AUD_TELEFONOS
AFTER INSERT OR UPDATE OR DELETE ON TELEFONOS
FOR EACH ROW
BEGIN

    IF INSERTING THEN
        INSERT INTO AUDITORIA_SISTEMA
            (TABLA_AFECTADA, OPERACION, ID_REGISTRO, USUARIO_DB)
        VALUES
            ('TELEFONOS', 'INSERT', :NEW.ID_TELEFONO, USER);

    ELSIF DELETING THEN
        INSERT INTO AUDITORIA_SISTEMA
            (TABLA_AFECTADA, OPERACION, ID_REGISTRO, USUARIO_DB)
        VALUES
            ('TELEFONOS', 'DELETE', :OLD.ID_TELEFONO, USER);

    ELSIF UPDATING THEN

        IF :OLD.TELEFONO <> :NEW.TELEFONO THEN
            INSERT INTO AUDITORIA_SISTEMA
                (TABLA_AFECTADA, OPERACION, ID_REGISTRO, CAMPO_MODIFICADO, VALOR_ANTERIOR, VALOR_NUEVO, USUARIO_DB)
            VALUES
                ('TELEFONOS', 'UPDATE', :NEW.ID_TELEFONO, 'TELEFONO', :OLD.TELEFONO, :NEW.TELEFONO, USER);
        END IF;

        IF :OLD.ID_CLIENTE <> :NEW.ID_CLIENTE THEN
            INSERT INTO AUDITORIA_SISTEMA
                (TABLA_AFECTADA, OPERACION, ID_REGISTRO, CAMPO_MODIFICADO, VALOR_ANTERIOR, VALOR_NUEVO, USUARIO_DB)
            VALUES
                ('TELEFONOS', 'UPDATE', :NEW.ID_TELEFONO, 'ID_CLIENTE', TO_CHAR(:OLD.ID_CLIENTE), TO_CHAR(:NEW.ID_CLIENTE), USER);
        END IF;

    END IF;

END;
/


-- =========================================
-- AUDITORIA TABLA TELEFONOS_PROVEEDOR
-- =========================================
CREATE OR REPLACE TRIGGER TRG_AUD_TELEFONOS_PROVEEDOR
AFTER INSERT OR UPDATE OR DELETE ON TELEFONOS_PROVEEDOR
FOR EACH ROW
BEGIN

    IF INSERTING THEN
        INSERT INTO AUDITORIA_SISTEMA
            (TABLA_AFECTADA, OPERACION, ID_REGISTRO, USUARIO_DB)
        VALUES
            ('TELEFONOS_PROVEEDOR', 'INSERT', :NEW.ID_TELEFONO, USER);

    ELSIF DELETING THEN
        INSERT INTO AUDITORIA_SISTEMA
            (TABLA_AFECTADA, OPERACION, ID_REGISTRO, USUARIO_DB)
        VALUES
            ('TELEFONOS_PROVEEDOR', 'DELETE', :OLD.ID_TELEFONO, USER);

    ELSIF UPDATING THEN

        IF :OLD.TELEFONO <> :NEW.TELEFONO THEN
            INSERT INTO AUDITORIA_SISTEMA
                (TABLA_AFECTADA, OPERACION, ID_REGISTRO, CAMPO_MODIFICADO, VALOR_ANTERIOR, VALOR_NUEVO, USUARIO_DB)
            VALUES
                ('TELEFONOS_PROVEEDOR', 'UPDATE', :NEW.ID_TELEFONO, 'TELEFONO', :OLD.TELEFONO, :NEW.TELEFONO, USER);
        END IF;

        IF :OLD.ID_PROVEEDOR <> :NEW.ID_PROVEEDOR THEN
            INSERT INTO AUDITORIA_SISTEMA
                (TABLA_AFECTADA, OPERACION, ID_REGISTRO, CAMPO_MODIFICADO, VALOR_ANTERIOR, VALOR_NUEVO, USUARIO_DB)
            VALUES
                ('TELEFONOS_PROVEEDOR', 'UPDATE', :NEW.ID_TELEFONO, 'ID_PROVEEDOR', TO_CHAR(:OLD.ID_PROVEEDOR), TO_CHAR(:NEW.ID_PROVEEDOR), USER);
        END IF;

    END IF;

END;
/


-- =========================================
-- AUDITORIA TABLA CORREOS
-- =========================================
CREATE OR REPLACE TRIGGER TRG_AUD_CORREOS
AFTER INSERT OR UPDATE OR DELETE ON CORREOS
FOR EACH ROW
BEGIN

    IF INSERTING THEN
        INSERT INTO AUDITORIA_SISTEMA
            (TABLA_AFECTADA, OPERACION, ID_REGISTRO, USUARIO_DB)
        VALUES
            ('CORREOS', 'INSERT', :NEW.ID_CORREO, USER);

    ELSIF DELETING THEN
        INSERT INTO AUDITORIA_SISTEMA
            (TABLA_AFECTADA, OPERACION, ID_REGISTRO, USUARIO_DB)
        VALUES
            ('CORREOS', 'DELETE', :OLD.ID_CORREO, USER);

    ELSIF UPDATING THEN

        IF :OLD.CORREO <> :NEW.CORREO THEN
            INSERT INTO AUDITORIA_SISTEMA
                (TABLA_AFECTADA, OPERACION, ID_REGISTRO, CAMPO_MODIFICADO, VALOR_ANTERIOR, VALOR_NUEVO, USUARIO_DB)
            VALUES
                ('CORREOS', 'UPDATE', :NEW.ID_CORREO, 'CORREO', :OLD.CORREO, :NEW.CORREO, USER);
        END IF;

        IF :OLD.ID_CLIENTE <> :NEW.ID_CLIENTE THEN
            INSERT INTO AUDITORIA_SISTEMA
                (TABLA_AFECTADA, OPERACION, ID_REGISTRO, CAMPO_MODIFICADO, VALOR_ANTERIOR, VALOR_NUEVO, USUARIO_DB)
            VALUES
                ('CORREOS', 'UPDATE', :NEW.ID_CORREO, 'ID_CLIENTE', TO_CHAR(:OLD.ID_CLIENTE), TO_CHAR(:NEW.ID_CLIENTE), USER);
        END IF;

    END IF;

END;
/


-- =========================================
-- AUDITORIA TABLA DIRECCIONES
-- =========================================
CREATE OR REPLACE TRIGGER TRG_AUD_DIRECCIONES
AFTER INSERT OR UPDATE OR DELETE ON DIRECCIONES
FOR EACH ROW
BEGIN

    IF INSERTING THEN
        INSERT INTO AUDITORIA_SISTEMA
            (TABLA_AFECTADA, OPERACION, ID_REGISTRO, USUARIO_DB)
        VALUES
            ('DIRECCIONES', 'INSERT', :NEW.ID_DIRECCION, USER);

    ELSIF DELETING THEN
        INSERT INTO AUDITORIA_SISTEMA
            (TABLA_AFECTADA, OPERACION, ID_REGISTRO, USUARIO_DB)
        VALUES
            ('DIRECCIONES', 'DELETE', :OLD.ID_DIRECCION, USER);

    ELSIF UPDATING THEN

        IF :OLD.DIRECCION <> :NEW.DIRECCION THEN
            INSERT INTO AUDITORIA_SISTEMA
                (TABLA_AFECTADA, OPERACION, ID_REGISTRO, CAMPO_MODIFICADO, VALOR_ANTERIOR, VALOR_NUEVO, USUARIO_DB)
            VALUES
                ('DIRECCIONES', 'UPDATE', :NEW.ID_DIRECCION, 'DIRECCION', :OLD.DIRECCION, :NEW.DIRECCION, USER);
        END IF;

        IF :OLD.ID_CLIENTE <> :NEW.ID_CLIENTE THEN
            INSERT INTO AUDITORIA_SISTEMA
                (TABLA_AFECTADA, OPERACION, ID_REGISTRO, CAMPO_MODIFICADO, VALOR_ANTERIOR, VALOR_NUEVO, USUARIO_DB)
            VALUES
                ('DIRECCIONES', 'UPDATE', :NEW.ID_DIRECCION, 'ID_CLIENTE', TO_CHAR(:OLD.ID_CLIENTE), TO_CHAR(:NEW.ID_CLIENTE), USER);
        END IF;

    END IF;

END;
/


-- =========================================
-- AUDITORIA TABLA USUARIOS
-- =========================================
CREATE OR REPLACE TRIGGER TRG_AUD_USUARIOS
AFTER INSERT OR UPDATE OR DELETE ON USUARIOS
FOR EACH ROW
BEGIN

    IF INSERTING THEN
        INSERT INTO AUDITORIA_SISTEMA
            (TABLA_AFECTADA, OPERACION, ID_REGISTRO, USUARIO_DB)
        VALUES
            ('USUARIOS', 'INSERT', :NEW.ID_USUARIO, USER);

    ELSIF DELETING THEN
        INSERT INTO AUDITORIA_SISTEMA
            (TABLA_AFECTADA, OPERACION, ID_REGISTRO, USUARIO_DB)
        VALUES
            ('USUARIOS', 'DELETE', :OLD.ID_USUARIO, USER);

    ELSIF UPDATING THEN

        IF :OLD.USERNAME <> :NEW.USERNAME THEN
            INSERT INTO AUDITORIA_SISTEMA
                (TABLA_AFECTADA, OPERACION, ID_REGISTRO, CAMPO_MODIFICADO, VALOR_ANTERIOR, VALOR_NUEVO, USUARIO_DB)
            VALUES
                ('USUARIOS', 'UPDATE', :NEW.ID_USUARIO, 'USERNAME', :OLD.USERNAME, :NEW.USERNAME, USER);
        END IF;

        -- Se audita el cambio de password pero sin guardar el valor real por seguridad
        IF :OLD.PASSWORD <> :NEW.PASSWORD THEN
            INSERT INTO AUDITORIA_SISTEMA
                (TABLA_AFECTADA, OPERACION, ID_REGISTRO, CAMPO_MODIFICADO, VALOR_ANTERIOR, VALOR_NUEVO, USUARIO_DB)
            VALUES
                ('USUARIOS', 'UPDATE', :NEW.ID_USUARIO, 'PASSWORD', '********', '********', USER);
        END IF;

        IF :OLD.ROL <> :NEW.ROL THEN
            INSERT INTO AUDITORIA_SISTEMA
                (TABLA_AFECTADA, OPERACION, ID_REGISTRO, CAMPO_MODIFICADO, VALOR_ANTERIOR, VALOR_NUEVO, USUARIO_DB)
            VALUES
                ('USUARIOS', 'UPDATE', :NEW.ID_USUARIO, 'ROL', :OLD.ROL, :NEW.ROL, USER);
        END IF;

    END IF;

END;
/


-- =========================================
-- AUDITORIA TABLA PRODUCTO_ATRIBUTOS
-- =========================================
CREATE OR REPLACE TRIGGER TRG_AUD_PRODUCTO_ATRIBUTOS
AFTER INSERT OR UPDATE OR DELETE ON PRODUCTO_ATRIBUTOS
FOR EACH ROW
BEGIN

    IF INSERTING THEN
        INSERT INTO AUDITORIA_SISTEMA
            (TABLA_AFECTADA, OPERACION, ID_REGISTRO, USUARIO_DB)
        VALUES
            ('PRODUCTO_ATRIBUTOS', 'INSERT', :NEW.ID_ATRIBUTO, USER);

    ELSIF DELETING THEN
        INSERT INTO AUDITORIA_SISTEMA
            (TABLA_AFECTADA, OPERACION, ID_REGISTRO, USUARIO_DB)
        VALUES
            ('PRODUCTO_ATRIBUTOS', 'DELETE', :OLD.ID_ATRIBUTO, USER);

    ELSIF UPDATING THEN

        IF :OLD.NOMBRE_ATRIBUTO <> :NEW.NOMBRE_ATRIBUTO THEN
            INSERT INTO AUDITORIA_SISTEMA
                (TABLA_AFECTADA, OPERACION, ID_REGISTRO, CAMPO_MODIFICADO, VALOR_ANTERIOR, VALOR_NUEVO, USUARIO_DB)
            VALUES
                ('PRODUCTO_ATRIBUTOS', 'UPDATE', :NEW.ID_ATRIBUTO, 'NOMBRE_ATRIBUTO', :OLD.NOMBRE_ATRIBUTO, :NEW.NOMBRE_ATRIBUTO, USER);
        END IF;

        IF :OLD.VALOR <> :NEW.VALOR THEN
            INSERT INTO AUDITORIA_SISTEMA
                (TABLA_AFECTADA, OPERACION, ID_REGISTRO, CAMPO_MODIFICADO, VALOR_ANTERIOR, VALOR_NUEVO, USUARIO_DB)
            VALUES
                ('PRODUCTO_ATRIBUTOS', 'UPDATE', :NEW.ID_ATRIBUTO, 'VALOR', :OLD.VALOR, :NEW.VALOR, USER);
        END IF;

    END IF;

END;
/


-- =========================================
-- AUDITORIA TABLA CARRITO
-- =========================================
CREATE OR REPLACE TRIGGER TRG_AUD_CARRITO
AFTER INSERT OR UPDATE OR DELETE ON CARRITO
FOR EACH ROW
BEGIN

    IF INSERTING THEN
        INSERT INTO AUDITORIA_SISTEMA
            (TABLA_AFECTADA, OPERACION, ID_REGISTRO, USUARIO_DB)
        VALUES
            ('CARRITO', 'INSERT', :NEW.ID_CARRITO, USER);

    ELSIF DELETING THEN
        INSERT INTO AUDITORIA_SISTEMA
            (TABLA_AFECTADA, OPERACION, ID_REGISTRO, USUARIO_DB)
        VALUES
            ('CARRITO', 'DELETE', :OLD.ID_CARRITO, USER);

    ELSIF UPDATING THEN

        IF :OLD.CANTIDAD <> :NEW.CANTIDAD THEN
            INSERT INTO AUDITORIA_SISTEMA
                (TABLA_AFECTADA, OPERACION, ID_REGISTRO, CAMPO_MODIFICADO, VALOR_ANTERIOR, VALOR_NUEVO, USUARIO_DB)
            VALUES
                ('CARRITO', 'UPDATE', :NEW.ID_CARRITO, 'CANTIDAD', TO_CHAR(:OLD.CANTIDAD), TO_CHAR(:NEW.CANTIDAD), USER);
        END IF;

        IF :OLD.ID_PRODUCTO <> :NEW.ID_PRODUCTO THEN
            INSERT INTO AUDITORIA_SISTEMA
                (TABLA_AFECTADA, OPERACION, ID_REGISTRO, CAMPO_MODIFICADO, VALOR_ANTERIOR, VALOR_NUEVO, USUARIO_DB)
            VALUES
                ('CARRITO', 'UPDATE', :NEW.ID_CARRITO, 'ID_PRODUCTO', TO_CHAR(:OLD.ID_PRODUCTO), TO_CHAR(:NEW.ID_PRODUCTO), USER);
        END IF;

    END IF;

END;
/
-- =========================================
-- AUDITORIA TABLA PRODUCTOS
-- =========================================
CREATE OR REPLACE TRIGGER TRG_AUD_PRODUCTOS
AFTER INSERT OR UPDATE OR DELETE ON PRODUCTOS
FOR EACH ROW
BEGIN

    IF INSERTING THEN
        INSERT INTO AUDITORIA_SISTEMA
            (TABLA_AFECTADA, OPERACION, ID_REGISTRO, USUARIO_DB)
        VALUES
            ('PRODUCTOS', 'INSERT', :NEW.ID_PRODUCTO, USER);

    ELSIF DELETING THEN
        INSERT INTO AUDITORIA_SISTEMA
            (TABLA_AFECTADA, OPERACION, ID_REGISTRO, USUARIO_DB)
        VALUES
            ('PRODUCTOS', 'DELETE', :OLD.ID_PRODUCTO, USER);

    ELSIF UPDATING THEN

        IF :OLD.PRECIO <> :NEW.PRECIO THEN
            INSERT INTO AUDITORIA_SISTEMA
                (TABLA_AFECTADA, OPERACION, ID_REGISTRO, CAMPO_MODIFICADO, VALOR_ANTERIOR, VALOR_NUEVO, USUARIO_DB)
            VALUES
                ('PRODUCTOS', 'UPDATE', :NEW.ID_PRODUCTO, 'PRECIO', TO_CHAR(:OLD.PRECIO), TO_CHAR(:NEW.PRECIO), USER);
        END IF;

        IF :OLD.STOCK <> :NEW.STOCK THEN
            INSERT INTO AUDITORIA_SISTEMA
                (TABLA_AFECTADA, OPERACION, ID_REGISTRO, CAMPO_MODIFICADO, VALOR_ANTERIOR, VALOR_NUEVO, USUARIO_DB)
            VALUES
                ('PRODUCTOS', 'UPDATE', :NEW.ID_PRODUCTO, 'STOCK', TO_CHAR(:OLD.STOCK), TO_CHAR(:NEW.STOCK), USER);
        END IF;

        IF :OLD.NOMBRE <> :NEW.NOMBRE THEN
            INSERT INTO AUDITORIA_SISTEMA
                (TABLA_AFECTADA, OPERACION, ID_REGISTRO, CAMPO_MODIFICADO, VALOR_ANTERIOR, VALOR_NUEVO, USUARIO_DB)
            VALUES
                ('PRODUCTOS', 'UPDATE', :NEW.ID_PRODUCTO, 'NOMBRE', :OLD.NOMBRE, :NEW.NOMBRE, USER);
        END IF;

    END IF;

END;
/

-- =========================================
-- AUDITORIA TABLA DETALLE_VENTAS
-- =========================================
CREATE OR REPLACE TRIGGER TRG_AUD_DETALLE_VENTAS
AFTER INSERT OR UPDATE OR DELETE ON DETALLE_VENTAS
FOR EACH ROW
BEGIN

    IF INSERTING THEN
        INSERT INTO AUDITORIA_SISTEMA
            (TABLA_AFECTADA, OPERACION, ID_REGISTRO, USUARIO_DB)
        VALUES
            ('DETALLE_VENTAS', 'INSERT', :NEW.ID_DETALLE, USER);

    ELSIF DELETING THEN
        INSERT INTO AUDITORIA_SISTEMA
            (TABLA_AFECTADA, OPERACION, ID_REGISTRO, USUARIO_DB)
        VALUES
            ('DETALLE_VENTAS', 'DELETE', :OLD.ID_DETALLE, USER);

    ELSIF UPDATING THEN

        IF :OLD.ID_CLIENTE <> :NEW.ID_CLIENTE THEN
            INSERT INTO AUDITORIA_SISTEMA
                (TABLA_AFECTADA, OPERACION, ID_REGISTRO, CAMPO_MODIFICADO, VALOR_ANTERIOR, VALOR_NUEVO, USUARIO_DB)
            VALUES
                ('DETALLE_VENTAS', 'UPDATE', :NEW.ID_DETALLE, 'ID_CLIENTE', TO_CHAR(:OLD.ID_CLIENTE), TO_CHAR(:NEW.ID_CLIENTE), USER);
        END IF;

        IF :OLD.ID_METODO <> :NEW.ID_METODO THEN
            INSERT INTO AUDITORIA_SISTEMA
                (TABLA_AFECTADA, OPERACION, ID_REGISTRO, CAMPO_MODIFICADO, VALOR_ANTERIOR, VALOR_NUEVO, USUARIO_DB)
            VALUES
                ('DETALLE_VENTAS', 'UPDATE', :NEW.ID_DETALLE, 'ID_METODO', TO_CHAR(:OLD.ID_METODO), TO_CHAR(:NEW.ID_METODO), USER);
        END IF;

        IF :OLD.FECHA_VENTA <> :NEW.FECHA_VENTA THEN
            INSERT INTO AUDITORIA_SISTEMA
                (TABLA_AFECTADA, OPERACION, ID_REGISTRO, CAMPO_MODIFICADO, VALOR_ANTERIOR, VALOR_NUEVO, USUARIO_DB)
            VALUES
                ('DETALLE_VENTAS', 'UPDATE', :NEW.ID_DETALLE, 'FECHA_VENTA', TO_CHAR(:OLD.FECHA_VENTA, 'DD/MM/YYYY'), TO_CHAR(:NEW.FECHA_VENTA, 'DD/MM/YYYY'), USER);
        END IF;

    END IF;

END;
/

-- =========================================
-- AUDITORIA TABLA VENTAS
-- =========================================
CREATE OR REPLACE TRIGGER TRG_AUD_VENTAS
AFTER INSERT OR UPDATE OR DELETE ON VENTAS
FOR EACH ROW
BEGIN

    IF INSERTING THEN
        INSERT INTO AUDITORIA_SISTEMA
            (TABLA_AFECTADA, OPERACION, ID_REGISTRO, USUARIO_DB)
        VALUES
            ('VENTAS', 'INSERT', :NEW.ID_VENTA, USER);

    ELSIF DELETING THEN
        INSERT INTO AUDITORIA_SISTEMA
            (TABLA_AFECTADA, OPERACION, ID_REGISTRO, USUARIO_DB)
        VALUES
            ('VENTAS', 'DELETE', :OLD.ID_VENTA, USER);

    ELSIF UPDATING THEN

        IF :OLD.CANTIDAD <> :NEW.CANTIDAD THEN
            INSERT INTO AUDITORIA_SISTEMA
                (TABLA_AFECTADA, OPERACION, ID_REGISTRO, CAMPO_MODIFICADO, VALOR_ANTERIOR, VALOR_NUEVO, USUARIO_DB)
            VALUES
                ('VENTAS', 'UPDATE', :NEW.ID_VENTA, 'CANTIDAD', TO_CHAR(:OLD.CANTIDAD), TO_CHAR(:NEW.CANTIDAD), USER);
        END IF;

        IF :OLD.PRECIO_UNITARIO <> :NEW.PRECIO_UNITARIO THEN
            INSERT INTO AUDITORIA_SISTEMA
                (TABLA_AFECTADA, OPERACION, ID_REGISTRO, CAMPO_MODIFICADO, VALOR_ANTERIOR, VALOR_NUEVO, USUARIO_DB)
            VALUES
                ('VENTAS', 'UPDATE', :NEW.ID_VENTA, 'PRECIO_UNITARIO', TO_CHAR(:OLD.PRECIO_UNITARIO), TO_CHAR(:NEW.PRECIO_UNITARIO), USER);
        END IF;

    END IF;

END;
/


-- =========================================
-- AUDITORIA TABLA CLIENTES
-- =========================================
CREATE OR REPLACE TRIGGER TRG_AUD_CLIENTES
AFTER INSERT OR UPDATE OR DELETE ON CLIENTES
FOR EACH ROW
BEGIN

    IF INSERTING THEN
        INSERT INTO AUDITORIA_SISTEMA
            (TABLA_AFECTADA, OPERACION, ID_REGISTRO, USUARIO_DB)
        VALUES
            ('CLIENTES', 'INSERT', :NEW.ID_CLIENTE, USER);

    ELSIF DELETING THEN
        INSERT INTO AUDITORIA_SISTEMA
            (TABLA_AFECTADA, OPERACION, ID_REGISTRO, USUARIO_DB)
        VALUES
            ('CLIENTES', 'DELETE', :OLD.ID_CLIENTE, USER);

    ELSIF UPDATING THEN

        IF :OLD.NOMBRE <> :NEW.NOMBRE THEN
            INSERT INTO AUDITORIA_SISTEMA
                (TABLA_AFECTADA, OPERACION, ID_REGISTRO, CAMPO_MODIFICADO, VALOR_ANTERIOR, VALOR_NUEVO, USUARIO_DB)
            VALUES
                ('CLIENTES', 'UPDATE', :NEW.ID_CLIENTE, 'NOMBRE', :OLD.NOMBRE, :NEW.NOMBRE, USER);
        END IF;

        IF :OLD.APELLIDO <> :NEW.APELLIDO THEN
            INSERT INTO AUDITORIA_SISTEMA
                (TABLA_AFECTADA, OPERACION, ID_REGISTRO, CAMPO_MODIFICADO, VALOR_ANTERIOR, VALOR_NUEVO, USUARIO_DB)
            VALUES
                ('CLIENTES', 'UPDATE', :NEW.ID_CLIENTE, 'APELLIDO', :OLD.APELLIDO, :NEW.APELLIDO, USER);
        END IF;

    END IF;

END;
/

SELECT * FROM AUDITORIA_SISTEMA;